<?php
include_once "Badnet/Badnet.inc";

$indice = BADNET_DIV;
define('BDIV_PAGE_GROUPS',      $indice++);
define('BDIV_FILL_GROUPS',      $indice++);
define('BDIV_PAGE_GROUP',       $indice++);
define('BDIV_PAGE_ADD_GROUP',   $indice++);
define('BDIV_ADD_GROUP',   		$indice++);
define('BDIV_PAGE_GROUPDEF',    $indice++);
define('BDIV_UPDATE_GROUPDEF',  $indice++);
define('BDIV_PAGE_TIESDEF',     $indice++);
define('BDIV_UPDATE_TIESDEF',   $indice++);
define('BDIV_PAGE_MATCHSDEF',   $indice++);
define('BDIV_UPDATE_MATCHSDEF', $indice++);
define('BDIV_PAGE_COMPO',       $indice++);
define('BDIV_UPDATE_COMPO',     $indice++);
define('BDIV_PAGE_CALENDAR',    $indice++);
define('BDIV_UPDATE_CALENDAR',  $indice++);
define('BDIV_PAGE_DELETE_GROUP', $indice++);
define('BDIV_DELETE_GROUP',     $indice++);
?>