<?php
/*****************************************************************************
!   Module     : Schedu
!   File       : $Source: /cvsroot/aotb/badnet/src/schedu/schedu.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.11 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/18 07:51:21 $
!   Mailto     : cage@free.fr
******************************************************************************/

define("SCHEDU_INSERT",          WBS_ACT_SCHEDU+1);
define("SCHEDU_REPLACE",         WBS_ACT_SCHEDU+2);


define("SCHEDU_UPDATE",   WBS_ACT_SCHEDU+1);
define("SCHEDU_REVERSE",  WBS_ACT_SCHEDU+2);
define("SCHEDU_SELECT",   WBS_ACT_SCHEDU+3);
define("SCHEDU_EDIT",     WBS_ACT_SCHEDU+4);
define("SCHEDU_UPDATE_ONE", WBS_ACT_SCHEDU+5);
define("SCHEDU_SELECT_NUM", WBS_ACT_SCHEDU+6);
define("SCHEDU_UPDATE_NUM", WBS_ACT_SCHEDU+7);
define("SCHEDU_PLACE",      WBS_ACT_SCHEDU+8);
define("SCHEDU_ANALYSE",    WBS_ACT_SCHEDU+9);

define("SCHEDU_CONFIRM",      WBS_ACT_SCHEDU+10);
define("SCHEDU_RAZ",          WBS_ACT_SCHEDU+11);
define("SCHEDU_INSERTMATCH",  WBS_ACT_SCHEDU+12);
define("SCHEDU_REPLACEMATCH", WBS_ACT_SCHEDU+13);
define("SCHEDU_DELETEMATCH",  WBS_ACT_SCHEDU+14);
define("SCHEDU_REMOVEMATCH",  WBS_ACT_SCHEDU+15);
define("SCHEDU_EDITTIME",     WBS_ACT_SCHEDU+16);
define("SCHEDU_UPDATETIME",   WBS_ACT_SCHEDU+17);
define("SCHEDU_CONVOC",       WBS_ACT_SCHEDU+18);
define("SCHEDU_CONVOCMAIL",   WBS_ACT_SCHEDU+19);
define("SCHEDU_CONVOCUPDATE", WBS_ACT_SCHEDU+20);
define("SCHEDU_PUBLICATION",  WBS_ACT_SCHEDU+22);

define("SCHEDU_PDF",           WBS_ACT_SCHEDU+30);
define("SCHEDU_PDF_INDIV",     WBS_ACT_SCHEDU+31);
define("SCHEDU_PDF_ALLINDIV",  WBS_ACT_SCHEDU+32);
define("SCHEDU_SELECT_AUTO",   WBS_ACT_SCHEDU+33);
define("SCHEDU_AUTO",          WBS_ACT_SCHEDU+34);

define("SCHEDU_EDIT_CONTACT",   WBS_ACT_SCHEDU+35);
define("SCHEDU_UPDATE_CONTACT", WBS_ACT_SCHEDU+36);
define("SCHEDU_PDF_PLAYER",     WBS_ACT_SCHEDU+37);
define("SCHEDU_NB_MATCH",       WBS_ACT_SCHEDU+38);
define("SCHEDU_DISPLAY_BLABLA", WBS_ACT_SCHEDU+39);
define("SCHEDU_PAUSE",          WBS_ACT_SCHEDU+40);
define("SCHEDU_INVERT_MATCH",   WBS_ACT_SCHEDU+41);

?>
