<?php 
define('LOC_ITEM_TIES','Rencontres'); 
define('LOC_ITEM_MY_TEAMS','Mes équipes'); 
define('LOC_ITEM_MY_TIES','Mes rencontres'); 
define('LOC_ITEM_EVENT','Tournoi'); 
define('LOC_ITEM_TRANSFERT','Transfert'); 
define('LOC_ITEM_IMPORT','Importation'); 
define('LOC_ITEM_TOURNAMENTS','Tournois'); 
define('LOC_ITEM_RESULTS','Résultats'); 
define('LOC_ITEM_TOUR','Circuits'); 
define('LOC_ITEM_INLINE','Inscription en ligne'); 
define('LOC_ITEM_MY_ACCOUNT','Mon compte'); 
define('LOC_ITEM_MY_CLUB','Mon association'); 
define('LOC_ITEM_MY_PLAYERS','Mes joueurs'); 
define('LOC_ITEM_MY_TOURNAMENTS','Mes tournois'); 
define('LOC_ITEM_ADMINISTRATION','Administration'); 
define('LOC_MSG_EMAIL_SEND','Votre email a bien été envoyé. Si vous ne recevez une copie, vérifier les paramètres anti-span de votre lecteur d\'email.
			'); 
define('LOC_TITLE_EMAIL','Envoyer un email'); 
define('LOC_LABEL_OBJECT','Sujet'); 
define('LOC_LABEL_FROM','Votre email'); 
define('LOC_LABEL_BODY','Message'); 
define('LOC_TIP_EMAIL','
				Email - Pour contacter les responsables de Badminton
				Netware
			'); 
define('LOC_ITEM_LIVE','Scores'); 
define('LOC_ITEM_UMPIRE','Arbitrage'); 
define('LOC_ITEM_ACCOUNTS','Comptes'); 
define('LOC_ITEM_ADHES','Adhérents'); 
define('LOC_ITEM_MEMBERS','Joueurs'); 
define('LOC_ITEM_ASSOCS','Associations'); 
define('LOC_ITEM_USER','Utilisation'); 
define('LOC_ITEM_MY_RESULTS','Mes résultats'); 
define('LOC_ITEM_ADHESION','Mon adhésion'); 
define('LOC_TIP_LOGOUT','
				Déconnexion - Cliquez ici pour terminer votre session
				BadNet
			'); 
?>