<?php
/*****************************************************************************
!   $Id$
******************************************************************************/
include_once 'Badnetmenu/Badnetmenu.inc';

$indice = BNETMENU_MENU;
define('MENU_ADM',     $indice++);
define('MENU_USER',    $indice++);
define('MENU_VISITOR', $indice++);
define('MENU_UMPIRE',  $indice++);
define('MENU_EMPTY',   $indice++);
define('MENU_LOGOUT',  $indice++);
define('MENU_BADNET',  $indice++);
define('MENU_CAPTAIN', $indice++);
define('MENU_TEAM',    $indice++);

define('MENU_FILL_EMAIL', $indice++);
define('MENU_SEND_EMAIL', $indice++);
define('MENU_EMAIL_SENDED', $indice++);
define('MENU_PLAYER',       $indice++);
define('MENU_ASSOC',        $indice++);




?>