<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Type des association
define('OASSO_TYPE_FEDE',    50);
define('OASSO_TYPE_UMPIRE',  51);
define('OASSO_TYPE_LIGUE',   52);
define('OASSO_TYPE_CODEP',   53);
define('OASSO_TYPE_CLUB',    54);
define('OASSO_TYPE_SCHOOL',  55);
define('OASSO_TYPE_OTHER',   56);
define('OASSO_TYPE_CORPO',   57);
define('OASSO_TYPE_PRIVATE', 58);
?>
