<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Type des commandes
define('OCOMMAND_TYPE_NONE',        420);
define('OCOMMAND_TYPE_ADHESION',    421);
define('OCOMMAND_TYPE_TOURNAMENT',  422);
define('OCOMMAND_TYPE_CIRCUIT',     423);
define('OCOMMAND_TYPE_INLINEREG',   424);
define('OCOMMAND_TYPE_WORKDAY',     425);
define('OCOMMAND_TYPE_FORMATION',   426);
define('OCOMMAND_TYPE_TICKNETS',    427);

// Moyens de paiement
define("OCOMMAND_PAYED_NONE",    180);
define("OCOMMAND_PAYED_CREDIT",  181);
define("OCOMMAND_PAYED_MONEY",   182);
define("OCOMMAND_PAYED_CHECK",   183);
define("OCOMMAND_PAYED_CB",      184);
define("OCOMMAND_PAYED_INLINE",  185);
define("OCOMMAND_PAYED_VIREMENT",186);



?>
