<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Draw type
define("ODRAW_TYPE_GROUP",   10);
define("ODRAW_TYPE_QUALIF",  11);
define("ODRAW_TYPE_TABLEAU", 12);
define("ODRAW_TYPE_SWISS",   13);
define("ODRAW_TYPE_TEAM_GROUP", 15);
define("ODRAW_TYPE_TEAM_BACK",  16);
define("ODRAW_TYPE_TEAM_KO",    17);
define("ODRAW_TYPE_CONSOL",     18);
?>
