<?php
// Position d'une paire dans un match
define("OPAIR_POS_TOP",      130);
define("OPAIR_POS_BOTTOM",   131);

// Pair status
define("OPAIR_STATUS_DNS",        89);
define("OPAIR_STATUS_MAINDRAW",   90);
define("OPAIR_STATUS_QUALIF",     91);
define("OPAIR_STATUS_RESERVE",    92);
define("OPAIR_STATUS_PTQ",        93);
define("OPAIR_STATUS_PFR",        94);
define("OPAIR_STATUS_PTM",        95);
define("OPAIR_STATUS_PFQ",        96);
define("OPAIR_STATUS_WDN",        97);
define("OPAIR_STATUS_INJ",        98);
define("OPAIR_STATUS_NONE",       99);

// Resultat d'une paire dans un match
define("OPAIR_RES_NOPLAY",    80);
define("OPAIR_RES_WIN",       81);
define("OPAIR_RES_WINAB",     82);
define("OPAIR_RES_WINWO",     83);
define("OPAIR_RES_LOOSE",     84);
define("OPAIR_RES_LOOSEAB",   85);
define("OPAIR_RES_LOOSEWO",   86);

// Etat d'une paire
define("OPAIR_STATE_NOK",  370); // Paire incomplete
define("OPAIR_STATE_REG",  371); // Paire complete inscrite
define("OPAIR_STATE_COM",  372); // Paire complete composee

?>