<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Sexe d'un joueur
define('OPLAYER_GENDER_MALE',      6);
define('OPLAYER_GENDER_FEMALE',    7);

// Status d'un joueur
define('OPLAYER_STATUS_PRESENT',  160); // Present
define('OPLAYER_STATUS_ABSENT',   161); // Absent
define('OPLAYER_STATUS_WARMUP',   162); // En salle d'echauffement
define('OPLAYER_STATUS_CALL',     163); // En chambre d'appel
define('OPLAYER_STATUS_UNKNOW',   164); // Inconnu

// Categorie d'age
define('OPLAYER_CATAGE_POU',  301);
define('OPLAYER_CATAGE_U11',  301);
define('OPLAYER_CATAGE_BEN',  302);
define('OPLAYER_CATAGE_U13',  302);
define('OPLAYER_CATAGE_MIN',  303);
define('OPLAYER_CATAGE_U15',  303);
define('OPLAYER_CATAGE_CAD',  304);
define('OPLAYER_CATAGE_U17',  304);
define('OPLAYER_CATAGE_JUN',  305);
define('OPLAYER_CATAGE_U19',  305);
define('OPLAYER_CATAGE_SEN',  306);
define('OPLAYER_CATAGE_VET',  307);

define('OPLAYER_DISCIPLINE_MS',  1);
define('OPLAYER_DISCIPLINE_WS',  2);
define('OPLAYER_DISCIPLINE_MD',  3);
define('OPLAYER_DISCIPLINE_WD',  4);
define('OPLAYER_DISCIPLINE_MX',  5);

define('OPLAYER_SURCLASSE_NONE',    350);
define('OPLAYER_SURCLASSE_SIMPLE',  351);
define('OPLAYER_SURCLASSE_DOUBLE',  352);
define('OPLAYER_SURCLASSE_VA',      353);
define('OPLAYER_SURCLASSE_SE',      354);
define('OPLAYER_SURCLASSE_SP',      355);

?>
