<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/

define('OPUBLIC_DATA_UNDELETE',  0);
define('OPUBLIC_DATA_DELETE',    1);
define('OPUBLIC_DATA_PUBLIC',    2);
define('OPUBLIC_DATA_PRIVATE',   4);
define('OPUBLIC_DATA_CONFIDENT', 8);
define('OPUBLIC_DATA_ARCHIVED', 16);

?>
