<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Type des inscriptions
define('OREGI_TYPE_PLAYER',     60);
define('OREGI_TYPE_REFEREE',    61);
define('OREGI_TYPE_DEPUTY',     62);
define('OREGI_TYPE_UMPIRE',     63);
define('OREGI_TYPE_LINEJUDGE',  64);
define('OREGI_TYPE_COACH',      65);
define('OREGI_TYPE_CONSEILLER', 66);
define('OREGI_TYPE_DELEGUE',    67);
define('OREGI_TYPE_SCORER',     68);

define('OREGI_TYPE_VOLUNTEER',    170);
define('OREGI_TYPE_ORGANISATION', 171);
define('OREGI_TYPE_VIP',          172);
define('OREGI_TYPE_PRESS',        173);
define('OREGI_TYPE_GUEST',        174);
define('OREGI_TYPE_MEDICAL',      175);
define('OREGI_TYPE_EXHIBITOR',    176);
define('OREGI_TYPE_PLATEAU',      177);
define('OREGI_TYPE_SECURITE',     178);
define('OREGI_TYPE_OTHER',        179);

?>
