<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Formule du tour
//define('OROUND_FORMULA_GROUP'	,  10);
//define('OROUND_FORMULA_GROUP'	,  11);

define('OROUND_FORMULA_GROUPTAB',  12);
define('OROUND_FORMULA_PLAPOULE',  13);
define('OROUND_FORMULA_QUALIF'	,  14);
define('OROUND_FORMULA_GROUP'	,  15);
define('OROUND_FORMULA_AR'	,      16);
define('OROUND_FORMULA_KO'	,      17);
define('OROUND_FORMULA_PLATEAU',   18);
define('OROUND_FORMULA_RONDE',     19);

// Type du tour
// En ce moment, pour les interclubs, rund type vaut
// 15 pour une poule
// 16 pour une poule A/R
// 17 pour un Ko
// A faire evoluer
define('OROUND_TYPEIC_GROUP',  15);
define('OROUND_TYPEIC_AR'	,  16);
define('OROUND_TYPEIC_KO',     17);

// Les types définitif pour les tours (deja utilise pour les individuels)
define('OROUND_TYPE_GROUP',    280);
define('OROUND_TYPE_QUALIF'	,  281);
define('OROUND_TYPE_MAINDRAW', 282);
define('OROUND_TYPE_THIRD',    283);
define('OROUND_TYPE_CONSOL',   284);
define('OROUND_TYPE_PLATEAU',  285);
define('OROUND_TYPE_RONDE',    286);
define('OROUND_TYPE_AR',       287);
define('OROUND_TYPE_PROGRES',  288);

// Mode de calcul du classement d'un groupe de type poule
define('OGROUP_RANK_CG'	,      140);
define('OGROUP_RANK_RP'	,      141);



?>
