<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// Statut des equipes
define('OTEAM_STATUT_CLUB',    450); // inscrite par le club, attente validation organisateur
define('OTEAM_STATUT_VALIDE',  451); // Inscrite par le club, validé organisation
define('OTEAM_STATUT_ORGA',    459); // inscrite par l'orgnisateur

?>
