<?php
/*****************************************************************************
 !   $Id$
 ******************************************************************************/
// valeur des commandes
//ne pas utiliser. remplacer par getconfigvalue('???', 'cost');
define('OTICKNET_VALUE_TOURNAMENT',    3000);
define('OTICKNET_VALUE_IC',            7000);
define('OTICKNET_VALUE_PROMOTION',      100);
define('OTICKNET_VALUE_SMS',             30);
define('OTICKNET_VALUE_STATS',         3000);
define('OTICKNET_VALUE_INLINE',       10000);
define('OTICKNET_VALUE_TEAM',           200);
define('OTICKNET_VALUE_CAPTAIN',        100);


// Type des commandes
define('OTICKNET_TYPE_NONE',  430);
define('OTICKNET_TYPE_TBD1',  431);
define('OTICKNET_TYPE_TBD2',  432);
define('OTICKNET_TYPE_TBD3',  433);
define('OTICKNET_TYPE_TBD4',  434);
define('OTICKNET_TYPE_TBD5',  435);

?>
