<?php
/************************************
 !   $Id$
 ************************************/
// Resultat d'une rencontre
define("OTIE_RESULT_WIN",     100);
define("OTIE_RESULT_LOOSE",   101);
define("OTIE_RESULT_EQUAL",   102);
define("OTIE_RESULT_NOTPLAY", 103);
define("OTIE_RESULT_LOOSEWO", 104);
define("OTIE_RESULT_WINWO",   105);
define("OTIE_RESULT_STEP",    106);
define("OTIE_RESULT_EQUAL_MINUS", 107);
define("OTIE_RESULT_EQUAL_PLUS",  108);

// Comment departager deux equipes a egalites
define("OTIE_CALC_RANK",   140); // Classement
define("OTIE_CALC_RESULT", 141); // Resultat du match entre les deux
define("OTIE_CALC_EQUAL",  142); // Egalite autorisé

// Position des equipes dans une rencontre
define('OTIE_TEAM_RECEIVER', 130);
define('OTIE_TEAM_VISITOR',  131);

?>
