<?php
/*****************************************************************************
!   Module     : Registrations
!   File       : $Source: /cvsroot/aotb/badnet/src/regi/regi.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.12 $
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/05/06 07:59:33 $
******************************************************************************/

// Actions Administrateur uniquement
define("LINE_TEAMS",       WBS_ACT_LINE);
define("LINE_TEAM",        WBS_ACT_LINE+1);
define("LINE_VALID",       WBS_ACT_LINE+2);
define("LINE_DEL_MESSAGE", WBS_ACT_LINE+3);


?>
