<?php 
require_once 'Object/Ocommand.inc'; 
define('LABEL_420','Libellé DE'); 
define('LABEL_421','Libellé DE'); 
define('LABEL_422','Libellé DE'); 
define('LABEL_423','Libellé DE'); 
define('LABEL_424','Libellé DE'); 
define('LABEL_425','Libellé DE'); 
define('LABEL_426','Libellé DE'); 
define('LABEL_427','Libellé DE'); 
define('LABEL_180','Libellé DE'); 
define('LABEL_181','Libellé DE'); 
define('LABEL_182','Libellé DE'); 
define('LABEL_183','Libellé DE'); 
define('LABEL_184','Libellé DE'); 
define('LABEL_185','Libellé DE'); 
define('LABEL_186','Libellé DE'); 
?>