<?php 
require_once 'Object/Ogroup.inc'; 
define('LABEL_15','Poule'); 
define('LABEL_16','Poule aller/retour'); 
define('LABEL_17','Départ en ligne'); 
define('LABEL_18','Départ en ligne + plateau'); 
define('LABEL_19','Ronde suisse'); 
define('LABEL_286','Ronde suisse'); 
define('LABEL_140','Classement général'); 
define('LABEL_141','Résultat particulier'); 
define('LABEL_142','Egalité autorisée'); 
define('LABEL_280','Poule'); 
define('LABEL_281','Qualification'); 
define('LABEL_282','Tableau principal'); 
define('LABEL_283','Troisième place'); 
define('LABEL_284','Consolante'); 
define('LABEL_285','Plateau'); 
?>