<?php 
require_once 'Object/Oplayer.inc'; 
define('LABEL_301','U11'); 
define('LABEL_302','U13'); 
define('LABEL_303','U15'); 
define('LABEL_304','U17'); 
define('LABEL_305','U19'); 
define('LABEL_306','Senior'); 
define('LABEL_307','+35'); 
define('LABEL_308','+40'); 
define('LABEL_309','+45'); 
define('LABEL_1','Men's single'); 
define('LABEL_2','Women's single'); 
define('LABEL_3','Men's double'); 
define('LABEL_4','Women's double'); 
define('LABEL_5','Mixed'); 
define('SMA_LABEL_1','MS'); 
define('SMA_LABEL_2','WS'); 
define('SMA_LABEL_3','MD'); 
define('SMA_LABEL_4','WD'); 
define('SMA_LABEL_5','MX'); 
define('LABEL_350','None'); 
define('LABEL_351','Single'); 
define('LABEL_352','Double'); 
define('LABEL_353','Vétéran autorisé'); 
define('LABEL_354','Exceptionnel'); 
define('LABEL_355','Poussin'); 
?>