<?php
/*****************************************************************************
!   Module     : Purchase
!   File       : $Source: /cvsroot/aotb/badnet/src/purchase/purchase.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.3 $
!   Revised by : $Author: cage $
!   Date       : $Date: 2006/04/27 23:10:58 $
******************************************************************************/
define("PURCHASE_SEL_ITEM",         WBS_ACT_PURCHASE+1);
define("PURCHASE_NEW_CREDIT",       WBS_ACT_PURCHASE+2);
define("PURCHASE_UPDATE_CREDIT",    WBS_ACT_PURCHASE+3);
define("PURCHASE_ADD_CREDIT",       WBS_ACT_PURCHASE+4);
define("PURCHASE_CONFIRM",          WBS_ACT_PURCHASE+5);
define("PURCHASE_DEL_CREDIT",       WBS_ACT_PURCHASE+6);
define("PURCHASE_REGI_SELECT",      WBS_ACT_PURCHASE+7);
define("PURCHASE_ITEM_SELECT",      WBS_ACT_PURCHASE+8);
define("PURCHASE_COMMAND_VALID",    WBS_ACT_PURCHASE+9);
define("PURCHASE_COMMAND_PAYEDM",   WBS_ACT_PURCHASE+10);
define("PURCHASE_COMMAND_PAYEDC",   WBS_ACT_PURCHASE+11);
define("PURCHASE_ITEM_CANCEL",      WBS_ACT_PURCHASE+12);
define("PURCHASE_REGI_BARCOD",      WBS_ACT_PURCHASE+13);
define("PURCHASE_ITEM_BARCOD",      WBS_ACT_PURCHASE+14);
define("PURCHASE_ITEMS_GRID",       WBS_ACT_PURCHASE+15);
define("PURCHASE_ITEMS_UPDATE",     WBS_ACT_PURCHASE+16);
define("PURCHASE_SOLDE_CHECK",      WBS_ACT_PURCHASE+17);
define("PURCHASE_SOLDE_MONEY",      WBS_ACT_PURCHASE+18);

define("PURCHASE_HOTEL",     WBS_ACT_PURCHASE+19);
define("PURCHASE_FEES",      WBS_ACT_PURCHASE+20);
define("PURCHASE_RESERVE",   WBS_ACT_PURCHASE+21);
define("PURCHASE_UPDATE_ROOM",   WBS_ACT_PURCHASE+22);
define("PURCHASE_SOLDE_CLUB",    WBS_ACT_PURCHASE+23);
define("PURCHASE_SOLDE_MEMBER",     WBS_ACT_PURCHASE+24);
define("PURCHASE_EDIT_ROOM",        WBS_ACT_PURCHASE+25);
define("PURCHASE_UPDATE_ROOMNUM",   WBS_ACT_PURCHASE+26);
define("PURCHASE_SEL_ROOM",         WBS_ACT_PURCHASE+27);

?>
