<?php 
define('LOC_MSG_RESULT_CONFIRMED','Les résultats de la rencontre sont confirmés. Seul l\'organisateur de la compétition peux les modifier.'); 
define('LOC_MSG_RESULT_SENDED','Les résultats de la rencontre sont enregistrés. Un email de confirmation a été envoyé au capitaine adverse pour qu\'il donne son accord.'); 
define('LOC_LABEL_GENDER','Gender'); 
define('LOC_TITLE_EMAIL_PLAYERS','Contact all players'); 
define('LOC_TITLE_EMAIL_PLAYER','Contact a player'); 
define('LOC_MSG_EMAIL_ONLY','You can modify the email only'); 
define('LOC_TITLE_EDIT_PLAYER','Modification d\'un joueur'); 
define('LOC_MSG_VALIDATION','Les résultats de cette rencontre ont été saisis par le capitaine de l\'équipe adverse. Vous devez soit les accepter de façon définitives et ils ne seront plus modifiables, soit les modifier. Dans le second cas, un email est envoyé au capitaine adverse pour qu\'il les valide.'); 
define('LOC_MSG_PLAYER_TEAM','Ce joueur est déjà inscrit dans une autre équipe. Vous ne pouvez pas l\'intégrer à celle ci.'); 
define('LOC_MSG_ADD_PLAYER','Saisissez le nom ou le numéro de licence puis choisissez le joueur dans la liste. Utilisez le caractère % pour remplacer un ou plusieurs caractères. Seul l\'email du joueur choisi est modifibale.'); 
define('LOC_LABEL_EMAIL','Email'); 
define('LOC_MSG_CONFIRM_DEL_PLAYER','Vous allez supprimer le joueur de votre équipe. Vous pourrez le rajouter ultérieurement si nécessaire.'); 
define('LOC_TITLE_ADD_PLAYER','Add a player'); 
define('LOC_LABEL_ONE_MORE','Add another player'); 
define('LOC_LABEL_LEVEL','Classement'); 
define('LOC_MSG_DELAY','L\'ajout de joueur est bloqué %bndays% jours avant la prochaine rencontre et tant que toutes les rencontres passées ne sont pas validés.'); 
define('LOC_MSG_MULTIASSO_NO','Seul les joueurs du club sont autorisés à jouer pour cette équipe.'); 
define('LOC_MSG_MULTIASSO_YES','Les joueurs d\'un autre club sont autorisés à jouer pour cette équipe.'); 
define('LOC_MSG_MULTITEAM_YES','Un joueur est autorisé à jouer dans plusieurs équipes de cette compétition.'); 
define('LOC_MSG_MULTITEAM_NO','Un joueur ne peut jouer que dans une seule équipe.'); 
define('LOC_MSG_LICENSE_ONLY','Seul les joueurs licenciés peuvent participer à cette compétition.'); 
define('LOC_MSG_NEVER','Les gestionnaires de la compétition ont bloqué l\'ajout de joueur. Vous ne pouvez pas rajouter de joueur à votre équipe.'); 
define('LOC_LABEL_RANK','Ranking'); 
define('LOC_LABEL_NEW_PLAYER','Register then add a new player'); 
define('LOC_LABEL_TEAM','Select team'); 
define('LOC_TITLE_RESULTS','Ranking and results of the group'); 
define('LOC_LABEL_FROM','From'); 
define('LOC_TITLE_EMAIL_MANAGER','Contact organizer'); 
define('LOC_TITLE_EMAIL','Contact other team'); 
define('LOC_MSG_TIE_CONFIRM','Bonjour,
      
le capitaine de l\'équipe que vous avez affrontée vient 
de saisir les résultats de la rencontre.

----------------------------------------
%bnresult%
----------------------------------------

Il a ce message pour vous.

----------------------------------------
%bncomment%
----------------------------------------

Si vous êtes d\'accord avec les résultats saisis,
utiliser le lien ci-dessous pour les valider de
façon définitive.

========================================
Confirmer les résultats
%bnconfirm%
========================================

Si les résultats proposés ne vous semblent pas correct
ou sont incomplets, utiliser le lien suivant pour les 
modifier et proposer vos modifications au capitaine de 
l\'autre équipe.
========================================
Modifier les résultats
%bnrefuse%
========================================
'); 
define('LOC_P_INFO_GROUPS','Here are the players of other teams of your group.'); 
define('LOC_BTN_ACCEPT','Accept'); 
define('LOC_P_TIE_CONFIRM','The results of the matches will be send to captain of other team for confirmation.'); 
define('LOC_P_TIE','Register the results of the matches.'); 
define('LOC_COLUMN_ASSO','Club'); 
define('LOC_LABEL_COMMENT','Comment'); 
define('LOC_LABEL_GROUP','Groupe'); 
define('LOC_LABEL_ASSO','Club'); 
define('LOC_LABEL_VALIDATE','Results confirmed by %bnuser% on %bndate%'); 
define('LOC_LABEL_REGISTERED','Results registered by %bnuser% on %bndate%'); 
define('LOC_TITLE_TIE','Results of a tie'); 
define('LOC_TITLE_REGIS_PLAYERS','Players in teams'); 
define('LOC_LGD_OTHER_TEAM','Registered in other team'); 
define('LOC_LGD_TEAM','Registered in your team'); 
define('LOC_TITLE_SPORT','Sport'); 
define('LOC_TITLE_CIVIL','Civil'); 
define('LOC_LABEL_NUMCATAGE','Number'); 
define('LOC_LABEL_CATAGE','Catégorie'); 
define('LOC_LABEL_SURCLASSE','Surclassment'); 
define('LOC_LABEL_MIXED','Level mixed'); 
define('LOC_LABEL_DOUBLE','Level double'); 
define('LOC_LABEL_SINGLE','Level'); 
define('LOC_LABEL_WOMAN','Woman'); 
define('LOC_LABEL_MAN','Man'); 
define('LOC_LABEL_LICENSE','License'); 
define('LOC_LABEL_BORN','Born'); 
define('LOC_LABEL_FIRSTNAME','First name'); 
define('LOC_LABEL_FAMNAME','Family name'); 
define('LOC_TITLE_PLAYER','New player creation'); 
define('LOC_LINK_BACK_CAPTAIN','Back to the man page'); 
define('LOC_LINK_CONSULT_RESULTS','Consult results and ranking of the group'); 
define('LOC_LINK_CONSULT_PLAYERS','Consult players of the teams'); 
define('LOC_TITLE_TEAM_PLAYERS','Players of my team'); 
define('LOC_LINK_ADD_PLAYER','Players of my team'); 
define('LOC_MSG_CAPTAIN_TIES','Register'); 
define('LOC_MSG_PLAYERS_CHOICE','Register'); 
define('LOC_BTN_NEW','New player'); 
define('LOC_TITLE_PLAYERS','Availabe players'); 
define('LOC_TITLE_TIES','Ties of your team'); 
define('LOC_COLUMN_PLACE','Place'); 
define('LOC_COLUMN_VERSUS','Adversaire'); 
define('LOC_COLUMN_RESULT','Result'); 
define('LOC_COLUMN_SCORE','Score'); 
define('LOC_COLUMN_RANK','Ranking'); 
define('LOC_COLUMN_SURCLASSE','Surclassement'); 
define('LOC_COLUMN_CATAGE','Catégorie'); 
define('LOC_COLUMN_LEVEL','Ranking'); 
define('LOC_COLUMN_LICENSE','License'); 
define('LOC_COLUMN_FIRSTNAME','First name'); 
define('LOC_COLUMN_FAMNAME','Family name'); 
define('LOC_COLUMN_GENDER','Gender'); 
define('LOC_CRIT_GENDER','Limitation'); 
define('LOC_LABEL_SEARCH','Name or license'); 
define('LOC_P_INFO_TEAM','you are the captain of this team'); 
define('LOC_P_INFO_CAPTAIN','Use the link below to manage your team'); 
?>