<?php
/*****************************************************************************
!   Module     : items
!   File       : $Source: /cvsroot/aotb/badnet/src/items/items.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.3 $
!   Author     : PMM
!   Revised by : $Author: cage $
!   Date       : $Date: 2006/04/27 23:10:58 $
!******************************************************************************/

define("ITEM_MAIN",       WBS_ACT_ITEMS+1);
define("ITEM_UPDATE_A",   WBS_ACT_ITEMS+2);
define("ITEM_FUSION_A",   WBS_ACT_ITEMS+3);
define("ITEM_EDIT_A",     WBS_ACT_ITEMS+4);
define("ITEM_SELECTED",   WBS_ACT_ITEMS+5);
define("ITEM_LIST_PDF",   WBS_ACT_ITEMS+6);
define("ITEM_STATS",      WBS_ACT_ITEMS+7);
define("ITEM_COMMANDS",   WBS_ACT_ITEMS+8);
define("ITEM_SPECIALCODE_PDF",  WBS_ACT_ITEMS+9);

define("ITEM_HOTELS",        WBS_ACT_ITEMS+10);
define("ITEM_OTHERS",        WBS_ACT_ITEMS+11);
define("ITEM_NEW_HOTEL",     WBS_ACT_ITEMS+12);
define("ITEM_EDIT_HOTEL",    WBS_ACT_ITEMS+13);
define("ITEM_UPDATE_HOTEL",  WBS_ACT_ITEMS+14);
define("ITEM_HOTEL",         WBS_ACT_ITEMS+15);

?>