<?php
include_once "Badnet/Badnet.inc";

$indice = BADNET_TEAM;
define('BTEAM_PAGE_TEAMS',      $indice++);
define('BTEAM_FILL_TEAMS',      $indice++);
define('BTEAM_PAGE_ADD_TEAM',   $indice++);
define('BTEAM_ADD_TEAM',        $indice++);
define('BTEAM_SEARCH_ASSOC',    $indice++);
define('BTEAM_PAGE_DEL_TEAM',   $indice++);
define('BTEAM_DEL_TEAM',        $indice++);
define('BTEAM_PAGE_TEAM',       $indice++);
define('BTEAM_UPDATE_TEAM',     $indice++);
define('BTEAM_PAGE_PLAYERS',    $indice++);
define('BTEAM_FILL_PLAYERS',    $indice++);
define('BTEAM_PAGE_VCARD',          $indice++);
define('BTEAM_PDF_VCARD',           $indice++);
define('BTEAM_PAGE_EMAIL_CAPTAIN',  $indice++);
define('BTEAM_SEND_EMAIL_CAPTAIN',  $indice++);
define('BTEAM_PAGE_EMAIL_CAPTAINS', $indice++);
define('BTEAM_SEND_EMAIL_CAPTAINS', $indice++);
define('BTEAM_EMAIL_SENDED',        $indice++);

?>