<?php 
require_once 'Object/Ocommand.inc'; 
define('LABEL_420','Unknow'); 
define('LABEL_421','Adhésion'); 
define('LABEL_422','Tournament'); 
define('LABEL_423','Circuit'); 
define('LABEL_424','Inscription'); 
define('LABEL_425','Day'); 
define('LABEL_426','Formation'); 
define('LABEL_427','Buy ticknets'); 
define('LABEL_180','Unknow'); 
define('LABEL_181','Credit'); 
define('LABEL_182','Money'); 
define('LABEL_183','Chèque'); 
define('LABEL_184','Credit card'); 
define('LABEL_185','In line'); 
define('LABEL_186','Virement'); 
?>