<?php 
require_once 'Object/Omatch.inc'; 
define('LABEL_110','Single'); 
define('LABEL_111','Double'); 
define('LABEL_112','Mixed'); 
define('LABEL_261','Finale'); 
define('LABEL_262','Demi Finale'); 
define('LABEL_263','Quart de Finale'); 
define('LABEL_264','Huitième'); 
define('LABEL_265','Seizième'); 
define('LABEL_266','32ème'); 
define('LABEL_267','64ème'); 
define('LABEL_268','Premier tour'); 
define('LABEL_269','Second tour'); 
define('LABEL_270','Troisième tour'); 
define('SMA_LABEL_261','Fin'); 
define('SMA_LABEL_262','1/2'); 
define('SMA_LABEL_263','1/4'); 
define('SMA_LABEL_264','1/8'); 
define('SMA_LABEL_265','1/16'); 
define('SMA_LABEL_266','1/32'); 
define('SMA_LABEL_267','1/64'); 
define('SMA_LABEL_268','Tr 1'); 
define('SMA_LABEL_269','Tr 2'); 
define('SMA_LABEL_270','Tr 3'); 
?>