<?php 
define('LOC_P_ACCOUNT_INFOS','Saisissez votre mot de passe et le code de sécurité pour terminer la création de votre compte'); 
define('LOC_MSG_ACCOUNT_EXIST','Un compte existe déjà pour ce joueur. Si vous pensez être victime d\'une usurpation, contacter le modérateur à partir de la page d\'accueil.'); 
define('LOC_MSG_UNKNOW_PLAYER','Numéro de licence inconnu dans la base féférale.'); 
define('LOC_MSG_BAD_BORN','La date de naissance de naissance ne correspond pas à celle enregistrée dans la base de données fédérale.'); 
define('LOC_LABEL_BORN','Date de naissance'); 
define('LOC_LABEL_LICENSE','License number'); 
define('LOC_TITLE_ACCOUNT_LICENSE','License number'); 
define('LOC_P_ACCOUNT_CLUB','Vous avez choisi la création d\'un compte Association. Vous pourrez l\'utiliser pour créer et gérer les compétitions que vous organisez, gérer les inscriptions de vos joueurs a toutes les compétitions déclarées. 
      Il ne pourra pas être converti en compte simple ou Joueur.'); 
define('LOC_TITLE_ACCOUNT_CLUB','Création d\'un compte Association'); 
define('LOC_P_ACCOUNT_PLAYER','Vous avez choisi la création d\'un compte Joueur. Vous pourrez l\'utiliser pour consulter vos résultats et vous inscrire en ligne aux compétitions déclarées. Il ne pourra pas être converti en compte simple ou Association.
      Saisissez votre numéro de licence et votre date de naissance. Ces informations doivent être conformes à celles enregistrées dans la base de données fédérale.'); 
define('LOC_TITLE_ACCOUNT_PLAYER','Création d\'un compte joueur'); 
define('LOC_P_ACCOUNT_OTHER','Vous avez choisi la création d\'un compte simple. Vous pourrez l\'utiliser pour devenir capitaine d\une équipe interclubs, ou gestionnaire d\'une compétition. 
      Il pourra être converti en compte Association en le reliant à l\'association de votre choix.'); 
define('LOC_TITLE_ACCOUNT_OTHER','Création d\'un compte simple'); 
define('LOC_LABEL_OTHER_DESC','Utiliser ce type de compte si vous devez être capitaine d\'équipe interclubs ou gestionnaire d\'une ou plusieurs compétitions'); 
define('LOC_LABEL_OTHER','Compte simple.'); 
define('LOC_LABEL_CLUB_DESC','Ce type de compte est relié à une association affiliée à la fédération. Il permet de créer des compétitions, inscrire des équipes aux interclubs, gérer les joueurs de l\'association...'); 
define('LOC_LABEL_CLUB','Compte association.'); 
define('LOC_LABEL_PLAYER','Compte joueur.'); 
define('LOC_LABEL_PLAYER_DESC','Le compte Joueur est un compte personnel. Seul les joueurs licenciés peuvent utiliser ce type de compte. L\'identifiant est le numéro de licence. Ce compte permet de consulter son classement et permettra d\'utiliser le module d\'inscription en ligne aux tournois.'); 
define('LOC_P_ACCOUNT','Choisissez le type de compte en fonction de vos besoins. Le création de compte est gratuite; N\'hésitez pas à créer plusieurs compte pour séparer les fonctions que vous pouvez cumuler. Si vous êtes à la fois Juge-arbitre, responsable de d\'association et capitaine d\'équipe interclubs, créez un compte pour chaque fonction.'); 
define('LOC_TITLE_ACCOUNT2','Choix du type de compte'); 
define('LOC_TITLE_ACCOUNT_TYPE','Type de compte'); 
define('LOC_MSG_ERR_EMAIL_ACCOUNT','Libelle DE'); 
define('LOC_LNK_BACK_HOME','Zurück zur Startseite'); 
define('LOC_MSG_ERRORLOGIN','Benutzernamen oder Passwort falsch. Wenn Sie Ihre Anmeldedaten vergessen haben, benutzen Sie die Funktion "Passwort vergessen".'); 
define('LOC_TITLE_BADLOGIN','Verbindung gescheitert'); 
define('LOC_TITLE_LOGIN','Verbindung'); 
define('LOC_MSG_SEND_PWD','Ein neues Passwort wurde Ihnen zugesand'); 
define('LOC_MSG_ERR_EMAIL','Fehler. Bitte nochmal versuchen.'); 
define('LOC_MSG_BAD_EMAIL','E-Mail unbekannt'); 
define('LOC_MSG_ACCOUNT_VALID','Libelle DE'); 
define('LOC_MSG_ACCOUNT_CONFIRM','Libelle DE'); 
define('LOC_EMAIL_BODY','Hallo,
eine Passwort Anfrage wurde soeben für Ihr BadNetkonto beantragt.

Hier sind Ihre neuen Verbindungsangaben.

-------------------------------
Benutzername : %bnid%
Passwort : %bnpwd%
-------------------------------
'); 
define('LOC_EMAIL_OBJECT_PWD','Passwort'); 
define('LOC_P_ASK_PWD','Geben Sie Ihre E-Mail Adresse an, ein neues Passwort wird Ihnen dann zugesandt.'); 
define('LOC_TITLE_NEW_PASSWORD','Passwortabfrage'); 
define('LOC_MSG_LOGIN_NOT_BLANK','Keine Leerzeichen im Benutzernamen bitte.'); 
define('LOC_MSG_LOGIN_ALREADY_USED','Benutzername schon besetzt. Suchen Sie sich einen anderen aus.'); 
define('LOC_MSG_BAD_DIFFPWD','Beide Passwörter müssen gleich sein.'); 
define('LOC_MSG_LOGIN_NOT_PWD','Benutzername und Passwort müssen aus Sicherheitsgründen verschieden sein!'); 
define('LOC_MSG_EMAIL_ALREADY_USED','Libellé DE'); 
define('LOC_MSG_BAD_CODE','Sicherheitsabfrage falsch.'); 
define('LOC_MSG_AQUIT_DEMANDE','Iihre Registrierung wurde gespeichert. Sie erhalten eine E-Mail mit Anweisung, um Ihre Anmeldung zu bestätigen.'); 
define('LOC_BODY_DEMANDE','Hallo,
eine Anfrage für ein BadNetkonto wurde soeben getätigt.
Sind Sie nicht Autor dieser Anfrage ignorieren Sie einfach diese Mail.
Andernfalls klicken sie auf den folgenden Link:

========================================
Confirmer votre compte
%bnconfirm%
========================================

Mit sportlichen Grüßen.

Das BadNet-Entwickler Team");'); 
define('LOC_OBJECT_DEMANDE','Neues konto erstellen'); 
define('LOC_P_EMAIL','Sie erhalten gleich eine E-Mail mit Anweisungen'); 
define('LOC_P_CAPTCHA','Um zu überprüfen, dass Sie aus Fleisch und Blut bestehen geben Sie bitte die Anzahl der BIldchen an.'); 
define('LOC_P_PSEUDO','Der Name wird in der späteren Korrespondenz benutzt, der Benutzername erscheint auf der öffentlich auf der Homepage.'); 
define('LOC_LABEL_CAPTCHA','Anzahl der Bilder'); 
define('LOC_LABEL_CONFIRM','Passwort bestätigen'); 
define('LOC_TITLE_CAPTCHA','Sicherheit'); 
define('LOC_TITLE_SAISIE','Informationsangaben'); 
define('LOC_TITLE_NEW_ACCOUNT','Neuer Benutzerzugang'); 
?>