<?php 
define('LOC_LABEL_OLD_PASSWORD','Aktuelles Passwort'); 
define('LOC_LABEL_NEW_PASSWORD','Neues Passwort'); 
define('LOC_LABEL_CONFIRM_PASSWORD','Bestätigung'); 
define('LOC_TITLE_PASSWORD','Passwort'); 
define('LOC_LNK_CHANGE_PWD','Passwort ändern'); 
define('LOC_TITLE_CONTACT','Adresse'); 
define('LOC_P_CIVILITE','Libellé DE'); 
define('LOC_P_ASSOCIATION','Libellé DE'); 
define('LOC_MSG_REGISTERED','Libellé DE'); 
define('LOC_MSG_ALREADY_MANAGE','Libellé DE'); 
define('LOC_MSG_NEED_PHONE','Libellé DE'); 
?>