<?php 
require_once 'Object/Ocommand.inc'; 
define('LABEL_420','Inconnu'); 
define('LABEL_421','Adhésion'); 
define('LABEL_422','Tournoi'); 
define('LABEL_423','Circuit'); 
define('LABEL_424','Inscription'); 
define('LABEL_425','Journée'); 
define('LABEL_426','Formation'); 
define('LABEL_427','Achat ticknets'); 
define('LABEL_180','Inconnu'); 
define('LABEL_181','Crédit'); 
define('LABEL_182','Espèce'); 
define('LABEL_183','Chèque'); 
define('LABEL_184','Carte de crédit'); 
define('LABEL_185','En ligne'); 
define('LABEL_186','Virement'); 
?>