<?php
/*****************************************************************************
!   Module    : AddressBooks
!   Version   : v0.0.1
!   Author    : G.CANTEGRIL
!   Co-author :
!   Mailto    : cage@aotb.org
!   Date      : 01-12-2003
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************
!   Greetings & thanks to:
!      - 
******************************************************************************
!   History:
!      v0.0.1        creation
******************************************************************************
!   Todo:
!      
******************************************************************************/


define("BOOKS_CREATE_A",         WBS_ACT_BOOKS+1);
define("BOOKS_NEWMEMBER_A",      WBS_ACT_BOOKS+2);
define("BOOKS_NEWASSOC_A",       WBS_ACT_BOOKS+3);
define("BOOKS_ADDMEMBER_A",      WBS_ACT_BOOKS+4);
define("BOOKS_ADDASSOC_A",       WBS_ACT_BOOKS+5);
define("BOOKS_NEWMBERCTAC_A",    WBS_ACT_BOOKS+6);
define("BOOKS_NEWASSOCCTAC_A",   WBS_ACT_BOOKS+7);

define("BOOKS_ADDCONTACT_A",     WBS_ACT_BOOKS+8);

define("BOOKS_EDITCONTACT_A",    WBS_ACT_BOOKS+9);
define("BOOKS_UPDTCONTACT_A",    WBS_ACT_BOOKS+10);
define("BOOKS_DELMBERCONTACT_A", WBS_ACT_BOOKS+11);
define("BOOKS_REGMBERCONTACT_A", WBS_ACT_BOOKS+12);
define("BOOKS_DELASSOCONTACT_A", WBS_ACT_BOOKS+13);
define("BOOKS_REGASSOCONTACT_A", WBS_ACT_BOOKS+14);
define("BOOKS_REMCONTACT_A",     WBS_ACT_BOOKS+15);

define("BOOKS_PRIVATECTAC_A",    WBS_ACT_BOOKS+16);
define("BOOKS_HIDDENCTAC_A",     WBS_ACT_BOOKS+17);
define("BOOKS_PUBLISHEDCTAC_A",  WBS_ACT_BOOKS+18);

define("BOOKS_MAIL_V",           WBS_ACT_BOOKS+19);
define("BOOKS_SENDMAIL_V",       WBS_ACT_BOOKS+20);

define("BOOKS_RIGHT_A",          WBS_ACT_BOOKS+21);
define("BOOKS_UPDATE_RIGHT_A",   WBS_ACT_BOOKS+22);

define("BOOKS_SELASSOCONTACT_A",   WBS_ACT_BOOKS+23);
define("BOOKS_VALIDASSOCONTACT_A", WBS_ACT_BOOKS+24);
define("BOOKS_SELECT_FILE_A",   WBS_ACT_BOOKS+25);
define("BOOKS_IMPORT_FILE_A",   WBS_ACT_BOOKS+26);
define("BOOKS_READ_FILE_A",     WBS_ACT_BOOKS+27);


?>