<?php
/*****************************************************************************
!   Module     : Ajaj
!   File       : $Source: /cvsroot/aotb/badnet/src/ajaj/ajaj.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.5 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/18 07:51:18 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

/**************************************
*  These are the constants for globals
*  actions and module actions
***************************************/
define("AJAJ_REGI1",           KID_USER+1);
define("AJAJ_REGI2",           KID_USER+2);

define("AJAJ_MAINT_SELECT_ASSO",    KID_USER+10);
define("AJAJ_MAINT_MERGE_ASSO",     KID_USER+11);
define("AJAJ_MAINT_UPDATE_ASSO",    KID_USER+12);
define("AJAJ_MAINT_SELECT_MEMBER",  KID_USER+13);
define("AJAJ_MAINT_MERGE_MEMBER",   KID_USER+14);
define("AJAJ_MAINT_UPDATE_MEMBER",  KID_USER+15);
define("AJAJ_MAINT_LIST_MEMBER",    KID_USER+16);

define("AJAJ_DRAW_SAVEROUND",       KID_USER+20);

?>
