<?php
/*****************************************************************************
!   Module     : Registrations
!   File       : $Source: /cvsroot/aotb/badnet/src/regi/regi.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.12 $
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/05/06 07:59:33 $
******************************************************************************/

// Actions Administrateur uniquement
define("REGI_TEAM",        WBS_ACT_REGI+35);
define("REGI_PLAYER",      WBS_ACT_REGI+36);
define("REGI_OFFICIAL",    WBS_ACT_REGI+37);

define("REGI_SEARCH",         WBS_ACT_REGI+1);
define("REGI_SEARCH_TEAM",    WBS_ACT_REGI+2);
define("REGI_FIND",           WBS_ACT_REGI+3);

define("REGI_GET_FFBA",        WBS_ACT_REGI+4);
define("REGI_GET_FFBA_SEPT",   WBS_ACT_REGI+5);
define("REGI_UPDATE_RANK",     WBS_ACT_REGI+6);

define("REGI_NEW_PLAYER",      WBS_ACT_REGI+10);
define("REGI_NEW_OFFICIAL",    WBS_ACT_REGI+11);
define("REGI_NEW_OTHER",       WBS_ACT_REGI+12);


define("REGI_NEW_OFFICIAL_FROM_TEAM", WBS_ACT_REGI+25);
define("REGI_NEW_OTHER_FROM_TEAM",    WBS_ACT_REGI+26);
define("REGI_ALL",                    WBS_ACT_REGI+28);

define("REGI_CREDITS",                WBS_ACT_REGI+30);
define("REGI_PDF_PLAYERS",            WBS_ACT_REGI+31);

define("REGI_PLAYERS_ABSENT",         WBS_ACT_REGI+32);
define("REGI_PLAYERS_PRESENT",        WBS_ACT_REGI+33);

define("REGI_PRINT",        WBS_ACT_REGI+34);

define("REGI_SELECT_FEES",            WBS_ACT_REGI+41);
define("REGI_REGI_FEES",              WBS_ACT_REGI+42);

?>
