<?php
/*****************************************************************************
!   $Id$
******************************************************************************/
define('ACCUEIL_MAIN',         PROJECT_ACCUEIL | 0x000000);
define('ACCUEIL_SQUASH_IDF',   PROJECT_ACCUEIL | 0x000100);
define('ACCUEIL_SQUASH_FFS',   PROJECT_ACCUEIL | 0x000200);
define('ACCUEIL_LIFB',         PROJECT_ACCUEIL | 0x000300);
define('ACCUEIL_SQUASH_NC',    PROJECT_ACCUEIL | 0x000400);
define('ACCUEIL_DISTRIB',      PROJECT_ACCUEIL | 0x000500);
define('ACCUEIL_END',          PROJECT_ACCUEIL | 0x000900);

?>
