<?php

include dirname(__FILE__)."/menu_V.inc";
//include dirname(__FILE__)."/t_asso.inc";

// Titre  du navigateur
$asso      = "Vereine";

// Menu
$itEntries     = "Anmeldungen";
$itItems       = "Artikel";
$itReservation = "Reservierungen";
$itCompetition = "Wettbewerbe";


// Titre des colonnes
$rowsPlayers1  = "Geschlecht";
$rowsPlayers2  = "Identität";
$rowsPlayers3  = "Nat Num";
$rowsPlayers4  = "Ibf Num";
$rowsPlayers5  = "Disziplinen";

$reservations1 = "Datum";
$reservations2 = "Artikel";
$reservations3 = "Identität";
$reservations4 = "Kosten";
$reservations5 = "Ermäßigung";
$reservations6 = "Bezahlt";
$reservations7 = "Saldo";

// Messages
$msgNoPlayers      = "Kein Spieler in diesem Turnier";
$msgNoReservations = "Keine Reservierung für dieses Turnier";
?>
