<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";


// Titre  du navigateur
$badges    = "Badges";

// Titres des fenetres
$tBadgeEdit = "Badge Layout";
$itModels    = "Modell";

// Menus 

// Label des zones
$badgeName = "Name des Modells";
$badgeWidth = "Breite in mm :";
$badgeHeight = "Hφhe in mm :";
$badgeBoder = "Rahmen (LTRB) :";
$badgeBoderSize = "Rand dicke :";
$badgeTopMargin = "Seitenrand hφhe :";
$badgeLeftMargin = "Seitenrand links :";
$badgeDeltaWidth = "Abstand breite :";
$badgeDeltaHeight = "Abstand hφhe :";

$eltbFont = "Schriftart :";
$eltbSize = "Grφίe :";
$eltbBold = "Fett :";
$eltbAlign = "Ausrichtung :";
$eltbTop  = "Haut :";
$eltbLeft = "Links :";
$eltbWidth  = "Breite :";
$eltbHeight = "Hφhe :";
$eltbBorder = "Rahmen :";
$eltbBorderSize = "Rahmen dicke :";
$eltbField  = "Felder :";
$eltbValue  = "Fixwerte :";
$eltbTextColor = "Textfarbe :";
$eltbFillColor = "Hintergrundfarbe :";
$eltbDrawColor = "Rahmenfarbe :";
// Titre de colonnes 
$badgeList1 = "Name";
$badgeList2 = "Breite (mm)";
$badgeList3 = "Hφhe (mm)";
$badgeList4 = "Rand";
$badgeList5 = "Dicke";
$badgeList6 = "Seitenrand Hφhe";
$badgeList7 = "Seitenrand links";
$badgeList8 = "Abstand breite";
$badgeList9 = "Abstand hφhe";

$badgeElts1 = "Schriftart";
$badgeElts2 = "Grφίe";
$badgeElts3 = "Fett";
$badgeElts4 = "Ausrichtung";
$badgeElts5 = "Oben";
$badgeElts6 = "Links";
$badgeElts7 = "Breite";
$badgeElts8 = "Hφhe";
$badgeElts9 = "Rahmen";
$badgeElts10 = "Dicke";
$badgeElts11 = "Feld";
$badgeElts12 = "Wert";
$badgeElts13 = "Textfarbe";
$badgeElts14 = "Texthintergrund";
$badgeElts15 = "Farbe";

$members1 = "Geschlecht";
$members2 = "Name";
$members3 = "Vorname";
$members4 = "Funktion";
$members5 = "NOC";
$members6 = "Mannschaft";
$members7 = "Logo";

// Messages d'erreur


// Label des boutons

?>