<?php

$tSubsList    = "Abonnements";
$msgSubscript = "Abonnieren Sie jetzt die Ergebnisse!";

$tManagerList = "Kontakte";
$helpManager  = "Nehmen zu einem Turnierverwalter Kontakt auf :";

$badnetLink  = "Direkter Link auf diese Seite :";
$msgDataBaseError = "Fehler beim Zugriff auf die Datenbank. Versuchen Sie es ernuet.";

$badnetVersion = "Page générée par ";

$lgdIncomplete  = "Unvollständig";
$lgdBusy        = "Besetzt";
$lgdRest        = "Pause";
$lgdReady       = "Ok";
$lgdLive        = "Läuft";
$lgdEnded       = "Fertig";
$lgdClosed      = "Fertig";
$lgdSend        = "Übermittelt";

$lgdMaindraw  = "M : Hauptfeld";
$lgdQualif    = "Q : Qualifikation";
$lgdReserve   = "R : Ersatz";
$lgdWdn       = "WDN : Walk-Over";
$lgdPtq       = "PTQ : Zur Quali befördert";
$lgdPtm       = "PTM : Ins Hauptfeld befördert";

?>