<?php
/* Chaines de caracteres generiques */

$badnet_lang = 'de';

$leftTitle = "Badminton Netware";
$rightTitle = "Verbindung";
$image = "Bilddatei:";

$wbs_notYet = "Funktion nicht verfügbar";

$lgdVisitor = "&nbsp;Gast";
$lgdUser    = "&nbsp;Benutzer";
$lgdGuest   = "&nbsp;Eingeladen";
$lgdFriend  = "&nbsp;Freund";
$lgdAssist  = "&nbsp;Assistent";
$lgdAdmin   = "&nbsp;Administrator";
$lgdManager = "&nbsp;Verwalter";

$lgdIncomplete  = "Unvollständig";
$lgdBusy        = "Besetzt";
$lgdRest        = "Pause";
$lgdReady       = "Ok";
$lgdLive        = "läuft";
$lgdEnded       = "beendet";
$lgdClosed      = "bestätigt";
$lgdSend        = "übermittelt";

$lgdConfident = "&nbsp;Vertraulich";
$lgdPrivate   = "&nbsp;Privat";
$lgdPublic    = "&nbsp;Öffentlich";
$lgdDelete   = "&nbsp;Gelöscht";

$lgdMaindraw  = "M: Hauptfeld";
$lgdQualif    = "Q: Qualifikation";
$lgdReserve   = "R: Warteliste";
$lgdWdn       = "WND: Walk-over";
$lgdPtq       = "PTQ: zur Quali befördert";
$lgdPfr       = "PFR: zur die Warteliste befördert";
$lgdPtm       = "PMD: ins Hauptfeld befördert";
$lgdPfq       = "PFQ: zur Quali befördert";
$lgdRtd       = "RTD: zurückgezogen";
$lgdQualify   = "Q: Qualifiziert";

$lgdPairs   = "Mehr Spieler/Paarungen als freie Plätze";
$lgdPlaces  = "Keine ausreichende Teilnehmerzahl";
$lgdCompose = "Zusammengesetzte Paarung";

$helpAdmin  = "Bei Problemen, Ideen oder Aufmunterung, nehmen Sie mit dem Administrator Kontakt auf.";

$username  = "Login:";
$password  = "Passwort:";

$tSubsList    = "Abonnement";
$msgSubscript = "Abonnieren Sie die Ergebnisse!";
$msgSubsList  = "Sie haben die Mannschaftsergebnisse abonniert";
$msgAskEvent = "Nehmen Sie mit dem Administrator Kontakt auf, um ein Turnier hinzuzufügen oder zusätzliche Berechtigungen zu erhalten.";
$msgNoAutorisation  = "Sie verfügen nicht über ausreichende Berechtigungen, um an diese Informationen zu gelangen.";
$msgDirectLink  = "Link zu dieser Seite:";

$msgUseImage  = "Klicken Sie auf das gewählten Bild oder laden Sie ein neues von Ihrem PC.";
$msgLimitedImage  = "ACHTUNG: nur die Bilder mit dem Format JPEG oder PNG werden richtig in PDF-Dateien dargestellt.";

$tManagerList = "Kontakte";
$helpManager  = "Nehmen Sie mit einem Turnier-Veranstalter Kontakt auf:";

$tEventInfos = "Praktisch";
$numAuto     = "Berechtigung";
$deadline    = "Anmeldeschluss";
$evntDraws   = "Auslosung";
$evntBegin   = "Erster Tag";
$evntFin     = "Letzter Tag";
$evntSite    = "Offizielle Homepage:";

$tAdminList   = "Kontakte";
$tUsersStat   = "Mitglieder";
$tEventsStat  = "Turniere";
$tVisitsStat  = "Besuche";
$nbUsers     = "Anzahl:";
$lastUser    = "Letzter:";
$nbAnonymousVisit  = "Anonym:";
$nbUsersVisit      = "Mitglieder:";
$nbAdminVisit      = "AdministratorInnen:";

$tEventStat   = "Statistiken";
$nbSubscribe  = "Abonnenten:";
$nbVisite     = "Besuche:";
$nbTeams      = "Mannschaften:";
$nbPlayers    = "Spieler:";
$nbMatchs     = "Matchs:";
$nbEvents     = "Gesamt:";

// Label des boutons
$btnRegisterAll  = "Alle speichern";
$btnRegister  = "Speichern";
$btnDelete    = "Entfernen";
$btnModify    = "Bearbeiten";
$btnCancel    = "Cancel";
$btnNew       = "Neu";
$btnClose     = "Schließen";
$btnSearch    = "Suchen";
$btnConfident = "Vertraulich";
$btnPrivate   = "Privat";
$btnPublic    = "Öffentlich";
$btnHelp      = "Hilfe";
$btnPlus      = "Mehr Infos";
$btnMoins     = "Maskieren";

?>