<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$draws    = "Tabellen";

// Sous menu
$itPairs     = "Spieler/Paarung";
$itGroup     = "Gruppenspiele";
$itQualif    = "Qualifikationen";
$itMainDraw  = "Finale-Tabelle";
$itPdf       = "Document Pdf";

// Titre des colonnes
$rowsPairs1  = "NAME Vorname";
$rowsPairs2  = "Klassifizierung";
$rowsPairs3  = "int. Rang";
$rowsPairs4  = "nat. Rang";
$rowsPairs5  = "Phase";
$rowsPairs6  = "Fortschritte";
$rowsPairs7  = "Mannschaft";

// Messages
$msgNoDraw       = "Keine deklarierte Tabelle.";
$msgNoPublic     = "Tabelle nicht verfügbar";
$msgNoPlayers    = "Es befindet sich kein Spieler in dieser Tabelle.";

?>
