<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/t_user.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$email = "Email verschicken";

// Titre  des fenetres
$femail = "Administrator kontaktieren";

// Titre  des cartouches
$tAdminList   = "Kontakte";
$tUsersStat   = "Mitglieder";
$tEventsStat  = "Turniere";
$tVisitsStat  = "Besuche";

// Label des zones
$from    = "Von :";
$fromEmail = "Ihre Adresse :";
$to      = "an :";
$subject = "Betreff:";
$message = "Nachricht :";
$Home    = "Zurück";

// Label des boutons
$btnMail    = "Abschicken";
$btnConnect = "Verbinden";
$btnNew     = "Neues Konto";
$btnLoose  = "Passwort oder Login vergessen ?";

// Label des message
$msgfrom       = "Bitte anmelden.";
$msgfromEmail  = "Email Adresse ist Pflicht.";
$msgsubject    = "Bitte ein Betreff angeben.";
$msgnoValidEmail = "Ihre Email Adresse ist ungültig.";
$msgmessage      = "Schreiben Sie eine Nachricht!!!";
$msgSend         = "Ihre Nachricht wurde erfolgreich versand.";


?>