<?php
include dirname(__FILE__)."/menu_V.inc";

// Boutons
$btnSubscribe   = "Abonnieren";
$btnUnsubscribe = "Abbestellen";
$btnInfo        = "Information";

// Titre  du navigateur
$events = "Event";

// Sous menus
$itPractical = "Praktisch";
$itSubscribe = "Abonnement";
$itContacts  = "Kontakte";
$itStats     = "Statistiken";

// Titres
$tCompetStat   = "Wettkampf";
$tVisitsStat   = "Besucher";

// Label des zones
$evntDate       = "Datum :";
$evntPlace      = "Ort :";
$evntOrganizer  = "Veranstalter :";
$evntDeadline   = "Anmeldeschluss :";
$evntDatedraw   = "Auslosung am :";

$nbTeams      = "Mannschaften :";
$nbPlayers    = "Spieler :";
$nbMatchs     = "Wettkämpfe :";
$nbVisite     = "Besuchen :";
$nbSubscribe  = "Abonieren :";

$email  = "Email";
$news   = "News empfangen";

// Colonnes
$rowsTeams1 = "Mannschaften";
$rowsTeams2 = "Pseudo";

// Messages
$msgSubscription = "Wählen Sie eine Mannschaft aus, geben Sie dann Ihre Emailadresse an und melden Sie sich an. Sie werden die Erbenisse der ausgewählten Mannschaften per E-mail erhalten.";

// Boutons
$btnSubscribe   = "sich abonnieren";
$btnUnsubscribe = "Abbestellen";
$btnInfo        = "Information";

?>