<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$live    = "Heute";

// Sous menus
$itList         = "Wettkämpfe";
$itLive         = "Live";
$itStream       = "Video";
$itLast         = "Neu";

// Titre des colonnes
$rowsMatchesV1  = "Feld";
$rowsMatchesV2  = "Phase";
$rowsMatchesV3  = "Runde";
$rowsMatchesV4  = "Spieler/Paarung A";
$rowsMatchesV5  = "Spieler/Paarung B";
$rowsMatchesV6  = "Spielfeld";
$rowsMatchesV7  = "Beginn";

$rowsResults1  = "Tabelle";
$rowsResults2  = "Phase";
$rowsResults3  = "Phase";
$rowsResults4  = "Spieler/Paarung A";
$rowsResults5  = "Spieler/Paarung B";
$rowsResults6  = "Punkte";
$rowsResults7  = "Dauer";
 
// Messages
$msgNoTies    = "Kein Wettkampf heute, bitte beachten Sie den Spielplan.";
$msgNoLiveNow = "Im Moment sind keine Wettkämpfe im Gange.";

$msgOnlyIE   = "Nur Plugins für Internet Explorer sind vorhanden.";
$msgWinamp   = "Falls Sie nicht über IE verfügen, können Sie Winamp benutzen.";
$msgVLC      = "Sie können auch VideoLan VLC ausprobieren.";
$msgLink     = "In beiden Fällen verwenden Sie die folgende Adresse.";
$msgNoStream = "Keine Videos verfügbar für dieses Turnier.";
$msgNoMatch  = "Im Moment sind keine Wettkämpfe im Gange. Beachten Sie den Spielplan.";

?>