<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";
include dirname(__FILE__)."/t_mber.inc";

// Titre  du navigateur
$mber      = "Etat civil";

// Titres des fenetres
$itAllMembers = "Alle Anmeldungen";
$itOthers      = "Andere Anmeldungen";
$itArrivals    = "Ankünfte";
$itDepartures  = "Abfahrten";
$tNewMember    = "Mitglied erstellen";
$tEditMember   = "Mitglied bearbeiten";
$tMembers     = "Alle Anmeldungen";
$tPlayers     = "Angemeldete Spieler";
$tOfficials   = "Angemeldete Offizielle";
$tOthers      = "Verschiedene";
$tPurchases   = "Einkaufsliste";
$tAccount     = "Kontoänderung";
$tCredits     = "Vorratsliste";
$tArrivals    = "Ankunfstliste";
$tDepartures  = "Abfahrtsliste";

// Titre des colonnes
$rowsMembers1  = "Geschlecht";
$rowsMembers2  = "Vorname";
$rowsMembers3  = "Name";
$rowsMembers4  = "Geboren am";
$rowsMembers5  = "IBF Nr.";
$rowsMembers6  = "Passnr.";
$rowsMembers6  = "Kommentar";

$rowsDeparr1  = "Art";
$rowsDeparr2  = "Identität";
$rowsDeparr3  = "Mannschaft";
$rowsDeparr4  = "Funktion";
$rowsDeparr5  = "Uhrzeit";
$rowsDeparr6  = "Ort";


// Label des zones
$regiAccount = "Konto :";
$regiTeam    = "Verein/Mannschaft :";
$regiName    = "Anmeldungen :";
$regiId      = $regiName;
$accountName = "Aktuelles Konto :";
$accountId = "Neues Konto :";
$regiArrival    = "Ankunftsdatum :";
$regiArrcmt     = "Ankunftsort :";
$regiDeparture  = "Abfahrtsdatum :";
$regiDepcmt     = "Abfahrtsort :";
$propagate      = "Ankunfts- und Absfahrtszeit aktualisieren";

// Label des listes

// Messages d'erreur
$msgNoMembers = "Keine Anmeldungen in dieser Kategorie.";

// Label des boutons

?>
