<?php

$itReload  = "Aktualisieren";
$itNew     = "Neu";
$itDelete  = "Löschen";
$itRestore = "Wiederherstellen";
$itErase   = "Entfernen";
$itMerge   = "Vereinen";

$itBadge   = "Badges PDF";
$itSearch  = "Suchen";
$itExit    = "Abmelden";
$itClose   = "Schließen";
$itMail    = "Mail";
$itHome    = "Home";
$itNone    = "&nbsp;";

$itPref    = "Einstellungen";
$itUsers   = "Benutzer";
$itEvents  = "Turniere";
$itBooks   = "Adressbuch";
$itAdmi    = "Parameter";
$itMaint   = "Wartung";
$itPhpInfo = "Php info";
$itHelp    = "Hilfe";
$itSubs    = "Abonnement";

$itAttribs = "Parameter";
$itGeneral = "Nützliche Infos";
$itClubs   = "Land & Verein";
$itTeams   = "Mannschaft";
$itPlayers = "Spieler";
$itRegister = "Anmeldungen";
$itOfficials = "Offizielle";
$itOthers    = "Andere";
$itDraws     = "Auslosung";
$itProgram   = "Programme";
$itCalendar  = "Terminkalender";
$itDivisions = "Divisions";
$itResults   = "Ergebnisse";
$itRanking   = "Klassements";
$itSchedule  = "Uhrzeit";
$itManage    = "Turnierablauf";
$itTies      = "Begegnungen";
$itTransfert = "Import/Export";

$itSport     = "Sportliches";
$itAdmin     = "Administratives";
$itEntries   = "Anmeldungen";
$itAccomodation = "Unterbringung";
$itTransport    = "Transport";

$itItems     = "Artikel";
$itAccounts  = "Konten";
$itPurchases = "Einkäufe";
$itToday     = "Heute";
$itEvent     = "Andere Turniere";
$itPrint     = "Drucken";

$itConfident = "Vertraulich";
$itPrivate   = "Privat";
$itPublic    = "Öffentlich";

$itEdit          = "Änderung";
$itAutorisations = "Erlaubnis";
$itPublication   = "Veröffentlichung";

$itGroup    = "Gruppen";
$itMainDraw = "KO Runde";


$itSH = "HE";
$itSD = "DE";
$itDH = "HD";
$itDD = "DD";
$itMX = "MX";
$itInscrits = "Anmeldungen";


?>
