<?php

// Menu general
$itGeneral   = "Information";
$itRegister  = "Anmeldungen";
$itDraws     = "Tabellen";
$itCalendar  = "Agenda";
$itToday     = "Heute";

// Sous menu
$itTeams     = "Mannschaften";
$itPlayers   = "Spieler";
$itOfficials = "Amtsperson";

// Temporaire pour les invites
$itExit      = "Abmelden";
$itEvents    = "Turniere";
$itPref      = "Einstellungen";
$itHome      = "Home";
$tUsersStat  = "Statistiken";
$nbUser      = "Mitglieder :";
$lastUser    = "Letzter :";
$tEventsStat = "Turniere";
$nbEvents    = "Anzahl :";
$nbAnonymousVisit   = "Besucher :";
$nbUsersVisit  = "Mitglieder :";
$nbAdminVisit= "Verwalter :";

$lgdVisitor = "&nbsp;Besucher";
$lgdUser    = "&nbsp;Benutzer";
$lgdGuest   = "&nbsp;Eingeladen";
$lgdFriend  = "&nbsp;Freund";
$lgdAssist  = "&nbsp;Assistant";
$lgdAdmin   = "&nbsp;Administrator";
$lgdManager = "&nbsp;Verwalter";

$lgdConfident = "&nbsp;Vertraulich";
$lgdPrivate   = "&nbsp;Privat";
$lgdPublic    = "&nbsp;Öffentlich";
$lgdDelete   = "&nbsp;Löschen";


?>