<?php

include "menu.inc";
include "badnet.inc";

// Titres des fenetres
$tDraws    = "Gestion des tableaux";


// Titre des colonnes
$rowsEvents2  = "Name";
$rowsEvents3  = "Datum";
$rowsEvents4  = "Ort";
$rowsEvents5  = "Veranstalter";
$rowsEvents6  = "Kommentar";
$rowsEvents7  = "Inhaber";


// Label des zones


// Label des listes


// Messages d'erreur
$msgRegistered  = "Die Änderungen wurden gespeichert";

// Label des boutons
$End       = "Schließen";
$Cancel    = "Cancel";
$Validate  = "Bestätigen";
$Register  = "Speichern";
$AddUser    = "Benutzer hinzufügen";
$RemoveUser = "Benutzer entfernen";


?>