<?php

$PDF_GENERATED = "Generated ";

// Titre pour la feuille de résultats
$PDF_DATE = "Datum";
$PDF_LIEU = "Platz";

$PDF_ORDRE = "Reihenfolge";
$PDF_TERRAIN = "Spielfeld";

$PDF_MATCHES = "Spiel";

$PDF_TEAMA = "Team A";
$PDF_TEAMB = "Team B";
$PDF_SCORES = "Ergebnisse";
$PDF_VICTOIRES = "Spiele";
$PDF_SETS = "Sätze";
$PDF_POINTS = "Punkte";

$PDF_VAINQUEUR = "GEWINNER";
$PDF_SCORE = "ERGEBNIS";
$PDF_TOTAUX ="GESAMT";

// Titre pour les déclaration d'équipes
$PDF_DAY  = "TAG";
$PDF_TIME = "ZEIT";
$PDF_TIE  = "TIE";
$PDF_DIVISION  = "STAGE";
$PDF_GROUP     = "GROUP";
$PDF_COURT     = "SPIELFELD N°";
$PDF_COMPO     = "TEAM PLATZIERUNG";

$PDF_ICN = "NATIONAL TEAM COMPETITION" ;
$PDF_DECLARATION_DE = "" ;
$PDF_COMPO = "TEAM COMPOSITION" ;
$PDF_RENCONTRE = "TIE" ;
$PDF_VERSUS = " vs " ;
$PDF_DEPOSE = "Dem Schiedsrichter übergeben :";

$PDF_MATCHES_ORDER = "Match order" ;
$PDF_DISCIPLINE = "Match" ;
$PDF_TEAM_COMPOSITION = "TEAM COMPOSITION" ;
$PDF_ORDER_PROPOSED = "you" ;
$PDF_ORDER_FINAL = "final" ;
$PDF_ORDER_OPPENENT = "opp.";
$PDF_NOM = " NAME";
$PDF_PRENOM = "vorname";

$PDF_SIGN_CAPTAIN = "Spielführer Name und Unterschrift" ;
$PDF_HEURE_DEPOT = "Time" ;
$PDF_REFEREE_OBSERVATIONS = "Bemerkung des Schiedsrichter" ;

// Titre pour le programme
$PDF_SCHEDULE  = "SCHEDULE";

// Titre pour les groupes
$PDF_GROUPS  = "GRUPPEN ZUSAMMENSTELLUNG";
$PDF_POULES  = "GRUPPEN";
$PDF_DEFGROUP_3 = "Qualikanten in 3er Gruppen :";
$PDF_DEFGROUP_4 = "Qualikanten in 4er Gruppen :";
$PDF_DEFGROUP_5 = "Qualikanten in 5er Gruppen :";
$PDF_DEFGROUP_SECOND = "Bester Zweiter :";

// Titre pour la feuille de score
$PDF_DIVISION  = "Liga :" ;
$PDF_START     = "Start :" ;
$PDF_UMPIRE    = "Umpire :" ;
$PDF_NUM       = "Spiel n°:" ;
$PDF_EVENT     = "Turnier : " ;
$PDF_END_M     = "Ende :";
$PDF_COURT     = "Spielfeld # :";
$PDF_LENGTH_M  = "Speildauer :";
$PDF_DATE      = "Datum : ";
$PDF_TIME      = "Uhrzeit : ";
$PDF_SERVICE   = "aufschlagrichter :";
$PDF_UMP_SIGNATURE = "Umpire signature :" ;
$PDF_REF_SIGNATURE = "Referee signature :" ;


// Titre pour le programme
$PDF_PROGRAM  = "PROGRAM";

// Titre pour le classement d'un tableau
$PDF_RESULTS = "ERGEBNISSE" ;
$PDF_RANKING = "PLATZIERUNG" ;
$PDF_TEAM = "Mannschaft" ;

$PDF_RANK_COMMENTS  = " S :  Gewonnen+  / N : Verloren / ";
$PDF_RANK_COMMENTS .= " M+ : Spiele +  / M- : Spiele - / MD : Verhältnis / ";
$PDF_RANK_COMMENTS .= " S+ : Sätze + / S- : Sätze - / SD : Satz verhältnis / ";
$PDF_RANK_COMMENTS .= " P+ : Punkte + / P- : Punkte - / PD : Punkt Verhältnis ";
$PDF_RANG_LEG1 = 'S : Siege / N : Niederlagen / M+ : Gewonnene Spiele / M- : Verlorene Spiele / MA : Verhältnis';
$PDF_RANG_LEG2 = 'G+ : Gewonnene Sätze / G- : Verlorene Sätze / GA : Games Average / P+ : Points Won / P- : Points Lost / PA : Points Average';


$PDF_MONSIEUR = "H" ;
$PDF_MLLE = "Fr" ;
$PDF_MADAME = "Fr" ;

// Titre pour les fiches d'activite arbitre
$PDF_TOTAL  = "Gesamt";
$PDF_MATCH  = "Spiel";
$PDF_ROUND  = "Runde";
$PDF_STEP   = "Step";
$PDF_BEGIN  = "Beginn";
$PDF_END    = "Ende";
$PDF_LENGTH = "Dauer";


// Titre pour les badges
$PDF_TYPE_JOUEUR = "Spieler" ;

// Bas de page
$page     = "Seite N° ";
$generate = "gedruckt";

?>
