<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$prefs      = "Einstellungen";

// Titres des fenetres

// Titres des blocs
$blkMail = "Email";

// Titre des colonnes
$rowsRanks ="klassement"; 
$rowsRanks1 ="Label"; 
$rowsRanks2 ="Punkte"; 
$rowsRanks3 ="Grenze"; 

// Label des zones
$host = "SMTP Server :";
$port = "Port :";
$username = "Name :";
$password = "Passwort :";
$ffbaEmail = "Email FFBa :";
$ffbaUrl = "Url fiche joueurs nationaux :";
$ibfUrl = "Url fiche joueurs internationaux :";

// Label des listes

// Messages d'erreur

// Label des boutons
$btnUpdateMail = "Speichern";
$btnAddRank    = "Erstellen";
$btnDelRank    = "Entfernen";
?>
