<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$regi = "Anmeldungen";


// Colonnes
$rowsAssos1 = "Name";
$rowsAssos2 = "Pseudonym";
$rowsAssos3 = "Web";

$rowsRegiV1 = "Qualität";
$rowsRegiV2 = "Name Vorname";
$rowsRegiV3 = "Land";
$rowsRegiV5 = "Mannschaft";

// Messages
$msgNoTeams              = "Keine Mannschaft vorhanden";
$msgNoRegisteredPlayer   = "Im Moment sind noch keine SpielerInnen angemeldet!";
$msgNoRegisteredOfficial = "Keine Amtsperson registriert";

?>