<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$resu   = "Spieler";

// Label des zones
$mberBorn       = "Geburtsdatum";
$mberLicence    = "Lizenz";
$mberIbfNumber  = "Ibf-Nummer";
$mberAsso       = "Mannschaft";
$mberRank       = "Klassement";

// Titre des colonnes
$rowsResuIndiv1 = "Phase";
$rowsResuIndiv2 = "Tour";
$rowsResuIndiv3 = "Gegner";
$rowsResuIndiv4 = "Ergebnis";
$rowsResuIndiv5 = "Punkte";
$rowsResuIndiv6 = "Dauer";

// Messages
$msgNoMatch = "Für diese(n) SpielerIn ist noch kein Spiel vorhanden";

?>