<?php
/* Chaines de caractere pour les libelles des champs de la table 
des associations */

// Label des zones
$assoId         = "Identifiant :";
$assoName       = "Name :";
$assoStamp      = "Abkürzung :";
$assoType       = "Modus :";
$assoFedeId     = "Linzenznummer poona :";
$assoExternId   = "Lizenznummer experne :";
$assoCmt        = "Kommentare :";
$assoUrl        = "Internetadresse :";
$assoLogo       = "Logo :";
$assoNumber     = "Matrikelnummer :";
$assoDpt        = "Departement :";
$assoPseudo     = "Pseudonym :";
$assoNoc        = "Olympischer Code (NOC) :";
$assoLockId     = "Gesperrt durch :";

// Messages d'erreur
$msgassoName    = "Der Name ist Pflicht.";
$msgassoStamp   = "Die Abkürzung ist Pflicht.";
$msgassoType    = "t_asso.inc.";
$msgassoPseudo  = "Das Pseudonym ist Pflicht.";
$msgassoNoc     = "Der olympische Code ist Pflicht.";


?>