<?php
/* Chaines de caractere pour les libelles des champs de la table draws */

$serialName   = "Libellé :";
$serial_ms     = "Herreneinzel";
$serial_ls     = "Dameneinzel";
$serial_md     = "Herrendoppel";
$serial_ld     = "Damendoppel";
$serial_mx     = "Mixed";

$drawSerial = "Spielklasse :";
$drawName   = "Name :";
$drawStamp  = "Abkürzung :";
$drawDisci  = "Disziplin :";
$drawType   = "Modus :";
$drawCatage = "Altersklasse :";
$drawRank   = "Maximale Spielstärke :";
$drawType   = "Modus :";
$drawNbp3   = "Anzahl der 3er Gruppen :";
$drawNbs3   = "Anzahl der Qualifikanten :";
$drawNbp4   = "Anzahl der 4er Gruppen :";
$drawNbs4   = "Anzahl der Qualifikanten :";
$drawNbp5   = "Anzahl der 5er Gruppen :";
$drawNbs5   = "Anzahl der Qualifikanten :";
$drawNbsd   = "Nombre de second :";
$drawNbq    = "Anzahl der Qualiplätze :";
$drawNbplq  = "Spieler in der Quali :";
$drawNbpl   = "Plätze im Hauptfeld :";
$drawNbcons = "Plätze in der Trostrunde :";
$drawThirdI = "Spiel um Platz 3 :";
$drawThird  = "Spiel um Platz 3";


$msgserialname   = "Le libellé est obligatoire !";

?>