<?php
/* Chaines de caractere pour les libelles des champs de la table event */
$evntName        = "Name :";
$evntPlace       = "Ort :";
$evntDate        = "Datum :";
$evntOrganizer   = "Veranstalter :";
$evntDatedraw    = "Auslosung :";
$evntDeadline    = "Meldeschluss :";
$evntCmt         = "Kommentare :";
$evntDeadline    = "Meldeschluss :";
$evntDrawdate    = "Auslosung :";
$evntNature      = "Turnierart :";
$evntLevel       = "Niveau des Turniers :";
$evntNumauto     = "Autorisierungsnummer :";
$evntUrl         = "Internetseite:";
$evntPoster      = "Plakat :";
$evntNbvisited   = "Anzahl der Besuche :";
$evntId          = "Login :";
$evntScoring     = "Zählweise :";
$evntRanking     = "Art der Classements :";
$evntNbDrawMax   = "Maximale Disziplinen :";
$evntUrlRank     = "Url Ergebnisse :";

$msgevntName   = "Der Turniername ist Pflicht !";


?>