<?php


/* Chaines de caractere pour les libelles des champs de la table 
des hotels */

// Label des zones
$hotelHotel      = "Name :";
$hotelDescr      = "Beschreibung :";
$hotelCost       = "Kosten :";
$hotelShortname  = "Abkürzung :";


// Messages d'erreur
$msghotelHotel = "Der Name ist Pflicht.";
$msghotelDescr = "Die Beschreibung ist Pflicht.";
$msghotelCost  = "der Preis ist Pflicht.";
$msghotelShortname = "Die Abkürzung ist Pflicht.";





?>