<?php


/* Chaines de caractere pour les libelles des champs de la table 
des items */

// Label des zones
$itemName      = "Name :";
$itemCode      = "Code :";
$itemRef       = "Référence :";
$itemCount     = "Quantité :";
$itemIsFollowed = "Suivre la consommation";
$itemIsCreditable = "Remisable";
$itemRubrikId   = "Rubrik :";
$itemValue      = "Wert :";

$IS = "Einzel :";
$ID = "Doppel :";
$IM = "Mixde :";
$I1 = "1 Disziplin :";
$I2 = "2 Disziplinen :";
$I3 = "3 Disziplinen :";

// Messages d'erreur
$msgitemName   = "Der Name muss angebeben werden.";
$msgitemValue  = "Der Wert muss angegeben werden.";

?>