<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$mberSexe       = "Geschlecht :";
$mberSexe1      = "Herr";
$mberSexe2      = "Frau";
$mberFirstName  = "Vorname :";
$mberSecondName = "Name :";
$mberBorn       = "Geboren am :";
$mberIbfNumber  = "Ibf Nr.:";
$mberLicence    = "Passnr. :";
$mberCountryId  = "Land :";
$mberId         = "Benutzername :";
$mberFedeId     = "Benutzername Poona :";
$mberExternId   = "Externer Benutzername :";
$mberUrlPhoto   = "Url Foto :";
$mberLockId     = "Gesperrt durch :";


// Messages d'erreur
$msgmberSexe = " Wählen Sie das Geschlecht :-)";
$msgmberFirstName = "Der Vorname ist Pflicht.";
$msgmberSecondName = "Der Name ist Pflicht.";

?>