<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$regiDate       = "Einschreibedatum :";
$regiType       = "Typ :";
$regiLongName   = "Name (lang) :";
$regiShortName  = "Name (kurz) :";
$regiTeamId     = "Mannschaft :";
$regiTeamName   = "Mannschaft :";
$regiCmt        = "Kommentar :";
$regiFunction   = "Funktion :";
$regiNoc        = "NOC :";
$regiArrival    = "Ankunft :";
$regiArrCmt     = "Précision t_regi :";
$regiDeparture  = "Abfahrt :";
$regiDepCmt     = "Précision :";
$regiCatage     = "Kategorie :";
$regiSurclasse  = "Seniorenerklärung :";
$regiDateSurclasse  = "Seit :";
$regiDateAuto   = "Aktiv seit :";

$regiStatus1    = "Stammspieler";
$regiStatus2    = "Ersatzspieler";
$regiStatus3    = "Andere";

$regiType1 = "Oberschiedsrichter";
$regiType2 = "Vertreter Oberschiedsrichter";
$regiType3 = "Schiedsrichter";
$regiType4 = "Linienrichter";

$regiAccountId1 = "Mannschaftsaccount";
$regiAccountId2 = "Persönliches Konto";

$regiRest = "Pause seit (tt-mm-jj hh:mm) :";
$regiDelay = "Abwesend bis (tt-mm-jj hh:mm) :";
$regiPresent = "Anwesend in der Halle :";
$regiWo = "Aufgabe :";
$regiUmpire = "Schiedsrichter auf Feld:";
$regiPlay = "Spielt auf Feld:";
$regiCourt = "Beschäftigt auf Feld:";

// Messages d'erreur
$msgregiTeamId = "Eine Mannschaft einzutragen ist Pflicht.";


?>