<?php
/* Chaines de caractere pour les libelles des champs de la table 
des equipes */

// Label des zones
$teamDate       = "Anmeldedatum :";
$teamName       = "Name :";
$teamStamp      = "Abkürzung :";
$teamCaptain    = "Spielführer :";
$teamCmt        = "Kommentare :";
$teamClub       = "Verein :";
$teamUrl        = "Internetadresse :";
$teamNoc        = "Olympischer Code (NOC) :";
$assoId         = "Verein :";
$teamAssoId     = "Verein :";

// Messages d'erreur
$msgteamName  = "Der Name ist Pflicht.";
$msgteamStamp = "Die Abkürzung ist Pflicht.";
$msgteamDate  = "Das Anmeldedatum ist Pflicht.";
$msgteamAssoId  = "Der Verein ist Pflicht.";

?>