<?php
/* Chaines de caractere pour les libelles des champs de la table user */

$userName   = "Name :";
$userLogin  = "Login :";
$userPseudo = "Pseudonym :";
$userPass   = "Passwort :";
$userLang   = "Sprache :";
$userEmail  = "Email :";
$userCmt    = "Kommentar :";
$userId     = "Login :";
$userLastvisit = "Letzter Besuch :";
$userNbcnx     = "Anzahl Verbindungen :";
$userSkin      = "Deko :";

$msguserName   = "Der name ist Pflicht !";
$msguserPseudo = "Das pseudonym ist Pflicht !";
$msguserLogin  = "Der Login ist Pflicht !";
$msguserPass   = "Das Passwort ist Pflicht !";

?>