<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$teams  = "Mannschaften";

// Actions
$itConvocsPdf  = "Pdf dokument";

// Label des zones
$assoPseudo     = "Pseudo";
$assoStamp      = "Kürzel";
$assoUrl        = "Internet-Homepage";
$assoNoc        = "Land (NOC)";

// Titre des colonnes
$rowsPairs_V1 = "Spieler/Paarungen";
$rowsPairs_V2 = "Tabelle";
$rowsPairs_V3 = "int. Rang";
$rowsPairs_V4 = "nat. Rang";
$rowsPairs_V5 = "Stadium";

$rowsPlayers1 = "Qualität";
$rowsPlayers2 = "Name Vorname";
$rowsPlayers3 = "Auslosung";
$rowsPlayers4 = "Convocation";
$rowsPlayers5 = "Sporthalle";

// Messages
$msgConvocation = "Das erste Spiel findet 30 Minuten nach der heures de convocation statt.";
?>