<?php 
require_once 'Object/Ocommand.inc'; 
define('LABEL_420','Libellé ES'); 
define('LABEL_421','Libellé ES'); 
define('LABEL_422','Libellé ES'); 
define('LABEL_423','Libellé ES'); 
define('LABEL_424','Libellé ES'); 
define('LABEL_425','Libellé ES'); 
define('LABEL_426','Libellé ES'); 
define('LABEL_427','Libellé ES'); 
define('LABEL_180','Libellé ES'); 
define('LABEL_181','Libellé ES'); 
define('LABEL_182','Libellé ES'); 
define('LABEL_183','Libellé ES'); 
define('LABEL_184','Libellé ES'); 
define('LABEL_185','Libellé ES'); 
define('LABEL_186','Libellé ES'); 
?>