<?php
/*****************************************************************************
!   Module    : Divisions
!   File       : $Source: /cvsroot/aotb/badnet/src/divs/divs.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.3 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/18 07:51:18 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

define("DIV_MAIN",         WBS_ACT_DIVS+1);
define("DIV_UPDATE_A",     WBS_ACT_DIVS+2);

define("GROUP_EDIT_A",     WBS_ACT_DIVS+3);
define("GROUP_UPDATE_A",   WBS_ACT_DIVS+4);
define("GROUP_DELETE_A",   WBS_ACT_DIVS+5);
define("GROUP_TEAM_A",     WBS_ACT_DIVS+6);
define("GROUP_REGTEAM_A",  WBS_ACT_DIVS+7);

define("TEAM_UP_A",      WBS_ACT_DIVS+9);
define("TEAM_DOWN_A",    WBS_ACT_DIVS+10);


define("TEAM_RESULT_V",  WBS_ACT_DIVS+11);
define("TEAM_RANK_V",    WBS_ACT_DIVS+12);

define("DIV_ADD_GROUP",      WBS_ACT_DIVS+13);
define("DIV_CONFIRM_GROUPS", WBS_ACT_DIVS+14);
define("DIV_CREATE_A",       WBS_ACT_DIVS+15);
define("DIV_CONFIRM_DEL",    WBS_ACT_DIVS+16);
define("DIV_PDF",            WBS_ACT_DIVS+17);

?>