<?php

include dirname(__FILE__)."/menu_V.inc";
//include dirname(__FILE__)."/t_asso.inc";

// Titre  du navigateur
$asso      = "Associations";

// Menu
$itEntries     = "Inscriptions";
$itItems       = "Articles";
$itReservation = "Réservations";
$itCompetition = "Compétition";


// Titre des colonnes
$rowsPlayers1  = "Genre";
$rowsPlayers2  = "Identité";
$rowsPlayers3  = "Nat Num";
$rowsPlayers4  = "Ibf Num";
$rowsPlayers5  = "Tableaux";

$reservations1 = "Date";
$reservations2 = "Article";
$reservations3 = "Identité";
$reservations4 = "Coût";
$reservations5 = "Remise";
$reservations6 = "Payé";
$reservations7 = "Solde";

// Messages
$msgNoPlayers      = "Aucun joueurs pour ce tournoi";
$msgNoReservations = "Aucune réservation pour ce tournoi";
?>
