<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";


// Titre  du navigateur
$badges    = "Badges";

// Titres des fenetres
$tBadgeEdit = "Définition de bagde";
$itModels   = "Modèles";
$itZones    = "Zones";
$tZone      = "Modifier une zone";
// Menus 
$itPrinted    = "Imprimé";
$itNoPrinted  = "Non imprimé";

// Label des zones
$badgeName = "Nom du modèle";
$badgeWidth = "Largeur en mm :";
$badgeHeight = "Hauteur en mm :";
$badgeBoder = "Bordure (LTRB) :";
$badgeBoderSize = "Epaisseur bordure :";
$badgeTopMargin = "Marge haute :";
$badgeLeftMargin = "Marge gauche :";
$badgeDeltaWidth = "Ecart largeur :";
$badgeDeltaHeight = "Ecart hauteur :";

$eltbFont = "Police :";
$eltbSize = "Taille :";
$eltbBold = "Graisse :";
$eltbAlign = "Alignement :";
$eltbTop  = "Haut :";
$eltbLeft = "Gauche :";
$eltbWidth  = "Largeur :";
$eltbHeight = "Hauteur :";
$eltbBorder = "Cadre :";
$eltbBorderSize = "Epaisseur cadre :";
$eltbField  = "Champs :";
$eltbValue  = "Valeur fixe :";
$eltbTextColor = "Couleur texte :";
$eltbFillColor = "Couleur fond :";
$eltbDrawColor = "Couleur cadre :";
$eltbZone      = "Zone :";

// Titre de colonnes 
$badgeList1 = "Nom";
$badgeList2 = "Largeur (mm)";
$badgeList3 = "Hauteur (mm)";
$badgeList4 = "Bordure";
$badgeList5 = "Epaisseur";
$badgeList6 = "Marge haute";
$badgeList7 = "Marge gauche";
$badgeList8 = "Ecart largeur";
$badgeList9 = "Ecart hauteur";

$badgeElts1 = "Police";
$badgeElts2 = "Taille";
$badgeElts3 = "Graisse";
$badgeElts4 = "Alignement";
$badgeElts5 = "Haut";
$badgeElts6 = "Gauche";
$badgeElts7 = "Largeur";
$badgeElts8 = "Hauteur";
$badgeElts9 = "Cadre";
$badgeElts10 = "Epaisseur";
$badgeElts11 = "Champ";
$badgeElts12 = "Valeur";
$badgeElts13 = "Couleur Texte";
$badgeElts14 = "Couleur Fond";
$badgeElts15 = "Couleur";

$members1 = "Genre";
$members2 = "Nom";
$members3 = "Prénom";
$members4 = "Fonction";
$members5 = "NOC";
$members6 = "Equipe";
$members7 = "Logo";
$members8 = "Imprimé";

$zoneName = "Nom de la zone :";
$zoneColor= "Couleur :";

$zoneList1 = "Nom";
$zoneList2 = "Couleur";

$listOk  = "Autorisé";
$listNok = "Interdit";


// Messages d'erreur


// Label des boutons
$btnAdd = "Autoriser >>>";
$btnRemove = "<<< Interdire";
?>