<?php

$tSubsList    = "Abonnements";
$msgSubscript = "Abonnez-vous maintenant aux résultats!";

$tManagerList = "Contacts";
$helpManager  = "Contacter un gestionnaire du tournoi :";

$badnetLink  = "Lien direct sur cette page :";
$msgDataBaseError = "Erreur d'accés à la base de données. Essayez à nouveau.";

$badnetVersion = "Page générée par ";

$lgdIncomplete  = "Incomplet";
$lgdBusy        = "Occupé";
$lgdRest        = "Repos";
$lgdReady       = "Ok";
$lgdLive        = "En cours";
$lgdEnded       = "Terminé";
$lgdClosed      = "Terminé";
$lgdSend        = "Transmis";

$lgdMaindraw  = "M : Tableau Principal";
$lgdQualif    = "Q : Qualification";
$lgdReserve   = "R : Remplaçant";
$lgdWdn       = "WDN : Forfait";
$lgdPtq       = "PTQ : Promu en qualif";
$lgdPtm       = "PTM : Promu tableau principal";

?>