<?php

/* Chaines de caracteres generiques */
$badnet_lang = 'fr';
$leftTitle = "Badminton Netware";
$rightTitle = "Connexion";

$wbs_notYet = "Fonction non disponible";

$image = "Fichier image :";

$lgdVisitor = "&nbsp;Visiteur";
$lgdUser    = "&nbsp;Utilisateur";
$lgdGuest   = "&nbsp;Invité";
$lgdFriend  = "&nbsp;Ami";
$lgdCaptain = "&nbsp;Capitaine";
$lgdAssist  = "&nbsp;Assistant";
$lgdAdmin   = "&nbsp;Administrateur";
$lgdManager = "&nbsp;Gestionnaire";
$lgdReferee = "&nbsp;Juge arbitre";

$lgdConfident = "&nbsp;Confidentiel";
$lgdPrivate   = "&nbsp;Privé";
$lgdPublic    = "&nbsp;Public";
$lgdDelete   = "&nbsp;Effacée";

$lgdIncomplete  = "Incomplet";
$lgdBusy        = "Occupé";
$lgdRest        = "Repos";
$lgdReady       = "Ok";
$lgdLive        = "En cours";
$lgdEnded       = "Terminé";
$lgdClosed      = "Validé";
$lgdSend        = "Transmis";

$lgdMaindraw  = "M: Tableau final";
$lgdQualif    = "Q: Qualification";
$lgdReserve   = "R: Liste d'attente";
$lgdWdn       = "WND: Forfait";
$lgdPtq       = "PTQ: Promu en qualification";
$lgdPfr       = "PFR: Promu de la liste d'attente";
$lgdPtm       = "PMD: Promu dans le tableau final";
$lgdPfq       = "PFQ: Promu des qualifications";
$lgdRtd       = "RTD: Retiré";
$lgdQualify   = "Q: Qualifié";

$lgdPairs   = "Plus de joueurs/paires que de places";
$lgdPlaces  = "Pas assez de joueurs/paires";
$lgdCompose = "Paire composée";

$helpAdmin  = "Contacter un administrateur pour un problème de fonctionnement, une idée...un encouragement, pourquoi pas";

$username  = "Login :";
$password  = "Mot de passe :";

$tSubsList    = "Abonnements";
$msgSubscript = "Abonnez-vous maintenant aux résultats!";
$msgSubsList  = "Vous êtes abonnés aux résultats des équipes";
$msgAskEvent = "Contacter un administrateur ci-dessous pour ajouter un tournoi ou obtenir des droits supplémentaires.";
$msgNoAutorisation  = "Vous n'avez pas les droits suffisants pour consulter ces informations.";
$msgDirectLink  = "Lien direct sur cette page :";

$msgUseImage  = "Cliquez sur l'image de votre choix ou téléchargez une nouvelle depuis votre ordinateur.";
$msgLimitedImage  = "ATTENTION: seules les images au format JPEG ou PNG sans transparence seront correctement affichées dans les documents PDF.";
$msgDataBaseError = "Erreur d'accés à la base de données. Essayez à nouveau.";

$tManagerList = "Contacts";
$helpManager  = "Contacter un gestionnaire du tournoi :";

$tEventInfos = "Pratique";
$numAuto     = "Autorisation";
$deadline    = "Fin inscription";
$evntDraws   = "Tirage au sort";
$evntBegin   = "Premier jour";
$evntFin     = "Dernier jour";
$evntSite    = "Site officiel :";

$tAdminList   = "Contacts";
$tUsersStat   = "Membres";
$tEventsStat  = "Tournois";
$tVisitsStat  = "Visites";
$nbUsers     = "Nombre :";
$lastUser    = "Dernier :";

$nbAnonymousVisit  = "Anonymes :";
$nbUsersVisit      = "Membres :";
$nbAdminVisit      = "Administrateurs :";


$tEventStat   = "Statistiques";
$nbSubscribe  = "Abonnés :";
$nbVisite     = "Visites :";
$nbTeams      = "Equipes :";
$nbPlayers    = "Joueurs :";
$nbMatchs     = "Matchs :";
$nbEvents     = "Total :";

$badnetVersion = "Version ";
$badnetCacheSince = "";


// Label des boutons
$btnRegisterAll  = "Enregistrer tous";
$btnRegister  = "Enregistrer";
$btnDelete    = "Supprimer";
$btnModify    = "Modifier";
$btnCancel    = "Abandonner";
$btnNew       = "Nouveau";
$btnClose     = "Fermer";
$btnSearch    = "Chercher";
$btnConfident = "Confidentiel";
$btnPrivate   = "Privé";
$btnPublic    = "Public";
$btnHelp      = "Aide";
$btnPlus      = "Plus d'info";
$btnMoins     = "Masquer";
?>