<?php
// Label des chaines de caracteres fixes genrale a toutes les forms
// Le numero est celui defini dans utils/const.inc
$WBS_LABEL_A = "Administrateur";
$WBS_LABEL_U = "Utilisateur";
$WBS_LABEL_V = "Visiteur";
$WBS_LABEL_G = "Invité";
$WBS_LABEL_F = "Ami";
$WBS_LABEL_T = "Capitaine";
$WBS_LABEL_S = "Assistant";
$WBS_LABEL_M = "Gestionnaire"; 
$WBS_LABEL_R = "Juge arbitre"; 

$WBS_LABEL_0 = "Non défini";

$WBS_LABEL_1 = "Simple Homme";
$WBS_LABEL_2 = "Simple Dame";
$WBS_LABEL_3 = "Double Homme";
$WBS_LABEL_4 = "Double Dame";
$WBS_LABEL_5 = "Double Mixte";

$WBS_LABEL_6 = "Homme";
$WBS_LABEL_7 = "Femme";

$WBS_LABEL_10 = "Poule (+ KO)";
$WBS_LABEL_11 = "Qualification + KO";
$WBS_LABEL_12 = "KO seul";
$WBS_LABEL_13 = "Equipe";
$WBS_LABEL_14 = "Ronde suisse";
$WBS_LABEL_15 = "Poule";
$WBS_LABEL_16 = "Poule A/R";
$WBS_LABEL_17 = "KO seul";
$WBS_LABEL_18 = "KO + plateaux";

$WBS_LABEL_20 = "Arbitre officiel";
$WBS_LABEL_21 = "Avec juge de service";
$WBS_LABEL_22 = "Auto-arbitrage";
$WBS_LABEL_23 = "Gagnant";
$WBS_LABEL_24 = "Perdant";

$WBS_LABEL_30 = "Incomplet";
$WBS_LABEL_31 = "Joueur indisponible";
$WBS_LABEL_32 = "Joueur en repos";
$WBS_LABEL_33 = "Prêt";
$WBS_LABEL_34 = "En cours";
$WBS_LABEL_35 = "Terminé";
$WBS_LABEL_36 = "Validé";
$WBS_LABEL_37 = "Tranmis";

$WBS_LABEL_40 = "Email";
$WBS_LABEL_41 = "Fax";
$WBS_LABEL_42 = "Portable";
$WBS_LABEL_43 = "Téléphone";

$WBS_LABEL_50 = "Fédération";
$WBS_LABEL_51 = "Association d'arbitre";
$WBS_LABEL_52 = "Ligue";
$WBS_LABEL_53 = "Codep";
$WBS_LABEL_54 = "Club";
$WBS_LABEL_55 = "Ecole";

$WBS_LABEL_60 = "Joueur";
$WBS_LABEL_61 = "Juge-arbitre";
$WBS_LABEL_62 = "JA Adjoint";
$WBS_LABEL_63 = "Arbitre";
$WBS_LABEL_64 = "Juge de Lignes";
$WBS_LABEL_65 = "Entraîneur";
$WBS_LABEL_66 = "Conseiller d'arbitrage";
$WBS_LABEL_67 = "Délégué fédéral";

$WBS_LABEL_70 = "Individuel";
$WBS_LABEL_71 = "Interclub/Par équipe";
$WBS_LABEL_72 = "Championnat";
$WBS_LABEL_73 = "Trophée";
$WBS_LABEL_74 = "Intercodep";

$WBS_LABEL_430 = "Département";
$WBS_LABEL_431 = "Régional";
$WBS_LABEL_432 = "National";
$WBS_LABEL_433 = "International";
$WBS_LABEL_434 = "Inter region";
$WBS_LABEL_435 = "Inter département";
$WBS_LABEL_436 = "Club";

$WBS_LABEL_80 = "Non joué";
$WBS_LABEL_81 = "Gagné";
$WBS_LABEL_82 = "Gagné par abandon";
$WBS_LABEL_83 = "Gagné par WO";
$WBS_LABEL_84 = "Perdu";
$WBS_LABEL_85 = "Perdu par abandon ";
$WBS_LABEL_86 = "Perdu par WO";

$WBS_LABEL_89 = "DNS: Ne s'est pas présenté";
$WBS_LABEL_90 = "M: Tableau final";
$WBS_LABEL_91 = "Q: Qualification";
$WBS_LABEL_92 = "R: Réserve";
$WBS_LABEL_93 = "PTQ: Promu dans les qualif";
$WBS_LABEL_94 = "PFR: Promu de la Reserve";
$WBS_LABEL_95 = "PMD: Promu dans le tableau final";
$WBS_LABEL_96 = "PFQ: Promu des qualifications";
$WBS_LABEL_97 = "WDN: Forfait";
$WBS_LABEL_98 = "INJ: Blessé";
$WBS_LABEL_99 = "----";

$WBS_LABEL_100 = "Gagné";
$WBS_LABEL_101 = "Perdu";
$WBS_LABEL_102 = "Egalité";
$WBS_LABEL_103 = "Non joué";
$WBS_LABEL_104 = "Perdu WO";
$WBS_LABEL_105 = "Gagné WO";
$WBS_LABEL_107 = "Nul perdant";
$WBS_LABEL_108 = "Nul gagnant";

$WBS_LABEL_110 = "Simple";
$WBS_LABEL_111 = "Double";
$WBS_LABEL_112 = "Mixte";

$WBS_LABEL_140 = "Classement général";
$WBS_LABEL_141 = "Match décisif";
$WBS_LABEL_142 = "Egalité autorisée";

$WBS_LABEL_160 = "Oui";
$WBS_LABEL_161 = "Non";

$WBS_LABEL_170 = "Bénévole";
$WBS_LABEL_171 = "Organisation";
$WBS_LABEL_172 = "VIP";
$WBS_LABEL_173 = "Presse";
$WBS_LABEL_174 = "Invité";
$WBS_LABEL_175 = "Médical";
$WBS_LABEL_176 = "Exposant";
$WBS_LABEL_177 = "Plateau";
$WBS_LABEL_178 = "Sécurité";
$WBS_LABEL_179 = "Autre";

$WBS_LABEL_190 = "Titre tournoi";
$WBS_LABEL_191 = "Nom Prénom";
$WBS_LABEL_192 = "Nom equipe";
$WBS_LABEL_193 = "Status membre";
$WBS_LABEL_194 = "Logo badge";
$WBS_LABEL_195 = "Photo membre";
$WBS_LABEL_196 = "Logo sponsor";
$WBS_LABEL_197 = "Bande couleur";
$WBS_LABEL_198 = "Code barre";
$WBS_LABEL_199 = "Logo équipe";
$WBS_LABEL_200 = "NOC";
$WBS_LABEL_201 = "Valeur fixe";
$WBS_LABEL_202 = "Prénom";
$WBS_LABEL_203 = "Nom";
$WBS_LABEL_204 = "Pseudo équipe";
$WBS_LABEL_205 = "Zone";

$WBS_LABEL_220 = "1";
$WBS_LABEL_221 = "2";
$WBS_LABEL_222 = "3";
$WBS_LABEL_223 = "4";
$WBS_LABEL_224 = "5";
$WBS_LABEL_225 = "6";
$WBS_LABEL_226 = "7";
$WBS_LABEL_227 = "8";
$WBS_LABEL_228 = "9";
$WBS_LABEL_229 = "10";
$WBS_LABEL_230 = "11";
$WBS_LABEL_231 = "12";
$WBS_LABEL_232 = "13";
$WBS_LABEL_233 = "14";
$WBS_LABEL_234 = "15";
$WBS_LABEL_235 = "16";
$WBS_LABEL_236 = "3/4";
$WBS_LABEL_237 = "5/8";
$WBS_LABEL_238 = "9/16";
$WBS_LABEL_239 = "Q1";
$WBS_LABEL_240 = "Q2";
$WBS_LABEL_241 = "Q3";
$WBS_LABEL_242 = "Q4";
$WBS_LABEL_243 = "Q5";
$WBS_LABEL_244 = "Q6";
$WBS_LABEL_245 = "Q7";
$WBS_LABEL_246 = "Q8";
$WBS_LABEL_247 = "Q9";
$WBS_LABEL_249 = "";

$WBS_LABEL_260 = 'Vainqueur';
$WBS_LABEL_261 = 'Finale';
$WBS_LABEL_262 = 'Demi-finale';
$WBS_LABEL_263 = 'Quart';
$WBS_LABEL_264 = 'Huitième';
$WBS_LABEL_265 = 'Seizième';
$WBS_LABEL_266 = '1/32';
$WBS_LABEL_267 = '1/64';
$WBS_LABEL_268 = 'Tour 1';
$WBS_LABEL_269 = 'Tour 2';
$WBS_LABEL_270 = 'Tour 3';

$WBS_LABEL_280 = 'Poule';
$WBS_LABEL_281 = 'Qualifications';
$WBS_LABEL_282 = 'Tableau principal'; 
$WBS_LABEL_283 = 'Troisième place';
$WBS_LABEL_284 = 'Consolante';
$WBS_LABEL_285 = 'Plateau';

$WBS_LABEL_290 = 'Arbitre';
$WBS_LABEL_291 = 'Service';
$WBS_LABEL_292 = 'Repos'; 

$WBS_LABEL_301 = 'U11';
$WBS_LABEL_302 = 'U13';
$WBS_LABEL_303 = 'U15'; 
$WBS_LABEL_304 = 'U17'; 
$WBS_LABEL_305 = 'U19'; 
$WBS_LABEL_306 = 'Sénior'; 
$WBS_LABEL_307 = 'Vétéran'; 

$WBS_LABEL_320 = 'France ancien'; 
$WBS_LABEL_321 = 'France actuel'; 
$WBS_LABEL_322 = 'Luxembourg'; 
$WBS_LABEL_323 = 'Squash'; 

$WBS_LABEL_330 = 'Aucun'; 
$WBS_LABEL_331 = '3x15'; 
$WBS_LABEL_332 = '5x7'; 
$WBS_LABEL_333 = '3x21'; 
$WBS_LABEL_334 = '1x5'; 
$WBS_LABEL_335 = '2 jeux gagnants'; 
$WBS_LABEL_336 = '3 jeux gagnants'; 

$WBS_LABEL_340 = 'Chambre simple'; 
$WBS_LABEL_341 = 'Chambre double'; 
$WBS_LABEL_342 = 'Chambre triple'; 
$WBS_LABEL_343 = 'Chambre autre'; 
$WBS_LABEL_345 = 'Tarif semaine'; 
$WBS_LABEL_346 = 'Tarif week-end'; 

$WBS_LABEL_350 = 'Aucun'; 
$WBS_LABEL_351 = 'Simple'; 
$WBS_LABEL_352 = 'Double'; 
$WBS_LABEL_353 = 'Véteran autorisé'; 
$WBS_LABEL_354 = 'Exceptionnel'; 
$WBS_LABEL_355 = 'Poussin'; 

$WBS_LABEL_370 = 'Incomplète'; 
$WBS_LABEL_371 = 'Inscrite'; 
$WBS_LABEL_372 = 'Composée'; 

$WBS_LABEL_STRING_PLACE   = " place";
$WBS_LABEL_STRING_PLACES  = " places";
$WBS_LABEL_STRING_GROUP   = " poule";
$WBS_LABEL_STRING_GROUPS  = " poules";
$WBS_LABEL_STRING_QUALIF  = " qualifié";
$WBS_LABEL_STRING_QUALIFS = " qualifiés";
$WBS_LABEL_STRING_BYE     = " vacant";

$WBS_SMA_LABEL_1 = "SH";
$WBS_SMA_LABEL_2 = "SD";
$WBS_SMA_LABEL_3 = "DH";
$WBS_SMA_LABEL_4 = "DD";
$WBS_SMA_LABEL_5 = "Mx";
$WBS_SMA_LABEL_6 = "Mr.";
$WBS_SMA_LABEL_7 = "Mme.";

$WBS_SMA_LABEL_10 = "Poule";
$WBS_SMA_LABEL_11 = "Qualification";
$WBS_SMA_LABEL_12 = "Plateau principal";
$WBS_SMA_LABEL_13 = "Equipe";
$WBS_SMA_LABEL_14 = "Ronde suisse";
$WBS_SMA_LABEL_15 = "Poule";
$WBS_SMA_LABEL_16 = "Poule A/R";
$WBS_SMA_LABEL_17 = "KO";

$WBS_SMA_LABEL_89 = "DNS";
$WBS_SMA_LABEL_90 = "M";
$WBS_SMA_LABEL_91 = "Q";
$WBS_SMA_LABEL_92 = "R";
$WBS_SMA_LABEL_93 = "PTQ";
$WBS_SMA_LABEL_94 = "PFR";
$WBS_SMA_LABEL_95 = "PMD";
$WBS_SMA_LABEL_96 = "PFQ";
$WBS_SMA_LABEL_97 = "WDN";
$WBS_SMA_LABEL_98 = "INJ";
$WBS_SMA_LABEL_99 = "----";

$WBS_SMA_LABEL_160 = "O";
$WBS_SMA_LABEL_161 = "N";

$WBS_SMA_LABEL_260 = 'Vainqueur';
$WBS_SMA_LABEL_261 = 'Finale';
$WBS_SMA_LABEL_262 = '1/2';
$WBS_SMA_LABEL_263 = '1/4';
$WBS_SMA_LABEL_264 = '1/8';
$WBS_SMA_LABEL_265 = '1/16';
$WBS_SMA_LABEL_266 = '1/32';
$WBS_SMA_LABEL_267 = '1/64';
$WBS_SMA_LABEL_268 = 'Tour 1';
$WBS_SMA_LABEL_269 = 'Tour 2';
$WBS_SMA_LABEL_270 = 'Tour 3';

$WBS_SMA_LABEL_280 = '';
$WBS_SMA_LABEL_281 = 'Q';
$WBS_SMA_LABEL_282 = 'F'; 
$WBS_SMA_LABEL_283 = 'f';
$WBS_SMA_LABEL_284 = 'C';
$WBS_SMA_LABEL_285 = 'P';

$WBS_SMA_LABEL_301 = 'U11';
$WBS_SMA_LABEL_302 = 'U13';
$WBS_SMA_LABEL_303 = 'U15'; 
$WBS_SMA_LABEL_304 = 'U17'; 
$WBS_SMA_LABEL_305 = 'U19'; 
$WBS_SMA_LABEL_306 = 'Sen'; 
$WBS_SMA_LABEL_307 = 'Vét'; 

$WBS_SMA_LABEL_340 = 'S'; 
$WBS_SMA_LABEL_341 = 'TW'; 
$WBS_SMA_LABEL_342 = 'TR'; 
$WBS_SMA_LABEL_343 = 'AU'; 
$WBS_SMA_LABEL_345 = 'Semaine'; 
$WBS_SMA_LABEL_346 = 'WE'; 

$WBS_SMA_LABEL_350 = 'Aucun'; 
$WBS_SMA_LABEL_351 = 'S'; 
$WBS_SMA_LABEL_352 = 'D'; 
$WBS_SMA_LABEL_353 = 'VA'; 
$WBS_SMA_LABEL_354 = 'SE'; 
$WBS_SMA_LABEL_355 = 'SP'; 

?>
