<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$draws       = "Tableaux";

// Sous menu
$itPairs     = "Joueurs/paires";
$itGroup     = "Poules";
$itMainDraw  = "Tableaux";
$itPdf       = "Document Pdf";

// Titre des colonnes
$rowsPairs1  = "NOM Prénom";
$rowsPairs2  = "Niveau";
$rowsPairs3  = "Points";
$rowsPairs4  = "Rang int.";
$rowsPairs5  = "Rang nat.";
$rowsPairs6  = "Phase";
$rowsPairs7  = "Evol";
$rowsPairs8  = "Tds";
$rowsPairs9  = "Equipe";

// Messages
$msgNoDraw       = "Aucun tableau disponible.";
$msgNoPublic     = "Tableau non disponible.";
$msgNoPlayers    = "Les joueurs/paire du tableau ne sont pas disponible.";
$msgNoAvailable  = "Le tableau demandé n'est pas disponible.";

?>