<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/t_user.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$email = "Envoyer un email";

// Titre  des fenetres
$femail = "Contacter un administrateur";

// Titre  des cartouches
$tAdminList   = "Contacts";
$tUsersStat   = "Membres";
$tEventsStat  = "Tournois";
$tVisitsStat  = "Visites";

// Label des zones
$from    = "De :";
$fromEmail = "Votre email :";
$to      = "à :";
$subject = "Sujet :";
$message = "Message :";
$Home    = "Retour accueil";

// Label des boutons
$btnMail    = "Envoyer";
$btnConnect = "Connecter";
$btnNew     = "Nouveau compte";
$btnLoose  = "Mot de passe ou login perdu ?";

// Label des message
$msgfrom       = "Veuillez vous identifier.";
$msgfromEmail  = "Votre adresse email est obligatoire.";
$msgsubject    = "Veuillez présiser le sujet.";
$msgnoValidEmail = "Votre adresse email est non valide.";
$msgmessage      = "Ecrivez ce que vous avez à dire!!!";
$msgSend         = "Votre message a été envoyé avec succés.";


?>