<?php

include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$events = "Tournoi";

// Sous menus
$itPractical = "Carte de visite";
$itSubscribe = "Abonnement";
$itContacts  = "Contacts";
$itStats     = "Statistiques";

// Titres
$tCompetStat   = "Compétition";
$tVisitsStat   = "Visiteurs";
$tNews         = "Brèves";
$tInfoGene     = "Informations générales";
$tDirectAccess = "Accès rapide";
$tLineRegi     = "Inscriptions en ligne";

// Label des zones
$evntDate       = "Date";
$evntPlace      = "Lieu";
$evntOrganizer  = "Organisateurs";
$evntDeadline   = "Fin d'inscription";
$evntDatedraw   = "Tirage au sort";
$evntUrl        = "Site officiel";

$playersList = 'Fiche joueur';
$teamsList   = 'Fiche club';

$nbTeams      = "Equipes";
$nbPlayers    = "Joueurs";
$nbMatchs     = "Matchs";
$nbVisite     = "Visites";
$nbSubscribe  = "Abonnés";

$login = "Identifiant";
$pwd   = "Mot de passe";


$from      = "De :";
$fromEmail = "Email :";
$to        = "à :";
$subject   = "Objet :";
$message   = "Message :";

$email        = "Email";
$news         = "Recevoir les news";

// Colonnes
$rowsTeams1  = "Equipe";
$rowsTeams2  = "Sigle";

$rowsEvents1 = "Nom";
$rowsEvents2 = "Date";
$rowsEvents3 = "Visites";

// Messages
$msgSubscription = "Sélectionnez les équipes, renseignez l'adresse email puis abonnez-vous. Vous recevrez un email pour chaque résultat des équipes choisies.";
$msgNoContact  = "Désolé, il n'y a aucun contact pour ce tournoi.";
$msgfromEmail  = "Renseigner votre adresse email. Vous recevrez une copie du courrier.";
$msgsubject    = "L'objet est obligatoire";
$msgmessage    = "Si vous n'avez rien a dire, pas besoin d'envoyer un email.";
$msgNoTeams    = "Aucun abonnement possible pour l'instant.";

$msgNoAccess   = "Si vous n'avez pas encore de compte, ";
$CIci          = "aller ici"; 

// Boutons
$btnSubscribe   = "S'abonner";
$btnUnsubscribe = "Se desabonner";
$btnInfo        = "Information";
$btnMail        = "Envoyer";
$btnLogin       = "Valider";

?>