<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$line    = "Inscriptions";

$itValid = "Valider";

// Titres des fenetres


// titre des blocs
$blkPrint    = "Impression rapide";
$tData       = "Correspondant";
$tCount      = "Compte";

// Titre des colonnes
$rowsPostits1  = "Type";
$rowsPostits2  = "Message";


$rowsSubmited1  = "Nom du club";
$rowsSubmited2  = "Sigle";
$rowsSubmited3  = "Nb joueurs";
$rowsSubmited4  = "Soumis le";

$rowsAccepted1  = "Nom du club";
$rowsAccepted2  = "Sigle";
$rowsAccepted3  = "Nb joueurs";
$rowsAccepted4  = "Soumis le";
$rowsAccepted5  = "Accepté le";

$rowsPlayers1  = "Genre";
$rowsPlayers2  = "Nom";
$rowsPlayers3  = "Prénom";
$rowsPlayers4  = "Catégorie";
$rowsPlayers5  = "Surclassement";
$rowsPlayers6  = "Niveau";
$rowsPlayers7  = "Simple";
$rowsPlayers8  = "Double";
$rowsPlayers9  = "Partenaire";
$rowsPlayers10 = "Mixte";
$rowsPlayers11 = "Partenaire";


$rowsRegiSubmited1  = "Proposée le";
$rowsRegiSubmited2  = "Nom";
$rowsRegiSubmited3  = "Prénom";
$rowsRegiSubmited4  = "Niveau";
$rowsRegiSubmited5  = "Simple";
$rowsRegiSubmited6  = "Double";
$rowsRegiSubmited7  = "Partenaire";
$rowsRegiSubmited8  = "Mixte";
$rowsRegiSubmited9  = "Partenaire";
$rowsRegiSubmited10 = "Prix";

$rowsRegiAccepted1  = "Proposé le";
$rowsRegiAccepted2  = "Accepté le";
$rowsRegiAccepted3  = "Nom";
$rowsRegiAccepted4  = "Prénom";
$rowsRegiAccepted5  = "Niveau";
$rowsRegiAccepted6  = "Simple";
$rowsRegiAccepted7  = "Double";
$rowsRegiAccepted8  = "Partenaire";
$rowsRegiAccepted9  = "Mixte";
$rowsRegiAccepted10 = "Partenaire";
$rowsRegiAccepted11 = "Prix";


// Label des zones
$lineIdentity = "Identité :";
$lineRue      = "Voie :";
$lineLieu     = "Lieu :";
$lineVille    = "Commune :";
$lineEmail    = "Email :";
$lineFixe     = "Tel fixe :";
$lineMobile   = "Mobile :";
$lineUsername = "Propriétaire :";
$lineUserpseudo = "Pseudo :";
$lineUseremail  = "Email :";

// Messages d'erreur 
$msgnosubmitedteams = "Pas de nouveau club inscrit.";
$msgnoacceptedteams = "Pas de club accepté.";

$msgProblems = "Problèmes détectés.<br>Modifier les inscriptions puis valider à nouveau ou supprimer les messages pour forcer la validation.<br>Un email sera automatiquement envoyé lorsqu'il n'y aura plus de message.";
$msgReceived = "Inscriptions reçues à valider";
$msgValidated = "Inscriptions acceptées";
$msgPlayers   = "Joueurs enregistrés";

?>
