<?php

include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$live    = "En direct";

// Sous menus
$itList      = "Matches";
$itLive      = "En direct";
$itStream    = "Vidéo";
$itLast      = "Récents";

// Titre des colonnes
$rowsMatchesV1  = "Tableau";
$rowsMatchesV2  = "Phase";
$rowsMatchesV3  = "Tour";
$rowsMatchesV4  = "Joueur/Paire A";
$rowsMatchesV5  = "Joueur/Paire B";
$rowsMatchesV6  = "Court";
$rowsMatchesV7  = "Début";

$rowsMatchs4  = "Etat";
$rowsMatchs5  = "Court";
$rowsMatchs6  = "Score";
$rowsMatchs7  = "Début";
$rowsMatchs8  = "Fin";
$rowsMatchs9  = "Durée";

$rowsResults1  = $rowsMatchesV1;
$rowsResults2  = $rowsMatchesV2;
$rowsResults3  = $rowsMatchesV3;
$rowsResults4  = $rowsMatchesV4;
$rowsResults5  = $rowsMatchesV5;
$rowsResults6  = "Score";
$rowsResults7  = "Début";
$rowsResults8  = "Fin";
$rowsResults9  = "Durée";


// Messages
$msgNoTies    = "Pas de match aujourd'hui. Consultez le calendrier.";
$msgNoLiveNow = "Aucun match en cours. Revenez plus tard";
$msgOnlyIE  = "Vous utilisez un navigateur IE !? Pas de chance, il n'y a pas de plugin disponible. Pour regarder les macthes en direct, installez et utilisez VCL.";
$msgVLC    = "Pour regardez les matchs en direct, installez VLC avec le plugin pour Firefox.";
$msgLink   = "Si le plugin ne fonctionne pas correctement, utilisez directement VLC avec l'adresse ci-dessous.";
$msgNoStream = "Pas de video en direct pour ce tournoi.";

?>
