<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";
include dirname(__FILE__)."/t_mber.inc";

// Titre  du navigateur
$mber      = "Etat civil";

// Titres des fenetres
$itAllMembers = "Tous les inscrits";
$itOthers      = "Autres inscrits";
$itArrivals    = "Arrivées";
$itDepartures  = "Départs";
$tNewMember    = "Création d'un membre";
$tEditMember   = "Modification d'un membre";
$tMembers     = "Tous les inscrits";
$tPlayers     = "Joueurs inscrits";
$tOfficials   = "Officiels inscrits";
$tOthers      = "Autres inscrits";
$tPurchases   = "Liste des achats";
$tAccount     = "Changement de compte";
$tCredits     = "Liste des provisions";
$tArrivals    = "Liste des arrivées";
$tDepartures  = "Liste des départs";

// Titre des colonnes
$rowsMembers1  = "Genre";
$rowsMembers2  = "Prénom";
$rowsMembers3  = "Nom";
$rowsMembers4  = "Né(e) le";
$rowsMembers5  = "Numéro IBF";
$rowsMembers6  = "Licence";
$rowsMembers6  = "Commentaire";

$rowsDeparr1  = "Genre";
$rowsDeparr2  = "Identité";
$rowsDeparr3  = "Equipe";
$rowsDeparr4  = "Fonction";
$rowsDeparr5  = "Heure";
$rowsDeparr6  = "Lieu";
$rowsDeparr7  = "Hotel";
$rowsDeparr8  = "Prise en charge";


// Label des zones
$regiAccount = "Compte :";
$regiTeam    = "Club/Equipe :";
$regiName    = "Inscrit :";
$regiId      = $regiName;
$accountName = "Compte actuel :";
$accountId = "Nouveau compte :";
$regiArrival    = "Arrivée (jj-mm-aa hh:mm):";
$regiArrcmt     = "Lieu d'arrivée :";
$regiDeparture  = "Départ (jj-mm-aa hh:mm):";
$regiDepcmt     = "Lieu de départ :";
$regiPrise      = "Prise en charge (hh:mm):";
$regiTransportcmt     = "Commentaire transport :";
$propagate      = "Mettre à jour arrivée et départ de tous les inscrits du club";

// Label des listes

// Messages d'erreur
$msgNoMembers = "Pas d'incrit dans cette catégorie.";

// Label des boutons

?>
