<?php

include dirname(__FILE__)."/badnet_V.inc";

// Menu general
$itGeneral   = "Informations";
$itRegister  = "Inscriptions";
$itDraws     = "Tableaux";
$itCalendar  = "Calendrier";
$itResults   = "Résultats";
$itRanking   = "Classements";
$itToday     = "Aujourd'hui";
$itEvent     = "Tournois";

// Sous menu
$itTeams     = "Equipes";
$itPlayers   = "Joueurs";
$itOfficials = "Officiels";

// Temporaire pour les invites
$itExit      = "Deconnexion";
$itEvents    = "Tournois";
$itPref      = "Préférences";
$itHome      = "Accueil";
$tUsersStat  = "Statistiques";
$nbUser      = "Membres :";
$lastUser    = "Dernier :";
$tEventsStat = "Tournois";
$nbEvents    = "Nombre :";
$nbAnonymousVisit   = "Visiteurs :";
$nbUsersVisit  = "Membres :";
$nbAdminVisit= "Gestionnaires :";

$lgdVisitor = "&nbsp;Visiteur";
$lgdUser    = "&nbsp;Utilisateur";
$lgdGuest   = "&nbsp;Invité";
$lgdFriend  = "&nbsp;Ami";
$lgdAssist  = "&nbsp;Assistant";
$lgdAdmin   = "&nbsp;Administrateur";
$lgdManager = "&nbsp;Gestionnaire";

$lgdConfident = "&nbsp;Confidentiel";
$lgdPrivate   = "&nbsp;Privé";
$lgdPublic    = "&nbsp;Public";
$lgdDelete   = "&nbsp;Effacée";

?>