<?php

$itReload  = "Actualiser";
$itNew     = "Nouveau";
$itDelete  = "Effacer";
$itRestore = "Restaurer";
$itErase   = "Supprimer";
$itMerge   = "Fusionner";

$itBadge   = "Badges PDF";
$itSearch  = "Chercher";
$itExit    = "Deconnexion";
$itClose   = "Fermeture";
$itMail    = "Mail";
$itHome    = "Accueil";
$itNone    = "&nbsp;";

$itPref    = "Préférences";
$itUsers   = "Utilisateurs";
$itEvents  = "Tournois";
$itBooks   = "Carnet d'adresses";
$itAdmi    = "Parametrage";
$itMaint   = "Maintenance";
$itPhpInfo = "Php info";
$itHelp    = "Aide";
$itSubs    = "Abonnement";

$itAttribs = "Parametres";
$itGeneral = "Pratique";
$itClubs   = "Pays & Clubs";
$itLine    = "A valider";
$itTeams   = "Equipes";
$itPlayers = "Joueurs";
$itRegister = "Inscriptions";
$itOfficials = "Officiels";
$itOthers    = "Autres";
$itDraws     = "Tableaux";
$itProgram   = "Programme";
$itCalendar  = "Calendrier";
$itDivisions = "Divisions";
$itResults   = "Résultats";
$itRanking   = "Classements";
$itSchedule  = "Horaires";
$itManage    = "Déroulement";
$itTies      = "Rencontres";
$itTransfert = "Import/Export";

$itSport     = "Sportif";
$itAdmin     = "Administratif";
$itEntries   = "Inscrits";
$itAccomodation = "Hébergement";
$itTransport    = "Transport";

$itItems     = "Articles";
$itAccounts  = "Comptes";
$itPurchases = "Achats";
$itToday     = "Aujourd'hui";
$itEvent     = "Autres tournois";
$itPrint     = "Imprimer";
$itBadges    = "Badges";

$itConfident = "Confidentiel";
$itPrivate   = "Privée";
$itPublic    = "Public";

$itEdit          = "Modifications";
$itAutorisations = "Autorisations";
$itPublication   = "Publication";

$itGroup    = "Poules";
$itMainDraw = "Plateaux";


$itSH = "SH";
$itSD = "SD";
$itDH = "DH";
$itDD = "DD";
$itMX = "MX";
$itInscrits = "Liste des inscrits";


?>
