<?php

include "menu.inc";
include "badnet.inc";

// Titres des fenetres
$tDraws    = "Gestion des tableaux";


// Titre des colonnes
$rowsEvents2  = "Nom";
$rowsEvents3  = "Date";
$rowsEvents4  = "Lieu";
$rowsEvents5  = "Organisateur";
$rowsEvents6  = "Commentaire";
$rowsEvents7  = "Propriétaire";


// Label des zones


// Label des listes


// Messages d'erreur
$msgRegistered  = "Les changements ont été enregistrés";

// Label des boutons
$End       = "Fermer";
$Cancel    = "Abandonner";
$Validate  = "Valider";
$Register  = "Enregistrer";
$AddUser    = "Ajouter un utilisateur";
$RemoveUser = "Enlever un utilisateur";


?>