<?php

$PDF_GENERATED = "Généré le ";

// Titre pour la feuille de résultats

$PDF_DATE = "Date";
$PDF_LIEU = "Lieu";

$PDF_ORDRE = "Ordre";
$PDF_TERRAIN = "Terrain";

$PDF_MATCHES = "Matches";

$PDF_TEAMA = "Equipe A";
$PDF_TEAMB = "Equipe B";
$PDF_SCORES = "Scores";
$PDF_VICTORIES = "Victoires";
$PDF_LOSTS = "Défaites";
$PDF_AVERAGE = "Différence";
$PDF_PENALTIES = "Pénalité";

$PDF_VICTOIRES = "Victoires";
$PDF_SETS = "Sets";
$PDF_POINTS = "Points";

$PDF_VAINQUEUR = "VAINQUEUR";
$PDF_SCORE = "SCORE";
$PDF_TOTAUX ="TOTAUX";
$PDF_MATCH_NUL = "EGALITE";

// Titre pour les declaration d'equipes
$PDF_DAY  = "JOUR";
$PDF_TEAM_TIME = "HEURE";
$PDF_TIE  = "RENCONTRE";
$PDF_TEAM_DIVISION  = "PHASE";
$PDF_GROUP     = "POULE";
$PDF_STAGE     = "TOUR";
$PDF_TEAM_COURT     = "COURT N°";
$PDF_COMPO     = "COMPOSITION DE L'EQUIPE";
$PDF_DEPOSE  = "Déclaration à remettre au juge arbitre avant :";
$PDF_VERSUS  = " vs " ;

$PDF_MATCHES_ORDER = "Ordre des matches" ;
$PDF_DISCIPLINE = "Match" ;
$PDF_TEAM_COMPOSITION = "COMPOSITION DE L'EQUIPE" ;
$PDF_ORDER_PROPOSED = "Vous" ;
$PDF_ORDER_FINAL = "final" ;
$PDF_ORDER_OPPENENT = "adv.";
$PDF_NOM = "NOM" ;
$PDF_PRENOM = "Prenom" ;

$PDF_PRESENCE = "Feuille de présence";
$PDF_NAME = 'NOM Prénom';
$PDF_LICENSE = 'Licence';
$PDF_NATION = 'F/Ass/Etr';
$PDF_MUTE = 'Muté';
$PDF_PARAPH = 'Signature';
$PDF_COMMENT = 'Commentaire';

$PDF_SIGN_CAPTAIN = "Nom et Signature du Capitaine" ;
$PDF_HEURE_DEPOT = "Heure de dépot" ;
$PDF_REFEREE_OBSERVATIONS = "Observations du juge-arbitre" ;

// Titre pour le programme
$PDF_SCHEDULE  = "PROGRAMME";
$PDF_PROGRAM   = "PROGRAMME";
$PDF_PROTECT   = "Horaires donnés à  titre indicatif et susceptibles d'être modifiés";

// Titre pour les groupes
$PDF_GROUPS  = "COMPOSITION DES POULES";
$PDF_POULES  = "POULES";
$PDF_DEFGROUP_3 = "Sortant par poule de 3 :";
$PDF_DEFGROUP_4 = "Sortant par poule de 4 :";
$PDF_DEFGROUP_5 = "Sortant par poule de 5 :";
$PDF_DEFGROUP_SECOND = "Meilleur second :";
$PDF_DEFGROUP_TDS = "Tds";
$PDF_DEFGROUP_PLAYER = "NOM Prénom";
$PDF_DEFGROUP_CLUB   = "Club";
$PDF_DEFGROUP_LEVEL  = "Niveau";
$PDF_DEFGROUP_AVERAGE= "Moyenne";
$PDF_DEFGROUP_MATCHS = "Mtchs";
$PDF_DEFGROUP_GAMES  = "Sets";
$PDF_DEFGROUP_POINTS = "Pts";
$PDF_DEFGROUP_RANK   = "Rang";
$PDF_DEFGROUP_CLT    = "Clt";
$PDF_DEFGROUP_MATCHES= 'Matches';
$PDF_DEFGROUP_NUM    = '#';
$PDF_DEFGROUP_DAY    = 'Jour';
$PDF_DEFGROUP_HOUR   = 'Heure';
$PDF_DEFGROUP_VENUE  = 'Salle';
$PDF_DEFGROUP_MATCH  = 'Match';
$PDF_DEFGROUP_SCORE  = 'Score';
$PDF_DEFGROUP_VERSUS = 'contre';
$PDF_DEFGROUP_LICENCE = 'Licence';

// Titre pour la feuille de score
$PDF_DIVISION  = "Tour :" ;
$PDF_START     = "Debut :" ;
$PDF_UMPIRE    = "Arbitre :" ;
$PDF_EVENT     = "Tableau : " ;
$PDF_NUM       = "Match n°: " ;
$PDF_END_M       = "Fin :";
$PDF_COURT     = "Court # :";
$PDF_LENGTH_M    = "Durée :";
$PDF_DATE      = "Date : ";
$PDF_TIME      = "Time : ";
$PDF_SERVICE   = "Service :";
$PDF_UMP_SIGNATURE = "Signature arbitre :" ;
$PDF_REF_SIGNATURE = "Signature juge-arbitre :" ;

// Titre pour le classement d'un tableau
$PDF_RESULTS = "RESULTATS" ;
$PDF_RANKING = "CLASSEMENT" ;
$PDF_TEAM = "Equipe";

$PDF_RANK_COMMENTS  = " V : Victoires +  / D : Defaites / ";
$PDF_RANK_COMMENTS .= " M+ : Matches +  / M- : Matches - / MD : Matches Difference / ";
$PDF_RANK_COMMENTS .= " S+ : Sets + / S- : Sets - / SD : Sets Difference / ";
$PDF_RANK_COMMENTS .= " P+ : Points + / P- : Points - / PD : Points Difference ";

$PDF_RANG_LEG1 = 'P : Pénalités /  V : Victoires / E : Egalités / D : Defaites / M+ : Matches gagnes / M- : Matches perdus / MD : Matches difference';
$PDF_RANG_LEG11 = 'P : Pénalités /  V : Victoires / EV : Nul gagnant / ED : Nul perdant / D : Defaites / M+ : Matches gagnes / M- : Matches perdus / MD : Matches difference';
$PDF_RANG_LEG2 = 'G+ : Jeux gagnes / G- : Jeux perdus / GD : Jeux difference / P+ : Points gagnes / P- : Points perdus / PD : Points difference';
$PDF_SMALL_GAME = 'G';

$PDF_MONSIEUR = "Mr" ;
$PDF_MLLE = "Mlle" ;
$PDF_MADAME = "Mme" ;

// Titre pour les badges
$PDF_TYPE_JOUEUR = "Joueur" ;

// Titre pour les fiches d'activite arbitre
$PDF_TOTAL  = "Total" ;
$PDF_MATCH  = "Match" ;
$PDF_ROUND  = "Phase" ;
$PDF_STEP   = "Tour" ;
$PDF_BEGIN  = "Debut" ;
$PDF_END    = "Fin" ;
$PDF_LENGTH = "Duree" ;

$tEntriesStats = "Joueurs et paires";
$tMatchsStats  = "Nombre de matchs";

// Bas de page
$page     = "Page N°";
$generate = "Printed ";

// Titre des rapports
$tEntries     = 'Inscriptions';
$tPlayersClub = 'Liste des joueurs par club';
$tPairsClub   = 'Liste des paires par club';
$tPlayerList  = 'Liste des joueurs';
$tPalmares    = 'Palmares';
$tStaTours    = 'Répartition des matchs par tour';

// Titre de colonne des rapports
$cDraw     = 'Tableau';
$cStage    = 'Phase';
$cRound    = 'Tour';
$cResult   = 'Résultat';
$cOpponent = 'Adversaire';
$cScore    = 'Score';
$cLength   = 'Durée';
$cDate     = 'Date';
$cIdentity = 'Identité';
$cCost     = 'Coût';
$cPurchase = 'Achat';
$cDiscount = 'Remise';
$cPaid     = 'Payé';
$cBalance  = 'Solde';
$cLevel    = 'Niveau';
$cPairs    = 'Joueurs/paires';
$cPoints   = 'Points';
$cIntRank  = 'Rang int.';
$cNatRank  = 'Rang nat.';
$cRank     = 'Rang';
$cGender   = 'Genre';
$cEntrie   = 'Inscription';
$cNatNum   = 'Licence';
$cFirstMatch = 'Premier match';
$cConvocation = 'Convocation';
$cVenue      = 'Salle';
$cBorn     = 'Née le';
$cTeam     = 'Equipe';
$cNoc      = 'NOC';
$cHour     = 'Heure';
$cNum      = 'Num';
$cPairA    = 'Paire A';
$cPairB    = 'Paire B';
$cWinner   = 'Vainqueur';
$cSecond   = 'Second';
$cThird    = 'Troisième';
?>