<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$prefs      = "Préférences";

// Titres des fenetres

// Titres des blocs
$blkMail = "Email";

// Titre des colonnes
$rowsRanks ="Classement"; 
$rowsRanks1 ="Label"; 
$rowsRanks2 ="Point"; 
$rowsRanks3 ="Seuil"; 

// Label des zones
$host = "Serveur SMTP :";
$port = "Port de connexion :";
$username = "Nom :";
$password = "Mot de passe :";
$ffbaEmail = "Email FFBa :";
$ffbaUrl = "Url fiche joueurs nationaux :";
$ibfUrl = "Url fiche joueurs internationaux :";

// Label des listes

// Messages d'erreur

// Label des boutons
$btnUpdateMail = "Enregistrer";
$btnAddRank    = "Créer";
$btnDelRank    = "Supprimer";
?>
