<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$regi = "Inscriptions";

// Colonnes
$rowsAssos1 = "Noms";
$rowsAssos2 = "Pseudo";
$rowsAssos3 = "Web";

$rowsRegiV1 = "Qualité";
$rowsRegiV2 = "Nom Prénom";
$rowsRegiV3 = "Licence";
$rowsRegiV4 = "Equipe";
$rowsRegiV5 = "Classement";

$rowsTeams1  = "Nom";
$rowsTeams2  = "Sigle";
$rowsTeams3  = "Association";
$rowsTeams4  = "Capitaine";

$rowsOffiV1  = "Genre";
$rowsOffiV2  = "Nom";
$rowsOffiV3  = "Pays";


// Messages
$msgNoTeams              = "La liste des équipes n'est pas disponible.";
$msgNoRegisteredPlayer   = "La liste des joueurs n'est pas disponible.";
$msgNoRegisteredOfficial = "La liste des officiels n'est pas disponible.";

?>