<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre
$resu         = "Joueur";
$tCivil       = "Informations sportives";
$tInscription = "Inscription";

// Label des zones
$mberBorn       = "Né(e) le";
$mberLicence    = "Licence";
$mberIbfNumber  = "Numéro Ibf";
$mberAsso       = "Equipe";
$mberRank       = "Classement";
$mberCatage     = "Catégorie";
$mberCompet     = "Date d'autorisation";
$mberSurclasse  = "Surclassement";
$mberDateSurclasse  = "depuis";
$mberDraws      = "Tableaux";
$mberPartnerD   = "Double avec";
$mberPartnerM   = "Mixte avec";
$mberConvoc     = "Convocation";
$mberVenue      = "Salle";
$mberMatch      = "Prochain macth";

// Titre des colonnes
$rowsResuIndiv1 = "Phase";
$rowsResuIndiv2 = "Tour";
$rowsResuIndiv3 = "Adversaire(s)";
$rowsResuIndiv4 = "Résultat";
$rowsResuIndiv5 = "Score";
$rowsResuIndiv6 = "Durée";

$rowsResuV1 = "Date";
$rowsResuV2 = "Discipline<br />(Partenaire)";
$rowsResuV3 = "Adversaire(s)";
$rowsResuV4 = "Résultat";
$rowsResuV5 = "Score";

// Messages
$msgNoMatch = "Pas de match pour ce joueur";
$msgNoAutorisation  = "La fiche demandée n'est pas disponible.";


?>