<?php

include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$schedu     = "Calendrier";

// Menu
$itVenue = "Salles";
$itDraws = "Tableaux";
$itPdf = "Document Pdf";

// Messages d'erreur
$msgNoPlaces   = "Calendrier non disponible.";
$msgNoCalendar = "Calendrier non disponible.";
$msgNoDivs     = "Aucune division déclarée.";

// Label des boutons
$btnPdf     = "Calendrier PDF";

?>