<?php
/* Chaines de caractere pour les libelles des champs de la table 
des associations */

// Label des zones
$assoId         = "Identifiant :";
$assoName       = "Nom :";
$assoStamp      = "Sigle :";
$assoType       = "Type :";
$assoFedeId     = "Identifiant poona :";
$assoExternId   = "Identifiant experne :";
$assoCmt        = "Commentaire :";
$assoUrl        = "Site internet :";
$assoLogo       = "Logo :";
$assoNumber     = "Matricule :";
$assoDpt        = "Département :";
$assoPseudo     = "Ville :";
$assoNoc        = "Code Olympique (NOC) :";
$assoLockId     = "Verrouillée par :";

// Messages d'erreur
$msgassoName    = "Le nom est obligatoire.";
$msgassoStamp   = "Le sigle est obligatoire.";
$msgassoType    = "Choisissez une catégorie dans la liste.";
$msgassoPseudo  = "La ville est obligatoire.";
$msgassoNoc     = "Le code olympique est obligatoire.";


?>