<?php
/* Chaines de caractere pour les libelles des champs de la table draws */

$serialName    = "Nom de la série :";
$serial_ms     = "Simple Homme";
$serial_ls     = "Simple Dame";
$serial_md     = "Double Homme";
$serial_ld     = "Double Dame";
$serial_mx     = "Mixte";

$drawSerial = "Série :";
$drawName   = "Nom :";
$drawStamp  = "Sigle :";
$drawDisci  = "Discipline :";
$drawType   = "Type :";
$drawCatage = "Catégorie d'age :";
$drawNumcatage = "Numéro catégorie d'age :";
$drawRank   = "Classement maximum :";
$drawType   = "Type :";
$drawNbp3   = "Nombre de poules de 3 :";
$drawNbs3   = "Nombre de sortants :";
$drawNbp4   = "Nombre de poules de 4 :";
$drawNbs4   = "Nombre de sortants :";
$drawNbp5   = "Nombre de poules de 5 :";
$drawNbs5   = "Nombre de sortants :";
$drawNbsd   = "Nombre de second :";
$drawNbq    = "Nb places pour qualifiés :";
$drawNbplq  = "Nb joueurs en qualif :";
$drawNbpl   = "Nb joueurs tableau final :";
$drawNbcons = "Nb de consolante :";
$drawThirdI = "Petite finale :";
$drawThird  = "Petite finale";


$msgserialname   = "Le libellé est obligatoire !";

?>