<?php
/* Chaines de caractere pour les libelles des champs de la table event */
$evntName        = "Nom :";
$evntPlace       = "Lieu :";
$evntDate        = "Date :";
$evntOrganizer   = "Organisateur :";
$evntDatedraw    = "Tirage au sort le (jj-mm-aa) :";
$evntDeadline    = "Fin d'inscription le (jj-mm-aa) :";
$evntCmt         = "Commentaire :";
$evntDeadline    = "Inscription avant (jj-mm-aa) :";
$evntDrawdate    = "Tirage au sort (jj-mm-aa) :";
$evntNature      = "Type du tournoi :";
$evntLevel       = "Niveau du tournoi :";
$evntNumauto     = "Numéro d'autorisation :";
$evntUrl         = "Adresse du site officiel:";
$evntPoster      = "Affiche :";
$evntNbvisited   = "Nombre de visite :";
$evntId          = "Identifiant :";
$evntScoring     = "Type de score :";
$evntRanking     = "Type de classement :";
$evntNbDrawMax   = "Nb tableaux autorisés :";
$evntUrlRank     = "Url classement :";
$evntFirstday    = "Premier jour (jj-mm-aa) :";
$evntLastday     = "Dernier jour (jj-mm-aa) :";
$evntZone        = "Zone géographique :";
$evntOwnerId     = "Propriétaire :";
$evntSeason      = "Saison :";

$msgevntName   = "Le nom du tournoi est obligatoire !";


?>