<?php


/* Chaines de caractere pour les libelles des champs de la table 
des hotels */

// Label des zones
$hotelHotel      = "Nom :";
$hotelDescr      = "Description :";
$hotelCost       = "Cout :";
$hotelShortname  = "Raccourci :";


// Messages d'erreur
$msghotelHotel = "Le nom est obligatoire.";
$msghotelDescr = "La description est obligatoire.";
$msghotelCost  = "Le prix est obligatoire.";
$msghotelShortname = "Le raccourci est obligatoire.";





?>