<?php


/* Chaines de caractere pour les libelles des champs de la table 
des items */

// Label des zones
$itemName      = "Nom :";
$itemCode      = "Code :";
$itemRef       = "Référence :";
$itemCount     = "Quantité :";
$itemIsFollowed = "Suivre la consommation";
$itemIsCreditable = "Remisable";
$itemRubrikId   = "Rubrique :";
$itemValue      = "Valeur :";

$IS = "Simple :";
$ID = "Double :";
$IM = "Mixte :";
$I1 = "Un tableau :";
$I2 = "Deux tableaux :";
$I3 = "Trois tableaux :";

// Messages d'erreur
$msgitemName   = "Le nom est obligatoire.";
$msgitemValue  = "La valeur est obligatoire.";

?>