<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$mberSexe       = "Genre :";
$mberSexe1      = "Monsieur";
$mberSexe2      = "Madame, mademoiselle";
$mberFirstName  = "Prénom :";
$mberSecondName = "Nom :";
$mberBorn       = "Né(e) le :";
$mberIbfNumber  = "Numéro Ibf :";
$mberLicence    = "Licence :";
$mberCountryId  = "Pays :";
$mberId         = "Identifiant :";
$mberFedeId     = "Identifiant Poona :";
$mberExternId   = "Identifiant externe :";
$mberUrlPhoto   = "Url photo :";
$mberLockId     = "Verrouillé par :";


// Messages d'erreur
$msgmberSexe = "Choisissez le sexe du membre :-)";
$msgmberFirstName = "Le prénom est obligatoire.";
$msgmberSecondName = "Le nom est obligatoire.";

?>