<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$regiDate       = "Date d'inscription :";
$regiType       = "Type :";
$regiLongName   = "Nom (long) :";
$regiShortName  = "Nom (court) :";
$regiTeamId     = "Equipe :";
$regiTeamName   = "Equipe :";
$regiCmt        = "Commentaire :";
$regiFunction   = "Fonction :";
$regiNoc        = "NOC :";
$regiArrival    = "Arrivée :";
$regiArrCmt     = "Précision :";
$regiDeparture  = "Départ :";
$regiDepCmt     = "Précision :";
$regiCatage     = "Catégorie :";
$regiNumcatage  = "Numéro catégorie :";
$regiSurclasse  = "Surclassement :";
$regiDateSurclasse  = "Depuis le :";
$regiDateAuto   = "Compétiteur depuis :";
$regiDateWo     = "Date forfait :";

$regiStatus1    = "Titulaire";
$regiStatus2    = "Remplaçant";
$regiStatus3    = "Autre";

$regiType1 = "Juge arbitre";
$regiType2 = "JA adjoint";
$regiType3 = "Arbitre";
$regiType4 = "Juge de lignes";
$regiType5 = "Délégué fédéral";
$regiType6 = "Conseiller d'arbitrage";

$regiAccountId1 = "Compte de l'equipe";
$regiAccountId2 = "Compte personnel";

$regiRest = "Repos depuis (jj-mm-aa hh:mm) :";
$regiDelay = "Absent jusqu'à (jj-mm-aa hh:mm) :";
$regiPresent = "Présent dans la salle :";
$regiWo = "Forfait :";
$regiUmpire = "Arbitre terrain :";
$regiPlay = "Joue terrain :";
$regiCourt = "Occupé terrain :";

// Messages d'erreur
$msgregiTeamId = "Une équipe est obligatoire.";


?>