<?php
/* Chaines de caractere pour les libelles des champs de la table 
des equipes */

// Label des zones
$teamDate       = "Date d'inscription :";
$teamName       = "Nom :";
$teamStamp      = "Sigle :";
$teamCaptain    = "Capitaine :";
$teamCmt        = "Commentaire :";
$teamClub       = "Club :";
$teamUrl        = "Site internet :";
$teamNoc        = "Code olympique (NOC) :";
$assoId         = "Club :";
$teamAssoId     = "Club :";

// Messages d'erreur
$msgteamName  = "Le nom est obligatoire.";
$msgteamStamp = "Le sigle est obligatoire.";
$msgteamDate  = "La date d'inscription est obligatoire.";
$msgteamAssoId  = "Le club est oligatoire.";

?>