<?php
/* Chaines de caractere pour les libelles des champs de la table user */

$userName   = "Nom usuel :";
$userLogin  = "Login :";
$userPseudo = "Pseudonyme :";
$userPass   = "Mot de passe :";
$userLang   = "Langue :";
$userEmail  = "Email :";
$userCmt    = "Commentaire :";
$userId     = "Identifiant :";
$userLastvisit = "Derniere visite :";
$userNbcnx     = "Nb connexions :";
$userSkin      = "Décoration :";

$msguserName   = "Le nom est obligatoire !";
$msguserPseudo = "Le pseudonyme est obligatoire !";
$msguserLogin  = "Le login est obligatoire !";
$msguserPass   = "Le mot de passe est obligatoire !";

?>