<?php
include dirname(__FILE__)."/menu_V.inc";
include dirname(__FILE__)."/t_teams.inc";

// Titre  du navigateur
$teams  = "Equipes";

// Actions
$itConvocsPdf  = "Document Pdf";

// Label des zones
$assoPseudo     = "Pseudonyme :";
$assoStamp      = "Sigle :";
$assoUrl        = "Site internet :";
$assoNoc        = "Pays (NOC) :";

// Titre des colonnes
$rowsPairs_V1 = "Joueurs/Paires";
$rowsPairs_V2 = "Tableau";
$rowsPairs_V3 = "Rang int.";
$rowsPairs_V4 = "Rang nat.";
$rowsPairs_V5 = "Niveau";
$rowsPairs_V6 = "Points";

$rowsPlayers1 = "Genre";
$rowsPlayers2 = "Nom Prénom";
$rowsPlayers3 = "Tableaux";
$rowsPlayers4 = "Premier match";
$rowsPlayers5 = "Convocation";
$rowsPlayers6 = "Salle";

$rowsRegis1 = "Genre";
$rowsRegis2 = "NOM Prénom";
$rowsRegis3 = "Licence";
$rowsRegis4 = "IBF";
$rowsRegis5 = "Niveau";
$rowsRegis6 = "Inscription";
$rowsRegis7 = "Premier match";
$rowsRegis8 = "Convocation";
$rowsRegis9 = "Salle";

$rowsTies1  = "Lieu";
$rowsTies2  = "Date";
$rowsTies3  = "Tour";
$rowsTies4  = "Adversaire";
$rowsTies5  = "Résultat";
$rowsTies6  = "Score";

$rowsPlayers_V1 = "Genre";
$rowsPlayers_V2 = "NOM Prénom";
$rowsPlayers_V3 = "Licence";
$rowsPlayers_V4 = "Classement";
$rowsPlayers_V5 = "Rang";

// Messages
$msgConvocation    = "Le premier match d'un joueur est 30 minutes aprés l'heure de convocation";
$msgNoPlayers      = "La liste des joueurs n'est pas diponible.";
$msgNoAutorisation = "Cette équipe n'est pas disponible.";
$msgNoTies         = "La liste des rencontres n'est pas disponible.";

?>