<?php

include dirname(__FILE__)."/t_user.inc";
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$users    = "Utilisateurs";

// Titres des fenetres
$tInfos = "Vos données";
$tEntries = "Vos inscriptions";
$tArchived = "Tournois archivés";
$tTeam     = "Tournois par équipe";
$tIndividual = "Tournois individuels";
$tManager    = "Gestion";


// Messages 
$msgEntries  = "Voici les tournois auxquel le club a participé. Vous pouvez consulter toutes les données relatives à ses joueurs.";
$msgManager  = "Vous êtes gestionnaire de ces tournois. Vous pouvez les modifier et donner des droits à d'autres membres.";
$msgAssist   = "Vous êtes assistant de ces tournois. Vous pouvez saisir les résultats.";
$msgNoFriendEvents  = "Aucun tournoi.";
$msgNoManageEvents  = "Aucun tournoi.";
$msgNoAssistEvents  = "Aucun tournoi.";
$msgNoFriendAsso    = "Pas de club";
// Boutons
$btnUser =  "Modifier";
$btnPwd  =  "Mot de passe";

$rowsEvent1 = "Saison";
$rowsEvent2 = "Tournoi";
$rowsAssist1 = $rowsEvent1;
$rowsAssist2 = $rowsEvent2;


?>