<?php
/*****************************************************************************
!   Module    :  Events
!   File       : $Source: /cvsroot/aotb/badnet/src/events/events.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.9 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/30 20:31:09 $
!   Mailto     : cage@free.fr
******************************************************************************/
define("EVNT_UPDATE_NEW",    WBS_ACT_EVENTS+1);
define("EVNT_EDIT_NEW",      WBS_ACT_EVENTS+2);
define("EVNT_ADD_NEW",       WBS_ACT_EVENTS+3);

define("EVNT_ADD_RIGHT",      WBS_ACT_EVENTS+4);
define("EVNT_EDIT_RIGHT",     WBS_ACT_EVENTS+5);
define("EVNT_UPDATE_RIGHT",   WBS_ACT_EVENTS+6);

define("EVNT_SECTOR_ADMI",    WBS_ACT_EVENTS+7);
define("EVNT_SECTOR_SPORT",   WBS_ACT_EVENTS+8);

define("EVNT_CONFIRM_RIGHTS",  WBS_ACT_EVENTS+9);
define("EVNT_DELETE_NEWS",     WBS_ACT_EVENTS+10);
define("EVNT_DELETE_RIGHTS",   WBS_ACT_EVENTS+11);
define("EVNT_CONFIRM_NEWS",    WBS_ACT_EVENTS+12);

define("EVNT_PRINT_OPTIONS",       WBS_ACT_EVENTS+13);
define("EVNT_EDIT_PRINTOPTIONS",   WBS_ACT_EVENTS+14);
define("EVNT_UPDATE_PRINTOPTIONS", WBS_ACT_EVENTS+15);

define("EVNT_SELECT_IMAGE",    WBS_ACT_EVENTS+16);
define("EVNT_SELECT_POSTER",   WBS_ACT_EVENTS+17);
define("EVNT_SELECT_LOGO",     WBS_ACT_EVENTS+18);
define("EVNT_SELECT_BADGE",    WBS_ACT_EVENTS+19);
define("EVNT_SELECT_SPON",     WBS_ACT_EVENTS+20);

define("EVNT_STATS",     WBS_ACT_EVENTS+21);
define("EVNT_CONTACTS",  WBS_ACT_EVENTS+22);
define("EVNT_SUBSCRIBE", WBS_ACT_EVENTS+23);

define("EVNT_SEND_EMAIL",  WBS_ACT_EVENTS+24);
define("EVNT_FEES",        WBS_ACT_EVENTS+25);
define("EVNT_UPDATE_FEES", WBS_ACT_EVENTS+26);


define("EVNT_NEWS", WBS_ACT_EVENTS+27);
define("EVNT_RIGHTS", WBS_ACT_EVENTS+28);

define("EVNT_EMPTY", WBS_ACT_EVENTS+29);

define("EVNT_MAIN",        WBS_ACT_EVENTS+30);
define("EVNT_EDIT_POSTIT", WBS_ACT_EVENTS+31);
define("EVNT_UPDT_POSTIT", WBS_ACT_EVENTS+32);
define("EVNT_CTL_POSTIT",  WBS_ACT_EVENTS+33);
define("EVNT_DEL_POSTIT",  WBS_ACT_EVENTS+34);
define("EVNT_NEW_POSTIT",  WBS_ACT_EVENTS+35);

define("EVNT_INLINE",  WBS_ACT_EVENTS+36);
define("EVNT_OFFLINE",  WBS_ACT_EVENTS+37);
define("EVNT_EMPTY_CACHE",  WBS_ACT_EVENTS+38);

?>