<?php 
define('LOC_TITLE_FAQ','Foire Aux Questions'); 
define('LOC_TITLE_EVENTS','Tournois'); 
define('LOC_TITLE_TEAM','Compétitions par équipe'); 
define('LOC_TITLE_CONNECTION','Connexion'); 
define('LOC_P_DIRECT_ACCESS','Vous ne vous êtes pas déconnecté lors votre dernière visite. Ceci peut être dangereux pour la confidentialité de vos tournois.'); 
define('LOC_LNK_DIRECT_ACCESS','Accès direct'); 
define('LOC_LNK_ACCOUNT','Nouveau compte'); 
?>