<?php
/*****************************************************************************
!   Module     : Badges
!   File       : $Source: /cvsroot/aotb/badnet/src/badges/badges.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.3 $
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/05/19 09:56:24 $
******************************************************************************/

define("BADGES_EDIT",     WBS_ACT_BADGES+1);
define("BADGES_UPDATE",   WBS_ACT_BADGES+2);
define("BADGES_PLAYERS",  WBS_ACT_BADGES+3);
define("BADGES_OFFOS",    WBS_ACT_BADGES+4);
define("BADGES_OTHERS",   WBS_ACT_BADGES+5);
define("BADGES_PDF",      WBS_ACT_BADGES+6);
define("BADGES_DELETE",   WBS_ACT_BADGES+7);
define("BADGES_ZONES",       WBS_ACT_BADGES+8);
define("BADGES_ZONE",        WBS_ACT_BADGES+9);
define("BADGES_ZONE_UPDATE", WBS_ACT_BADGES+10);
define("BADGES_ZONE_DELETE", WBS_ACT_BADGES+11);
define("BADGES_ZONE_ADD",    WBS_ACT_BADGES+12);
define("BADGES_ZONE_REMOVE", WBS_ACT_BADGES+13);
define("BADGES_ZONE_DETAIL", WBS_ACT_BADGES+14);
define("BADGES_PRINTED",     WBS_ACT_BADGES+15);
define("BADGES_NOPRINTED",   WBS_ACT_BADGES+16);

?>
