<?php
/*****************************************************************************
!   Module     : Main
!   File       : $Source: /cvsroot/aotb/badnet/src/main/main.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.2 $
!   Author     : G.CANTEGRIL
!   Mailto     : cage@free.fr
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/18 07:51:18 $
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

// Contacter l'administrateur
define("MAIN_MAIL",     KID_USER);
define("MAIN_SENDMAIL", KID_USER+1);
define("MAIN_UPDATE_PARAM", WBS_ACT_PARAMETERS + 2);
define("MAIN_EDIT_PARAM",   WBS_ACT_PARAMETERS + 3);

?>