<?php 
define('LOC_P_ACCOUNT_INFOS','Saisissez votre mot de passe et le code de sécurité pour terminer la création de votre compte'); 
define('LOC_MSG_ACCOUNT_EXIST','Un compte existe déjà pour ce joueur. Si vous pensez être victime d\'une usurpation, contacter le modérateur à partir de la page d\'accueil.'); 
define('LOC_MSG_UNKNOW_PLAYER','Numéro de licence inconnu dans la base féférale.'); 
define('LOC_MSG_BAD_BORN','La date de naissance de naissance ne correspond pas à celle enregistrée dans la base de données fédérale.'); 
define('LOC_LABEL_BORN','Date de naissance'); 
define('LOC_LABEL_LICENSE','License number'); 
define('LOC_TITLE_ACCOUNT_LICENSE','License number'); 
define('LOC_P_ACCOUNT_CLUB','Vous avez choisi la création d\'un compte Association. Vous pourrez l\'utiliser pour créer et gérer les compétitions que vous organisez, gérer les inscriptions de vos joueurs a toutes les compétitions déclarées. 
      Il ne pourra pas être converti en compte simple ou Joueur.'); 
define('LOC_TITLE_ACCOUNT_CLUB','Création d\'un compte Association'); 
define('LOC_P_ACCOUNT_PLAYER','Vous avez choisi la création d\'un compte Joueur. Vous pourrez l\'utiliser pour consulter vos résultats et vous inscrire en ligne aux compétitions déclarées. Il ne pourra pas être converti en compte simple ou Association.
      Saisissez votre numéro de licence et votre date de naissance. Ces informations doivent être conformes à celles enregistrées dans la base de données fédérale.'); 
define('LOC_TITLE_ACCOUNT_PLAYER','Création d\'un compte joueur'); 
define('LOC_P_ACCOUNT_OTHER','Vous avez choisi la création d\'un compte simple. Vous pourrez l\'utiliser pour devenir capitaine d\une équipe interclubs, ou gestionnaire d\'une compétition. 
      Il pourra être converti en compte Association en le reliant à l\'association de votre choix.'); 
define('LOC_TITLE_ACCOUNT_OTHER','Création d\'un compte simple'); 
define('LOC_LABEL_OTHER_DESC','Utiliser ce type de compte si vous devez être capitaine d\'équipe interclubs ou gestionnaire d\'une ou plusieurs compétitions'); 
define('LOC_LABEL_OTHER','Compte simple.'); 
define('LOC_LABEL_CLUB_DESC','Ce type de compte est relié à une association affiliée à la fédération. Il permet de créer des compétitions, inscrire des équipes aux interclubs, gérer les joueurs de l\'association...'); 
define('LOC_LABEL_CLUB','Compte association.'); 
define('LOC_LABEL_PLAYER','Compte joueur.'); 
define('LOC_LABEL_PLAYER_DESC','Le compte Joueur est un compte personnel. Seul les joueurs licenciés peuvent utiliser ce type de compte. L\'identifiant est le numéro de licence. Ce compte permet de consulter son classement et permettra d\'utiliser le module d\'inscription en ligne aux tournois.'); 
define('LOC_P_ACCOUNT','Choisissez le type de compte en fonction de vos besoins. Le création de compte est gratuite; N\'hésitez pas à créer plusieurs compte pour séparer les fonctions que vous pouvez cumuler. Si vous êtes à la fois Juge-arbitre, responsable de d\'association et capitaine d\'équipe interclubs, créez un compte pour chaque fonction.'); 
define('LOC_TITLE_ACCOUNT2','Choix du type de compte'); 
define('LOC_TITLE_ACCOUNT_TYPE','Type de compte'); 
define('LOC_MSG_ERR_EMAIL_ACCOUNT','Libellé ES'); 
define('LOC_LNK_BACK_HOME','Libellé ES'); 
define('LOC_MSG_ERRORLOGIN','Libellé ES'); 
define('LOC_TITLE_BADLOGIN','Libellé ES'); 
define('LOC_TITLE_LOGIN','Libellé ES'); 
define('LOC_MSG_SEND_PWD','Libellé ES'); 
define('LOC_MSG_ERR_EMAIL','Libellé ES'); 
define('LOC_MSG_BAD_EMAIL','Libellé ES'); 
define('LOC_MSG_ACCOUNT_VALID','Libellé ES'); 
define('LOC_MSG_ACCOUNT_CONFIRM','Libellé ES'); 
define('LOC_EMAIL_BODY','Libellé ES'); 
define('LOC_EMAIL_OBJECT_PWD','Libellé ES'); 
define('LOC_P_ASK_PWD','Libellé ES'); 
define('LOC_TITLE_NEW_PASSWORD','Libellé ES'); 
define('LOC_MSG_LOGIN_NOT_BLANK','Libellé ES'); 
define('LOC_MSG_LOGIN_ALREADY_USED','Libellé ES'); 
define('LOC_MSG_BAD_DIFFPWD','Libellé ES'); 
define('LOC_MSG_LOGIN_NOT_PWD','Libellé ES'); 
define('LOC_MSG_EMAIL_ALREADY_USED','Libellé ES'); 
define('LOC_MSG_BAD_CODE','Libellé ES'); 
define('LOC_MSG_AQUIT_DEMANDE','Libellé ES'); 
define('LOC_BODY_DEMANDE','Libellé ES'); 
define('LOC_OBJECT_DEMANDE','Libellé ES'); 
define('LOC_P_EMAIL','Libellé ES'); 
define('LOC_P_CAPTCHA','Libellé ES'); 
define('LOC_P_PSEUDO','Libellé ES'); 
define('LOC_LABEL_CAPTCHA','Libellé ES'); 
define('LOC_LABEL_CONFIRM','Libellé ES'); 
define('LOC_TITLE_CAPTCHA','Libellé ES'); 
define('LOC_TITLE_SAISIE','Libellé ES'); 
define('LOC_TITLE_NEW_ACCOUNT','Libellé ES'); 
?>