<?php 
define('LOC_LABEL_OLD_PASSWORD','Libellé ES'); 
define('LOC_LABEL_NEW_PASSWORD','Libellé ES'); 
define('LOC_LABEL_CONFIRM_PASSWORD','Libellé ES'); 
define('LOC_TITLE_PASSWORD','Libellé ES'); 
define('LOC_LNK_CHANGE_PWD','Libellé ES'); 
define('LOC_TITLE_CONTACT','Libellé ES'); 
define('LOC_P_CIVILITE','Libellé ES'); 
define('LOC_P_ASSOCIATION','Libellé ES'); 
define('LOC_MSG_REGISTERED','Libellé ES'); 
define('LOC_MSG_ALREADY_MANAGE','Libellé ES'); 
define('LOC_MSG_NEED_PHONE','Libellé ES'); 
?>