<?php
/*****************************************************************************
!   Module     : members
!   File       : $Source: /cvsroot/aotb/badnet/src/mber/mber.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.2 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/01/18 07:51:18 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

define("MBER_UPDATE_NOREFRESH",       WBS_ACT_MBER+1);
define("MBER_EDIT_NOREFRESH",         WBS_ACT_MBER+2);
define("MBER_ADM_ALL",         WBS_ACT_MBER+3);
define("MBER_ADM_OFFICIALS",   WBS_ACT_MBER+4);
define("MBER_ADM_OTHERS",      WBS_ACT_MBER+5);
define("MBER_EDIT_ACCOUNT",    WBS_ACT_MBER+6);
define("MBER_UPDATE_ACCOUNT",  WBS_ACT_MBER+7);
define("MBER_CREDITS",         WBS_ACT_MBER+8);
define("MBER_ARRIVAL",         WBS_ACT_MBER+9);
define("MBER_DEPARTURE",       WBS_ACT_MBER+10);
define("MBER_NEW_DEPARR",      WBS_ACT_MBER+11);
define("MBER_UPDATE_DEPARR",   WBS_ACT_MBER+12);
define("MBER_EDIT_DEPARR",     WBS_ACT_MBER+13);
define("MBER_SELECT_PHOTO",    WBS_ACT_MBER+14);
define("MBER_UPDATE_PHOTO",    WBS_ACT_MBER+15);

?>