<?php 
define('LOC_MSG_RESULT_CONFIRMED','Les résultats de la rencontre sont confirmés. Seul l\'organisateur de la compétition peux les modifier.'); 
define('LOC_MSG_RESULT_SENDED','Les résultats de la rencontre sont enregistrés. Un email de confirmation a été envoyé au capitaine adverse pour qu\'il donne son accord.'); 
define('LOC_LABEL_GENDER','Genre'); 
define('LOC_TITLE_EMAIL_PLAYERS','Contacter tous les joueurs'); 
define('LOC_TITLE_EMAIL_PLAYER','Contacter un joueur.'); 
define('LOC_MSG_EMAIL_ONLY','Seule l\'adresse email du joueur est modifiable.'); 
define('LOC_TITLE_EDIT_PLAYER','Modification d\'un joueur'); 
define('LOC_MSG_VALIDATION','Les résultats de cette rencontre ont été saisis par le capitaine de l\'équipe adverse. Vous devez soit les accepter de façon définitives et ils ne seront plus modifiables, soit les modifier. Dans le second cas, un email est envoyé au capitaine adverse pour qu\'il les valide.'); 
define('LOC_MSG_PLAYER_TEAM','Ce joueur est déjà inscrit dans une autre équipe. Vous ne pouvez pas l\'intégrer à celle ci.'); 
define('LOC_MSG_ADD_PLAYER','Saisissez le nom ou le numéro de licence puis choisissez le joueur dans la liste. Utilisez le caractère % pour remplacer un ou plusieurs caractères. Seul l\'email du joueur choisi est modifibale.'); 
define('LOC_LABEL_EMAIL','Email'); 
define('LOC_MSG_CONFIRM_DEL_PLAYER','Vous allez supprimer le joueur de votre équipe. Vous pourrez le rajouter ultérieurement si nécessaire.'); 
define('LOC_TITLE_ADD_PLAYER','Ajouter un joueur'); 
define('LOC_LABEL_ONE_MORE','Ajouter un autre joueur aprés celui-ci'); 
define('LOC_LABEL_LEVEL','Classement'); 
define('LOC_MSG_DELAY','L\'ajout de joueur est bloqué %bndays% jours avant la prochaine rencontre et tant que toutes les rencontres passées ne sont pas validés.'); 
define('LOC_MSG_MULTIASSO_NO','Seul les joueurs du club sont autorisés à jouer pour cette équipe.'); 
define('LOC_MSG_MULTIASSO_YES','Les joueurs d\'un autre club sont autorisés à jouer pour cette équipe.'); 
define('LOC_MSG_MULTITEAM_YES','Un joueur est autorisé à jouer dans plusieurs équipes de cette compétition.'); 
define('LOC_MSG_MULTITEAM_NO','Un joueur ne peut jouer que dans une seule équipe.'); 
define('LOC_MSG_LICENSE_ONLY','Seul les joueurs licenciés peuvent participer à cette compétition.'); 
define('LOC_MSG_NEVER','Les gestionnaires de la compétition ont bloqué l\'ajout de joueur. Vous ne pouvez pas rajouter de joueur à votre équipe.'); 
define('LOC_LABEL_RANK','Rang'); 
define('LOC_LABEL_NEW_PLAYER','Enregistrer puis ajouter un autre joueur'); 
define('LOC_LABEL_TEAM','Changer d\'équipe'); 
define('LOC_TITLE_RESULTS','Classement et résultats du groupe'); 
define('LOC_LABEL_FROM','De'); 
define('LOC_TITLE_EMAIL_MANAGER','Contacter les organisateurs'); 
define('LOC_TITLE_EMAIL','Contacter l\'équipe adverse'); 
define('LOC_MSG_TIE_CONFIRM','Bonjour,
      
le capitaine de l\'équipe que vous avez affrontée vient 
de saisir les résultats de la rencontre. La date limite 
de saisie/validation des résultats est le %bnmaxdelay%.
Au dela de cette date vous ne pourrez plus modifier ces
résultats. Seul les gestionnaires de la compétition pourront
faire des modifications.

----------------------------------------
%bnresult%
----------------------------------------

Il a ce message pour vous.

----------------------------------------
%bncomment%
----------------------------------------

Si vous êtes d\'accord avec les résultats saisis,
utiliser le lien ci-dessous pour les valider de
façon définitive.

========================================
Confirmer les résultats
%bnconfirm%
========================================

Si les résultats proposés ne vous semblent pas correct
ou sont incomplets, utiliser le lien suivant pour les 
modifier et proposer vos modifications au capitaine de 
l\'autre équipe.
========================================
Modifier les résultats
%bnrefuse%
========================================
'); 
define('LOC_P_INFO_GROUPS','Voici les joueurs pour chacune des équipes de votre groupe.'); 
define('LOC_BTN_ACCEPT','Accepter'); 
define('LOC_P_TIE_CONFIRM','Les résultats que vous avez saisis vont être envoyés au capitaine de l\'équipe adverse pour confirmation. Vous ne pourrez plus les modifier. Si le capitaine adverse n\'est pas d\'accord avec votre saisie, il pourra la modifier. Vous recevrez alors un email pour confirmer ou refuser sa modification.'); 
define('LOC_P_TIE','Saisissez les résultats des matches de la rencontre. S\'il manque des joueurs dans l\'équipe adverse enregistrer les matches sans ces joueurs. Un email sera envoyé à l\'autre capitaine pour qu\'il valide ou termine la saisie des résultats.'); 
define('LOC_COLUMN_ASSO','Club'); 
define('LOC_LABEL_COMMENT','Commentaire'); 
define('LOC_LABEL_GROUP','Groupe'); 
define('LOC_LABEL_ASSO','Club'); 
define('LOC_LABEL_VALIDATE','Résultats validés par %bnuser% le %bndate%'); 
define('LOC_LABEL_REGISTERED','Résultats saisis par %bnuser% le %bndate%'); 
define('LOC_TITLE_TIE','Résultat d\'une rencontre'); 
define('LOC_TITLE_REGIS_PLAYERS','Joueurs par équipes'); 
define('LOC_LGD_OTHER_TEAM','Inscrit dans autre équipe'); 
define('LOC_LGD_TEAM','Inscrit dans votre équipe'); 
define('LOC_TITLE_SPORT','Sportif'); 
define('LOC_TITLE_CIVIL','Civilité'); 
define('LOC_LABEL_NUMCATAGE','Numéro'); 
define('LOC_LABEL_CATAGE','Catégorie'); 
define('LOC_LABEL_SURCLASSE','Surclassement'); 
define('LOC_LABEL_MIXED','Classement mixte'); 
define('LOC_LABEL_DOUBLE','Classement double'); 
define('LOC_LABEL_SINGLE','Classement'); 
define('LOC_LABEL_WOMAN','Femme'); 
define('LOC_LABEL_MAN','Homme'); 
define('LOC_LABEL_LICENSE','Licence'); 
define('LOC_LABEL_BORN','Née le'); 
define('LOC_LABEL_FIRSTNAME','Prénom'); 
define('LOC_LABEL_FAMNAME','Nom'); 
define('LOC_TITLE_PLAYER','Création d\'un nouveau joueur'); 
define('LOC_LINK_BACK_CAPTAIN','Retour à la page principale'); 
define('LOC_LINK_CONSULT_RESULTS','Consulter les résultats et le classement du groupe'); 
define('LOC_LINK_CONSULT_PLAYERS','Consulter les joueurs des équipes'); 
define('LOC_TITLE_TEAM_PLAYERS','Joueurs de mon équipe'); 
define('LOC_LINK_ADD_PLAYER','Joueurs de mon équipe'); 
define('LOC_MSG_CAPTAIN_TIES','La liste des rencontres de votre équipe est classée par date. Utilisez les icônes pour contacter les capitaines des équipes adverses ou pour saisir le résultat de la rencontre. La saisie est accessible à compter du jour prévu pour la rencontre et pendant %bndelay% jours.'); 
define('LOC_MSG_PLAYERS_CHOICE','Sélectionnez les joueurs à ajouter à votre équipe en cochant la case à cocher en début de ligne ou en cliquant sur la ligne correspondante. Utilisez les critères de filtrage pour faciliter votre recherche. Si vous ne trouvez pas le joueur, utilisez le bouton "Nouveau joueur" pour en créer un nouveau.'); 
define('LOC_BTN_NEW','Nouveau joueur'); 
define('LOC_TITLE_PLAYERS','Joueurs de l\'équipe'); 
define('LOC_TITLE_TIES','Rencontres de votre équipe'); 
define('LOC_COLUMN_PLACE','Lieu'); 
define('LOC_COLUMN_VERSUS','Adversaire'); 
define('LOC_COLUMN_RESULT','Résultat'); 
define('LOC_COLUMN_SCORE','Score'); 
define('LOC_COLUMN_RANK','Rang'); 
define('LOC_COLUMN_SURCLASSE','Surclassement'); 
define('LOC_COLUMN_CATAGE','Catégorie'); 
define('LOC_COLUMN_LEVEL','Classement'); 
define('LOC_COLUMN_LICENSE','Licence'); 
define('LOC_COLUMN_FIRSTNAME','Prénom'); 
define('LOC_COLUMN_FAMNAME','Nom'); 
define('LOC_COLUMN_GENDER','Genre'); 
define('LOC_CRIT_GENDER','Critères de filtrage'); 
define('LOC_LABEL_SEARCH','Nom ou licence'); 
define('LOC_P_INFO_TEAM','Vous êtes le capitaine de cette équipe'); 
define('LOC_P_INFO_CAPTAIN','Les liens ci-dessous vous permettent d\'accéder aux fonctions de gestion de votre équipe.'); 
?>