<?php 
define('LOC_MSG_CONFIRM_DELETE_POSTIT','Le message sélectionné va être définitivement supprimé.'); 
define('LOC_TITLE_DELETE_POSTIT','Suppression d\'un message'); 
define('LOC_COLUMN_CONTENT','Message'); 
define('LOC_COLUMN_OBJECT','Objet'); 
define('LOC_TITLE_POSTITS','Liste des messages'); 
define('LOC_BTN_PUBLIC','Publier/masquer le tournoi'); 
define('LOC_BTN_CACHE','Vider le cache'); 
define('LOC_MSG_EVENT_DELETED','Le tournoi a été supprimé.'); 
define('LOC_MSG_CONFIRM_DELETE_EVENT','Vous allez supprimer le tournoi sélectionné. Toutes les données seront perdues.'); 
define('LOC_TITLE_DELETE_EVENT','Supression d\'un tournoi'); 
define('LOC_TITLE_NEW_EVENT','Nouveau tournoi'); 
define('LOC_COLUMN_VISITED','Visites'); 
define('LOC_COLUMN_EVENT_NAME','Nom du tournoi'); 
define('LOC_COLUMN_FIRST_DAY','Premier jour'); 
define('LOC_TITLE_EVENTS','Tournois'); 
define('LOC_BTN_NEW_EVENT','Nouveau tournoi'); 
define('LOC_LABEL_SEARCH_EVENT','Nom'); 
define('LOC_MSG_CAPTAIN_DELETED','L\'équipe n\'a plus de capitaine'); 
define('LOC_MSG_CONFIRM_DEL_CAPTAIN','Vous allez retirer la fonction de capitaine pour l\'équipe choisie.'); 
define('LOC_P_INFO','Les liens ci-dessous vous permettent d\'accéder aux fonctions de gestion de la compétition.'); 
?>