<?php
/*****************************************************************************
!   $Id$
******************************************************************************/
require_once 'Accueil/Accueil.inc';

$indice = ACCUEIL_MAIN+1;

define('MAIN_ACCUEIL',    $indice++);
define('MAIN_COLRIGHT',   $indice++);
define('MAIN_SOFT',       $indice++);
define('MAIN_RESULT',     $indice++);
define('MAIN_ORGANIZER',  $indice++);
define('MAIN_ASSOC',      $indice++);
define('MAIN_PLAYER',     $indice++);
define('MAIN_FR',         $indice++);
define('MAIN_UK',         $indice++);
define('MAIN_DE',         $indice++);
define('MAIN_SEARCH',     $indice++);
define('MAIN_PAGE_HELP',  $indice++);
?>
