<?php 
define('LOC_P_ACCOUNT_INFOS','Saisissez votre mot de passe et le code de sécurité pour terminer la création de votre compte'); 
define('LOC_MSG_ACCOUNT_EXIST','Un compte existe déjà pour ce joueur. Si vous pensez être victime d\'une usurpation, contacter le modérateur à partir de la page d\'accueil.'); 
define('LOC_MSG_UNKNOW_PLAYER','Numéro de licence inconnu dans la base féférale.'); 
define('LOC_MSG_BAD_BORN','La date de naissance de naissance ne correspond pas à celle enregistrée dans la base de données fédérale.'); 
define('LOC_LABEL_BORN','Date de naissance'); 
define('LOC_LABEL_LICENSE','License number'); 
define('LOC_TITLE_ACCOUNT_LICENSE','License number'); 
define('LOC_P_ACCOUNT_CLUB','Vous avez choisi la création d\'un compte Association. Vous pourrez l\'utiliser pour créer et gérer les compétitions que vous organisez, gérer les inscriptions de vos joueurs a toutes les compétitions déclarées. 
      Il ne pourra pas être converti en compte simple ou Joueur.'); 
define('LOC_TITLE_ACCOUNT_CLUB','Création d\'un compte Association'); 
define('LOC_P_ACCOUNT_PLAYER','Vous avez choisi la création d\'un compte Joueur. Vous pourrez l\'utiliser pour consulter vos résultats et vous inscrire en ligne aux compétitions déclarées. Il ne pourra pas être converti en compte simple ou Association.
      Saisissez votre numéro de licence et votre date de naissance. Ces informations doivent être conformes à celles enregistrées dans la base de données fédérale.'); 
define('LOC_TITLE_ACCOUNT_PLAYER','Création d\'un compte joueur'); 
define('LOC_P_ACCOUNT_OTHER','Vous avez choisi la création d\'un compte simple. Vous pourrez l\'utiliser pour devenir capitaine d\une équipe interclubs, ou gestionnaire d\'une compétition. 
      Il pourra être converti en compte Association en le reliant à l\'association de votre choix.'); 
define('LOC_TITLE_ACCOUNT_OTHER','Création d\'un compte simple'); 
define('LOC_LABEL_OTHER_DESC','Utiliser ce type de compte si vous devez être capitaine d\'équipe interclubs ou gestionnaire d\'une ou plusieurs compétitions'); 
define('LOC_LABEL_OTHER','Compte simple.'); 
define('LOC_LABEL_CLUB_DESC','Ce type de compte est relié à une association affiliée à la fédération. Il permet de créer des compétitions, inscrire des équipes aux interclubs, gérer les joueurs de l\'association...'); 
define('LOC_LABEL_CLUB','Compte association.'); 
define('LOC_LABEL_PLAYER','Compte joueur.'); 
define('LOC_LABEL_PLAYER_DESC','Le compte Joueur est un compte personnel. Seul les joueurs licenciés peuvent utiliser ce type de compte. L\'identifiant est le numéro de licence. Ce compte permet de consulter son classement et permettra d\'utiliser le module d\'inscription en ligne aux tournois.'); 
define('LOC_P_ACCOUNT','Choisissez le type de compte en fonction de vos besoins. Le création de compte est gratuite; N\'hésitez pas à créer plusieurs compte pour séparer les fonctions que vous pouvez cumuler. Si vous êtes à la fois Juge-arbitre, responsable de d\'association et capitaine d\'équipe interclubs, créez un compte pour chaque fonction.'); 
define('LOC_TITLE_ACCOUNT2','Choix du type de compte'); 
define('LOC_TITLE_ACCOUNT_TYPE','Type de compte'); 
define('LOC_MSG_ERR_EMAIL_ACCOUNT','Error occurs; Message not send'); 
define('LOC_LNK_BACK_HOME','Go back home'); 
define('LOC_MSG_ERRORLOGIN','Bad login or password. Use the link "Forgotten password" to obtain a new passord.'); 
define('LOC_TITLE_BADLOGIN','Connection failed'); 
define('LOC_TITLE_LOGIN','Connection'); 
define('LOC_MSG_SEND_PWD','New password sended'); 
define('LOC_MSG_ERR_EMAIL','Error. Try again.'); 
define('LOC_MSG_BAD_EMAIL','Unknow email'); 
define('LOC_MSG_ACCOUNT_VALID','Hello,
      
your account is ready.

--------------------------------
Login : %bnid%
Password : %bnpwd%
--------------------------------
'); 
define('LOC_MSG_ACCOUNT_CONFIRM','Account confirmation'); 
define('LOC_EMAIL_BODY','Hello,
Someone asked for the password of your account.

Here are your new login data.

-------------------------------
Identifier : %bnid%
Password : %bnpwd%
-------------------------------
'); 
define('LOC_EMAIL_OBJECT_PWD','Password'); 
define('LOC_P_ASK_PWD','Give your e-mail address, a mail with a new password will be send to you.'); 
define('LOC_TITLE_NEW_PASSWORD','New password'); 
define('LOC_MSG_LOGIN_NOT_BLANK','Login must not have blank'); 
define('LOC_MSG_LOGIN_ALREADY_USED','Login already used'); 
define('LOC_MSG_BAD_DIFFPWD','Password must be equal'); 
define('LOC_MSG_LOGIN_NOT_PWD','Login and password must be different'); 
define('LOC_MSG_EMAIL_ALREADY_USED','Email already used.'); 
define('LOC_MSG_BAD_CODE','Bad image number! Try again.'); 
define('LOC_MSG_AQUIT_DEMANDE','Votre demande de création de compte a bien été enregistrée. Vous allez recevoir un courrier électronique vous précisant la marche à suivre pour terminer votre enregistrement.'); 
define('LOC_BODY_DEMANDE','Hello,
      
an demand for a account were effected.
If you didn\'t ask for it, simply ignore this mail.
Otherwise click on the following link to confirm your registration.

========================================
Confirm your account
%bnconfirm%
========================================

Best regards.
'); 
define('LOC_OBJECT_DEMANDE','Create an new account'); 
define('LOC_P_EMAIL','You will receive an email with instructions.'); 
define('LOC_P_CAPTCHA','To securize the registration please give the number of pictures.'); 
define('LOC_P_PSEUDO','Libelle EN'); 
define('LOC_LABEL_CAPTCHA','Number of pictures'); 
define('LOC_LABEL_CONFIRM','Confirm password'); 
define('LOC_TITLE_CAPTCHA','Security'); 
define('LOC_TITLE_SAISIE','Informations'); 
define('LOC_TITLE_NEW_ACCOUNT','New account'); 
?>