<?php 
define('LOC_LABEL_OLD_PASSWORD','Current password'); 
define('LOC_LABEL_NEW_PASSWORD','New password'); 
define('LOC_LABEL_CONFIRM_PASSWORD','Confirmation'); 
define('LOC_TITLE_PASSWORD','Password'); 
define('LOC_LNK_CHANGE_PWD','New password'); 
define('LOC_TITLE_CONTACT','Adress'); 
define('LOC_P_CIVILITE','Pour utiliser le module d\'inscription en ligne ou adhérer à l\'association, vous devez renseigner les coordonnées et les informations permettant de vous contacter si le besoin se présente.'); 
define('LOC_P_ASSOCIATION','Pour utiliser le module d\'inscription en ligne vous devez être responsable d\'une association. Nous vous conseillons de modifier ce compte pour qu\'il devienne celui de l\'association. Ainsi il restera toujours valide si le responsable de l\'association change. 
Choisissez un login simple (comme le sigle de l\'association) et utilisez le nom de l\'association comme nom du compte.'); 
define('LOC_MSG_REGISTERED','Data updated'); 
define('LOC_MSG_ALREADY_MANAGE','Association alredy in use.'); 
define('LOC_MSG_NEED_PHONE','Veuillez renseigner au moins un des deux champs Mobile ou Fixe.'); 
?>