<?php 
define('LOC_P_FILES','Sélectionner le fichier contenant les données à	importer. Ce fichier doit être au format XML. Il doit provenir soit du site BadNet soit du responsable des interclubs. Il peut aussi provenir d\'une sauvegarde obtenue avec cet outil. Attention, toutes les données déjà enregistrées seront supprimées avant le traitement du fichier.'); 
define('LOC_LABEL_FILE','Fichier'); 
define('LOC_TITLE_FILE','Choix du fichier'); 
define('LOC_BTN_IMPORT','Importer'); 
define('LOC_LABEL_INPUT','Utiliser cette option pour initialiser les rencontres de la journée d\'interclub que vous organisez. Vous devez pour cela utiliser le fichier qui vous a été transmis ou que vous avez récupéré sur le site BadNet. Vous pouvez aussi utiliser une sauvegarde que vous auriez généré avec cet outil. Attention : lors de cette opération, toutes les données actuellement présentes seront supprimées et remplacées par celles contenu dans le fichier que vous allez choisir.'); 
define('LOC_TITLE_INPUT','Importation'); 
define('LOC_BTN_OUTPUT','Sauvegarder'); 
define('LOC_LABEL_OUTPUT','La sauvegarde permet d\'enregistrer les rencontres dans un fichier externe. Ce fichier pourra être utilisé soit pour restaurer les rencontres dans cet outil, soit pour les fusionner dans le tournoi final.'); 
define('LOC_TITLE_OUTPUT','Sauvegarde'); 
define('LOC_P_TRANSFERT','Le module de transfert vous permet d\'importer des données à partir d\'un fichier ou alors d\'enregistrer les rencontres dans un fichier de sauvegarde pour pouvoir les tranférer dans le tournoi final.'); 
define('LOC_TITLE_CHOICE','Choix du transfert'); 
define('LOC_TITLE_TRANSFERT','Transfert de données'); 
?>