<?php 
define('LOC_P_FILES','Sélectionner le fichier contenant les données à	importer. Ce fichier doit être au format XML. Il doit provenir soit du site BadNet soit du responsable des interclubs. Il peut aussi provenir d\'une sauvegarde obtenue avec cet outil. Attention, toutes les données déjà enregistrées seront supprimées avant le traitement du fichier.'); 
define('LOC_LABEL_FILE','Fichier'); 
define('LOC_LABEL_TOURNAMENT','Tournoi'); 
define('LOC_LABEL_STEP','Journée'); 
define('LOC_TITLE_CONTROL','Contrôle du fichier'); 
?>