<?php
/*****************************************************************************
!   Module    : Draws
!   Version   : v0.0.1
!   Author    : G.CANTEGRIL
!   Co-author :
!   Mailto    : cage@aotb.org
!   Date      : 01-12-2003
******************************************************************************/

define("DRAW_SERIAL_NEW",        WBS_ACT_DRAWS+1);
define("DRAW_SERIAL_CREATE",     WBS_ACT_DRAWS+2);
define("DRAW_SERIAL_EDIT",       WBS_ACT_DRAWS+3);
define("DRAW_SERIAL_UPDATE",     WBS_ACT_DRAWS+4);

define("DRAW_DISPLAY",       WBS_ACT_DRAWS+5);
define("DRAW_FUSION",        WBS_ACT_DRAWS+7);


define("DRAW_DEFINITION",           WBS_ACT_DRAWS+9);
define("DRAW_GROUPS_DISPLAY",       WBS_ACT_DRAWS+10);
define("DRAW_KO_DISPLAY",           WBS_ACT_DRAWS+11);
define("DRAW_FINAL_DISPLAY",        WBS_ACT_DRAWS+12);
define("DRAW_PDF_PAIRSIBF",         WBS_ACT_DRAWS+13);
define("DRAW_PDF_PAIRS",            WBS_ACT_DRAWS+14);
define("DRAW_UPDATE_CPPP",          WBS_ACT_DRAWS+15);
define("DRAW_LIST",                 WBS_ACT_DRAWS+16);

define("DRAW_PDF_KO",               WBS_ACT_DRAWS+20);
define("DRAW_PDF_GROUPS",           WBS_ACT_DRAWS+21);
define("DRAW_PDF_KO_IBF",           WBS_ACT_DRAWS+22);
define("DRAW_PDF_ALL_KO",           WBS_ACT_DRAWS+23);
define("DRAW_PDF_ALL_GROUPS",       WBS_ACT_DRAWS+24);
define("DRAW_PDF_GROUPSRANK",       WBS_ACT_DRAWS+25);
define("DRAW_PDF_GROUP_KO",         WBS_ACT_DRAWS+26);

define("DRAW_ROUND_PUBLIC",         WBS_ACT_DRAWS+30);
define("DRAW_ROUND_PRIVATE",        WBS_ACT_DRAWS+31);
define("DRAW_ROUND_CONFIDENT",      WBS_ACT_DRAWS+32);
define("DRAW_ROUND_DELETE",         WBS_ACT_DRAWS+33);
define("DRAW_ROUND_NEW",            WBS_ACT_DRAWS+34);
define("DRAW_ROUND_CONFIRM",        WBS_ACT_DRAWS+35);
define("DRAW_ROUND_CREATE",         WBS_ACT_DRAWS+36);

define("DRAW_GROUP_PUBLIC",         WBS_ACT_DRAWS+40);
define("DRAW_GROUP_PRIVATE",        WBS_ACT_DRAWS+41);
define("DRAW_GROUP_CONFIDENT",      WBS_ACT_DRAWS+42);
define("DRAW_PUBLISHED",            WBS_ACT_DRAWS+43);

define("DRAW_PDF_STATS",            WBS_ACT_DRAWS+44);
define("DRAW_CALENDAR",             WBS_ACT_DRAWS+45);

define("DRAW_XLS_STATS",            WBS_ACT_DRAWS+46);
define("DRAW_XLS_DRAWS",            WBS_ACT_DRAWS+47);
define("DRAW_XLS_PAIRS",            WBS_ACT_DRAWS+48);
define("DRAW_XLS_PAIRS2",           WBS_ACT_DRAWS+49);

define("DRAW_GROUP_NEW",           WBS_ACT_DRAWS+50);
define("DRAW_GROUP_CREATE",        WBS_ACT_DRAWS+51);
define("DRAW_GROUP_EDIT",          WBS_ACT_DRAWS+52);
define("DRAW_GROUP_UPDATE",        WBS_ACT_DRAWS+53);
define("DRAW_GROUP_CONFIRM",       WBS_ACT_DRAWS+54);
define("DRAW_GROUP_DELETE",        WBS_ACT_DRAWS+55);

?>
