<?php
include_once "Badnetteam/Badnetteam.inc";

$indice = BADNETTEAM_EVENT;
define('TEVENT_PAGE_TIES',       $indice++);
define('TEVENT_PAGE_PLAYER',     $indice++);
define('TEVENT_PAGE_CHECK',      $indice++);
define('TEVENT_PAGE_TIE',        $indice++);
define('TEVENT_FILL_TIES',       $indice++);
define('TEVENT_FILL_MATCHS',     $indice++);
define('TEVENT_PAGE_TEAM',       $indice++);
define('TEVENT_UPDATE_TEAM',     $indice++);
define('TEVENT_FILL_PLAYERS',    $indice++);
define('TEVENT_CHECK_PLAYERS',   $indice++);
define('TEVENT_ADD_PLAYER',      $indice++);
define('TEVENT_STATUS_MATCH',    $indice++);
define('TEVENT_PAGE_SCORE',      $indice++);
define('TEVENT_UPDATE_SCORE',    $indice++);
define('TEVENT_PDF_SCORESHEET',  $indice++);
define('TEVENT_PDF_TIE',         $indice++);
define('TEVENT_PDF_TEAM',        $indice++);
define('TEVENT_PDF_CHECK',       $indice++);
define('TEVENT_PDF_ALLCHECK',    $indice++);
define('TEVENT_PAGE_ORDER',      $indice++);
define('TEVENT_UPDATE_ORDER',    $indice++);
define('TEVENT_PROPOSE_ORDER',   $indice++);
define('TEVENT_PAGE_PARAM',      $indice++);
define('TEVENT_UPDATE_PARAM',    $indice++);
define('TEVENT_DISPLAY_CHRONO',  $indice++);
define('TEVENT_PDF_TIEALL',      $indice++);
define('TEVENT_MATCH_UPDOWN',    $indice++);

define('TEVENT_START_MATCH',    $indice++);
define('TEVENT_STOP_MATCH',     $indice++);
define('TEVENT_FILL_TIE',       $indice++);
define('TEVENT_UPDATE_TIE',     $indice++);

?>
