<?php
/*****************************************************************************
!   Module     : Ties
!   File       : $Source: /cvsroot/aotb/badnet/src/ties/ties.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.2 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2006/12/08 17:40:08 $
!   Mailto     : cage@free.fr
******************************************************************************/

define("TIES_SELECT_RESULTS",  WBS_ACT_TIES+1);
define("TIES_UPDATE_RESULTS",  WBS_ACT_TIES+2);
define("TIES_SELECT_RANKING",  WBS_ACT_TIES+3);
define("TIES_SELECT_TIE",      WBS_ACT_TIES+4);
define("TIES_PDF_RESULTS",     WBS_ACT_TIES+5);
define("TIES_PDF_RANKING",     WBS_ACT_TIES+6);
define("TIES_UPDATE_PENALTIES",WBS_ACT_TIES+7);
define("TIES_PDF_TIE",         WBS_ACT_TIES+8);
define("TIES_PDF_TIES",        WBS_ACT_TIES+9);
define("TIES_PDF_SCHEDULE",    WBS_ACT_TIES+10);
define("TIES_VALID_RESULTS",   WBS_ACT_TIES+11);
define("TIES_INVALID_RESULTS", WBS_ACT_TIES+12);
define("TIES_EXPORT_POONA",    WBS_ACT_TIES+13);
define("TIES_ARCHIVE_POONA",   WBS_ACT_TIES+14);
define("TIES_RAZ_VALID",       WBS_ACT_TIES+15);
define("TIES_RAZ_SAISIE",      WBS_ACT_TIES+16);
?>
