<?php 
define('LOC_MSG_CONFIRM_DELETE_POSTIT','Message will be deleted'); 
define('LOC_TITLE_DELETE_POSTIT','Message deletion'); 
define('LOC_COLUMN_CONTENT','Message'); 
define('LOC_COLUMN_OBJECT','Object'); 
define('LOC_TITLE_POSTITS','Messages'); 
define('LOC_BTN_PUBLIC','Publish/hide tournament'); 
define('LOC_BTN_CACHE','Empty cache'); 
define('LOC_MSG_EVENT_DELETED','Tournament deleted.'); 
define('LOC_MSG_CONFIRM_DELETE_EVENT','Tournament and all data will be delete.'); 
define('LOC_TITLE_DELETE_EVENT','Delete tournament'); 
define('LOC_TITLE_NEW_EVENT','New tournament'); 
define('LOC_COLUMN_VISITED','Visits'); 
define('LOC_COLUMN_EVENT_NAME','Tournament name'); 
define('LOC_COLUMN_FIRST_DAY','Premier jour'); 
define('LOC_TITLE_EVENTS','Tournaments'); 
define('LOC_BTN_NEW_EVENT','New tournament'); 
define('LOC_LABEL_SEARCH_EVENT','Name'); 
define('LOC_MSG_CAPTAIN_DELETED','Libelle DE'); 
define('LOC_MSG_CONFIRM_DEL_CAPTAIN','Libelle DE'); 
define('LOC_P_INFO','Libelle DE'); 
?>