<?php
/*****************************************************************************
!   Module     : subscript
!   File       : $Source: /cvsroot/aotb/badnet/src/subscript/subscript.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.1 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2005/09/07 20:51:00 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

define("SUBS_TEAM_REG",      WBS_ACT_SUBS+1);
define("SUBS_PLAYER_REG",    WBS_ACT_SUBS+2);
define("SUBS_MATCH_REG",     WBS_ACT_SUBS+3);
define("SUBS_DEL_REG",       WBS_ACT_SUBS+4);


?>
