<?php
/*****************************************************************************
!   Module     : Teams
!   File       : $Source: /cvsroot/aotb/badnet/src/teams/teams.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.13 $
!   Revised by : $Author: cage $
!   Date       : $Date: 2007/05/19 09:56:25 $
******************************************************************************/
define("TEAM_SUBSCRIPT",     WBS_ACT_TEAMS+1);

define("TEAM_SEND_CONVOC",   WBS_ACT_TEAMS+2);

define("TEAM_RESERVATION",   WBS_ACT_TEAMS+11);
define("TEAM_DISCOUNT",      WBS_ACT_TEAMS+12);
define("TEAM_CREDITS",       WBS_ACT_TEAMS+13);
define("TEAM_PUBLISHED",     WBS_ACT_TEAMS+14);
define("TEAM_SELECT_LOGO",   WBS_ACT_TEAMS+16);
define("TEAM_UPDATE_LOGO",   WBS_ACT_TEAMS+17);
define("TEAM_SELECT_PHOTO",  WBS_ACT_TEAMS+18);
define("TEAM_UPDATE_PHOTO",  WBS_ACT_TEAMS+19);
define("TEAM_PDF_BADGES",    WBS_ACT_TEAMS+20);
define("TEAM_PDF_PLAYERS",   WBS_ACT_TEAMS+21);
define("TEAM_PDF_PAIRS",     WBS_ACT_TEAMS+22);
define("TEAM_PDF_ALLPLAYERS",    WBS_ACT_TEAMS+23);
define("TEAM_PDF_ALLPAIRS",      WBS_ACT_TEAMS+24);
define("TEAM_PDF_ASSOPLAYERS",   WBS_ACT_TEAMS+25);
define("TEAM_XLS_ENTRIES",       WBS_ACT_TEAMS+26);
define("TEAM_MERGE",             WBS_ACT_TEAMS+27);
define("TEAM_PDF_RESULTS",       WBS_ACT_TEAMS+28);
define("TEAM_MERGE_PLAYERS",     WBS_ACT_TEAMS+29);

define("TEAM_DETAILS_PLAYERS",  WBS_ACT_TEAMS+30);
define("TEAM_DETAILS_DATE"  ,   WBS_ACT_TEAMS+31);
define("TEAM_DETAILS_ITEMS",    WBS_ACT_TEAMS+32);
define("TEAM_PDF_PURCHASE",     WBS_ACT_TEAMS+33);
define("TEAM_ROOM",             WBS_ACT_TEAMS+34);
define("TEAM_PDF_ENTRIES",      WBS_ACT_TEAMS+35);
?>