<?php
/*****************************************************************************
!   Module    : Maintenance
!   Version   : v0.0.1
!   Author    : G.CANTEGRIL
!   Co-author :
!   Date      : 01-12-2003
******************************************************************************/

define("MAINT_REGIRANK",         WBS_ACT_MAINT+1);
define("MAINT_CREATE_REGIRANK",  WBS_ACT_MAINT+2);
define("MAINT_DELETE_REGIRANK",  WBS_ACT_MAINT+3);
define("MAINT_IMPORT_REGIRANK",  WBS_ACT_MAINT+4);
define("MAINT_UPDATE_REGIRANK",  WBS_ACT_MAINT+5);
define("MAINT_UPDATE_NAME",      WBS_ACT_MAINT+6);
define("MAINT_UPDATE_POST2T",    WBS_ACT_MAINT+7);
define("MAINT_DISPLAY_SUBSCRIBE",    WBS_ACT_MAINT+8);

define("MAINT_UPDATE_DRAWS",    WBS_ACT_MAINT+10);
define("MAINT_UPDATE_PAIRS",    WBS_ACT_MAINT+11);

define("MAINT_MERGE_ASSO",    WBS_ACT_MAINT+12);
define("MAINT_MERGE_MEMBER",  WBS_ACT_MAINT+13);
define("MAINT_MERGE_CONTACT", WBS_ACT_MAINT+14);




?>