<?php

include dirname(__FILE__)."/menu_V.inc";
//include dirname(__FILE__)."/t_asso.inc";

// Titre  du navigateur
$asso      = "Associations";

// Menu
$itEntries     = "Entries";
$itItems       = "Items";
$itReservation = "Reservations";
$itCompetition = "Competition";


// Titre des colonnes
$rowsPlayers1  = "Gender";
$rowsPlayers2  = "Identity";
$rowsPlayers3  = "Nat Num";
$rowsPlayers4  = "Ibf Num";
$rowsPlayers5  = "Events";

$reservations1 = "Date";
$reservations2 = "Item";
$reservations3 = "Identity";
$reservations4 = "Cost";
$reservations5 = "Discount";
$reservations6 = "Payed";
$reservations7 = "Du";

// Messages
$msgNoPlayers      = "No players for this tournament.";
$msgNoReservations = "No reservation for this tournament.";
?>
