<?php

/* Chaines de carcateres generiques */
$badnet_lang = 'en';
$leftTitle = "Badminton Netware";
$rightTitle = "Connection";

$wbs_notYet = "Undefined function";

$image = "Image file :";

$lgdVisitor = "&nbsp;Visitor";
$lgdUser    = "&nbsp;User";
$lgdGuest   = "&nbsp;Guest";
$lgdFriend  = "&nbsp;Friend";
$lgdAssist  = "&nbsp;Assistant";
$lgdAdmin   = "&nbsp;Administrator";
$lgdManager = "&nbsp;Manager";

$lgdConfident = "&nbsp;Confidential";
$lgdPrivate   = "&nbsp;Private";
$lgdPublic    = "&nbsp;Public";
$lgdDelete    = "&nbsp;Deleted";

$lgdIncomplete  = "Incomplete";
$lgdBusy        = "Busy";
$lgdRest        = "Rest";
$lgdReady       = "Ready";
$lgdLive        = "Live";
$lgdEnded       = "Ended";
$lgdClosed      = "Validate";
$lgdSend        = "Transmis";

$lgdMaindraw  = "M: Main draw";
$lgdQualif    = "Q: Qualification";
$lgdReserve   = "R: Reserve";
$lgdWdn       = "WDN: Withdraw";
$lgdPfr       = "PFR: Promoted From Reserve";
$lgdPtm       = "PMD: Promoted To Main draw";
$lgdPfq       = "PFQ: Promoted From Qualification";
$lgdRtd       = "RTD: Retired";
$lgdInjured   = "INJ: Injured";
$lgdQualify   = "Qi : Qualified number i";

$lgdPairs   = "More players/pairs then places";
$lgdPlaces  = "No enought playrs/pairs";
$lgdCompose = "Pair composed";

$helpAdmin  = "For any problem or comment about this site, contact an administrator above";

$username  = "Login :";
$password  = "Password :";

$tSubsList    = "Subscriptions";
$msgSubscript = "Subscribe now to the results!";
$msgSubsList  = "You receive email for the results of these teams";
$msgAskEvent  = "To organise, manage, publish your tournament in line, free of charge, contact an administrator above.";
$msgNoAutorisation  = "Not enought privilege to consult theses informations.";
$msgDirectLink  = "Direct link on this page :";

$msgUseImage  = "Cliquez sur l'image de votre choix ou téléchargez une nouvelle depuis votre ordinateur.";
$msgLimitedImage  = "ATTENTION: seules les images au format JPEG ou PNG seront correctement affichées dans les documents PDF.";
$msgDataBaseError = "Erreur d'accés à la base de données. Essayez à nouveau.";

$tManagerList = "Contacts";
$helpManager  = "To contact a manager of this event, select it in the list.";

$tEventInfos = "Pratique";
$numAuto     = "Autorisation";
$deadline    = "Fin inscription";
$evntDraws   = "Tirage au sort";
$evntBegin   = "First day";
$evntFin     = "Last day";
$evntSite    = "Official site:";

$tAdminList   = "Contacts";
$tUsersStat   = "Members";
$tEventsStat  = "Events";
$tVisitsStat  = "Visits";
$nbUsers     = "Number :";
$lastUser    = "Last :";

$nbAnonymousVisit  = "Anonymous :";
$nbUsersVisit      = "Members :";
$nbAdminVisit      = "Administrators :";

$tEventStat   = "Statistiques";
$nbSubscribe  = "Subscribers :";
$nbVisite     = "Visits :";
$nbTeams      = "Teams :";
$nbPlayers    = "Players :";
$nbMatchs     = "Matchs :";
$nbEvents     = "Total :";

$badnetVersion = "Version ";
$badnetCacheSince = "";

// Label des boutons
$btnRegisterAll  = "Save all";
$btnRegister  = "Save";
$btnDelete    = "Delete";
$btnModify    = "Modify";
$btnCancel    = "Cancel";
$btnNew       = "New";
$btnClose     = "Close";
$btnSearch    = "Find";
$btnConfident = "Confidential";
$btnPrivate   = "Private";
$btnPublic    = "Public";
$btnHelp      = "Help";
$btnPlus      = "More info";
$btnMoins     = "Hide info";
?>