<?php

$tSubsList    = "Abonnements";
$msgSubscript = "Abonnez-vous maintenant aux résultats!";

$tManagerList = "Contacts";
$helpManager  = "Contacter un gestionnaire du tournoi :";

$msgDirectLink    = "Direct link on this page:";
$badnetLink       = "Direct link on this page:";
$msgDataBaseError = "Database error. Try later.";

$lgdMaindraw  = "M : Main draw";
$lgdQualif    = "Q : Qualification";
$lgdReserve   = "R : Reserve";
$lgdWdn       = "WDN : WO";
$lgdPtq       = "PTQ : Promoted to qualif";
$lgdPtm       = "PTM : Promoted to main draw";


?>