<?php
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$draws       = "Draws";

// Sous menu
$itPairs     = "Players/pairs";
$itGroup     = "Groups";
$itQualif    = "Qualifications";
$itMainDraw  = "Main draw";
$itPdf       = "Pdf Document";

// Titre des colonnes
$rowsPairs1  = "FAMILY NAME";
$rowsPairs2  = "Level";
$rowsPairs3  = "Int. rank";
$rowsPairs4  = "Nat rank";
$rowsPairs5  = "Stage";
$rowsPairs6  = "Seed";
$rowsPairs7  = "Team";

// Messages
$msgNoDraw       = "No draw available.";
$msgNoPublic     = "Draw not available.";
$msgNoPlayers    = "No player in this draw.";
$msgNoAvailable  = $msgNoPublic;
?>