<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/t_user.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$main = "Send an email";

// Titre  des fenetres
$tSendMail = "Contact administrator";

// Label des zones
$from    = "From :";
$fromEmail = "Your email :";
$to      = "To :";
$subject = "Subject :";
$message = "Message :";
$Home    = "Back ";

// Legende des bloc

// Label des boutons
$btnMail  = "Send";
$btnLoose  = "Loose password ?";

// Label des message
$msgfrom       = "Please, let identify yourself.";
$msgfromEmail  = "Your email address is required.";
$msgsubject    = "Please, fill in the subject form.";
$msgnoValidEmail = "Your email is not valid.";
$msgmessage      = "Write here your message !!!";
$msgSend         = "Your message have been successfully sent.";


?>
