<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$events = "Tournament";

// Sous menus
$itPractical = "Practical";
$itSubscribe = "Subscribe";
$itContacts  = "Contacts";
$itStats     = "Statistiques";

// Titres
$tCompetStat   = "Competition";
$tVisitsStat   = "Visitors";
$tInfoGene     = "Informations";
$tDirectAccess = "Direct access";
$tNews         = "Last news";

// Label des zones
$evntDate       = "Date";
$evntPlace      = "Venue";
$evntOrganizer  = "Organisateurs";
$evntDeadline   = "Entries dead line";
$evntDatedraw   = "Draws";
$evntUrl        = "Official web site";

$nbTeams      = "Federations";
$nbPlayers    = "Players";
$nbMatchs     = "Matches";
$nbVisite     = "Visitors";
$nbSubscribe  = "Subscribe";

$from      = "From :";
$fromEmail = "Email :";
$to        = "To :";
$subject   = "Objet :";
$message   = "Message :";

$email        = "Email";
$news         = "Send me news";

// Colonnes
$rowsTeams1  = "Federations";
$rowsTeams2  = "Stamps";

$rowsEvents1 = "Name of the tournaments";
$rowsEvents2 = "Date";
$rowsEvents3 = "Visited";

// Messages
$msgSubscription = "Select association and give your email. We send you results for each match of the federation.";
$msgNoContact  = "Sorry, no contact for this tournament.";
$msgfromEmail  = "Give your email. You 'll receive a copy of the email.";
$msgsubject    = "Object is mandatory";
$msgmessage    = "Message is mandatory.";

// Boutons
$btnSubscribe   = "Subscribe";
$btnUnsubscribe = "Unsubscribe";
$btnInfo        = "Information";
$btnMail        = "Send";

?>