<?php

include dirname(__FILE__)."/menu_V.inc";

// Titre  du navigateur
$live    = "Direct live";

// Sous menus
$itList      = "Matches";
$itLive      = "Live scoring";
$itStream    = "Streaming";
$itLast      = "Last";

// Titre des colonnes
$rowsMatchesV1  = "Event";
$rowsMatchesV2  = "Phase";
$rowsMatchesV3  = "Round";
$rowsMatchesV4  = "Player/Pair A";
$rowsMatchesV5  = "Player/Pair B";
$rowsMatchesV6  = "Court";
$rowsMatchesV7  = "Start";

$rowsMatchs4  = "Status";
$rowsMatchs5  = "Court";
$rowsMatchs6  = "Score";
$rowsMatchs7  = "Start";
$rowsMatchs8  = "End";
$rowsMatchs9  = "Length";

$rowsResults1  = $rowsMatchesV1;
$rowsResults2  = $rowsMatchesV2;
$rowsResults3  = $rowsMatchesV3;
$rowsResults4  = $rowsMatchesV4;
$rowsResults5  = $rowsMatchesV5;
$rowsResults6  = "Score";
$rowsResults7  = "Start";
$rowsResults8  = "End";
$rowsResults9  = "Length";


// Messages
$msgNoTies    = "No match today. Consult the calendar.";
$msgNoLiveNow = "No match now. Try latter.";
$msgOnlyIE  = "Are you using IE !? No chance, there is not plugin available. Install Firefox or use VCL.";
$msgVLC    = "Install VLC with the Firefox plugin.";
$msgLink   = "If the plugin don't work, use VLC with the link above";
$msgNoStream = "Pas de video en direct pour ce tournoi.";

?>
