<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$matches    = "Lived";

// Titres des fenetres
$tOrderMatch    = "Matches order";
$itList         = "Matchs";
$itLive         = "Live score";
$itStream       = "Stream video";
$itLast         = "Last results";

// titre des blocs

// Titre des colonnes
$rowOrder1  = "Order";
$rowOrder2  = "Discipline";

$rowsMatchs4  = "Status";
$rowsMatchs5  = "Court";
$rowsMatchs6  = "Score";
$rowsMatchs7  = "Length";

$rowsMatchesV1  = "Draw";
$rowsMatchesV2  = "Round";
$rowsMatchesV3  = "Step";
$rowsMatchesV4  = "Player/Pair A";
$rowsMatchesV5  = "Player/Pair B";
$rowsMatchesV6  = "Court";
$rowsMatchesV7  = "Begin";

$rowsControl1  = "Order";
$rowsControl2  = "Match";
$rowsControl3  = "Team A";
$rowsControl4  = "Team B";
$rowsControl5  = "Status";
$rowsControl6  = "Court";
$rowsControl7  = "Begin";
$rowsControl8  = "End";
$rowsControl9  = "Score";

$rowUmpires1  = "NAME";
$rowUmpires2  = "Court";
$rowUmpires3  = "Function";
$rowUmpires4  = "Rank";
$rowUmpires5  = "Sleep";
$rowUmpires6  = "Now";

$rowsList1  = "Num";
$rowsList2  = "Draw";
$rowsList3  = "Step";
$rowsList4  = "Player/Pair A";
$rowsList5  = "Player/Pair B";
$rowsList6  = "Court";
$rowsList7  = "Begin";
$rowsList8  = "End";
$rowsList9  = "Score";

$rowsResults1  = "Group";
$rowsResults2  = "Match";
$rowsResults3  = "Player/Pair A";
$rowsResults4  = "Player/Pair B";
$rowsResults5  = "Score";
$rowsResults6  = "Length";

// Label des zones
$dateList  = "Date :";
$placeList = "Place :";
$stepList  = "Step :";
$displayEnded = "Display ended matchs";
$courtNumber  = "Court :";
$status1  = "Winner";
$status2  = "Looser";
$status3  = "Official";
$umpire        = "Umpire :";
$umpireAffected   = "Assign an umpire on this match";
$serviceJudge  = "Service judge :";
$blkOptions    = "Display options";
$blkUmpire     = "Umpire select";

$teamDeclaration = "Teams declaration form (PDF)";
$teamEdit        = "Teams and results of the tie";
$teamResults     = "Tie result (PDF)";
$editSchedule    = "Schedule and court";
$matchEdit       = "Teams and result of the match";
$scoresheetEdit  = "Match score sheet";
$matchOrder      = "Match order";

$levelTrace    = "Log level :";
$fontList      = "Live font :";
$courtNumberLive  = "Display court";
$courtNumberClose = "Close court";

$msgOnlyIE  = "Plugin exist only for Internet Explorer.";
$msgWinamp = "Otherwise you can use Winamp.";
$msgVLC    = "or VideoLan VLC.";
$msgLink   = "Use the address below.";

// Messages d'erreur 
$msgNoTies = "No match today. Please, look at the schedule.";
$msgNoDate = "No date selected";
$msgNotie_place = "No place";
$msgNotie_step  = "No step";
$msgNoLive = "No live score for this event";
$msgNoStream  = "No streaming video for this event";
$msgNoLiveNow = "No live for the moment. Try later.";

// Label des boutons
$btnUp   = "Up";
$btnDown = "Down";
$btnEnd  = "End";
$btnMagic = "Order proposed";
$btnInitServer = "Start live server";

?>
