<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";
include dirname(__FILE__)."/t_mber.inc";

// Titre  du navigateur
$mber      = "Etat civil";

// Titres des fenetres
$itAllMembers = "All members";
$itOthers      = "Others";
$itArrivals    = "Arrivals";
$itDepartures  = "Departures";
$tNewMember    = "Add member";
$tEditMember   = "Edit member";
$tMembers     = "All members";
$tPlayers     = "Registered players";
$tOfficials   = "Registered officials";
$tOthers      = "Others registered members";
$tPurchases   = "Purchases list";
$tAccount     = "Change acocunt";
$tCredits     = "Credits list";
$tArrivals    = "Artivals list";
$tDepartures  = "Departures list";

// Titre des colonnes
$rowsMembers1  = "Gender";
$rowsMembers2  = "Firstname";
$rowsMembers3  = "Name";
$rowsMembers4  = "Date of birth";
$rowsMembers5  = "IBF number";
$rowsMembers6  = "Licence";
$rowsMembers6  = "Comment";

$rowsRegis1  = "Gender";
$rowsRegis2  = "Id";
$rowsRegis3  = "Function";
$rowsRegis4  = "Account";
$rowsRegis5  = "Purchase";
$rowsRegis6  = "Discount";
$rowsRegis7  = "Paid";
$rowsRegis8  = "Balance";

$rowsDeparr1  = "Gender";
$rowsDeparr2  = "Id";
$rowsDeparr3  = "Team";
$rowsDeparr4  = "Function";
$rowsDeparr5  = "Time";
$rowsDeparr6  = "Place";


// Label des zones
$regiName    = "Registration :";
$regiId      = $regiName;
$accountName = "Current account :";
$accountId = "New account :";
$regiArrival    = "Arrival date :";
$regiArrcmt     = "Arrival place :";
$regiDeparture  = "Departure date :";
$regiDepcmt     = "Departure place :";
$propagate      = "Update arrival and departure of all registered members of this association";

// Label des listes

// Messages d'erreur
$msgNoMembers = "No member found.";

// Label des boutons

?>
