<?php

// Menu general
$itHome      = "Home";
$itEvents    = "Tournaments";
$itExit      = "Deconnect";
$itGeneral   = "Informations";
$itRegister  = "Entries";
$itDraws     = "Draws";
$itCalendar  = "Program";
$itResults   = "Results";
$itRanking   = "Ranking";
$itToday     = "Today";
$itEvent     = "Others tournament";


// Sous menu
$itTeams     = "Teams";
$itPlayers   = "Players";
$itOfficials = "Officials";


?>