<?php

$itReload  = "Reload";
$itNew     = "New";
$itDelete  = "Delete";
$itRestore = "Restore";
$itErase   = "Supress";
$itMerge   = "Merge";

$itBadge   = "Badges";
$itSearch  = "Search";
$itExit    = "Exit";
$itClose   = "Close";
$itMail    = "Mail";
$itHome    = "Home";
$itNone    = "&nbsp;";

$itPref     = "Preferences";
$itUsers    = "Users";
$itEvents   = "Events";
$itBooks    = "Addresses book";
$itAdmi     = "Parameters";
$itMaint    = "Maintenance";
$itPhpInfo  = "Php info";
$itHelp     = "Help";
$itSubs     = "Subscription";

$itAttribs = "Generalities";
$itGeneral = "Pratical";
$itClubs   = "Associations";
$itTeams   = "Teams";
$itPlayers = "Players";
$itRegister = "Entries";
$itOfficials = "Court Officials";
$itOthers    = "Others";
$itDraws     = "Draws";
$itProgram   = "Schedule";
$itCalendar  = "Schedule";
$itDivisions = "Divisions";
$itResults   = "Results";
$itRanking   = "Ranking";
$itSchedule  = "Schedule";
$itManage    = "Management";
$itTies      = "Ties";
$itTransfert = "Import/Export";

$itGroup    = "Groups";
$itQualif   = "Qualifications";
$itMainDraw = "Main draw";

$itSport     = "Sportif";
$itAdmin     = "Administratif";

$itItems     = "Items";
$itAccounts  = "Accounts";
$itPurchases = "Purchases";
$itToday     = "Today";
$itPrint     = "Edition";

$itEvent     = "Others events";

$itConfident = "Confidential";
$itPrivate   = "Private";
$itPublic    = "Public";

$itEdit          = "Edit";
$itAutorisations = "Rights";
$itPublication   = "Publication";

$itSH = "SH";
$itSD = "SD";
$itDH = "DH";
$itDD = "DD";
$itMX = "MX";
$itInscrits = "Members list";


?>
