<?php

include "menu.inc";
include "badnet.inc";

// Titres des fenetres
$tDraws    = "Draws management";


// Titre des colonnes
$rowsEvents2  = "Name";
$rowsEvents3  = "Date";
$rowsEvents4  = "Place";
$rowsEvents5  = "Organisator";
$rowsEvents6  = "Comment";
$rowsEvents7  = "Owner";


// Label des zones


// Label des listes


// Messages d'erreur
$msgRegistered  = "Changes have been registered";

// Label des boutons
$End       = "Close";
$Cancel    = "Cancel";
$Validate  = "Ok";
$Register  = "Register";
$AddUser    = "Add user";
$RemoveUser = "Remove user";


?>
