<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$pairs    = "Pairs";

// Titres des fenetres
$tEditPair      = "Pairs modification";
$tPubliPairs    = "Players/pairs publication";
$tDelPairs      = "Pairs deletion";
$tSelectPair    = "Pairs choice";
$tSelectPartner = "Partner choice";
$tStatusPairs   = "Players/pairs status";
$tAskRank       = "Updating ranks";
$tImplode       = "Pair composition";

$itAdd    = "Add";
$itRemove = "Remove";

// Titre des colonnes
$rowsPairs1  = "Gender";
$rowsPairs2  = "FAMILY NAME ";
$rowsPairs3  = "NOC";
$rowsPairs4  = "Level";
$rowsPairs5  = "Entrie";

$rowsPlayers1  = "Gender";
$rowsPlayers2  = "FAM.NAME Firstname";
$rowsPlayers3  = "NOC";
$rowsPlayers4  = "IBF Num";
$rowsPlayers5  = "License";

$pairList1 = "Seed";
$pairList2 = "Position";
$pairList3 = "New status";
$pairList4 = "Status";
$pairList5 = "Players/pairs";

$pairList2ko1 = "Seed";
$pairList2ko2 = "Rank";
$pairList2ko3 = "Position";
$pairList2ko4 = "Pair";
$pairList2ko5 = "Team";


$pairGroups1 = "Seed";
$pairGroups2 = "Position";
$pairGroups3 = "Players/Pairs";
$pairGroups4 = "Team";
$pairGroups5 = "Level";
$pairGroups6 = "Points";

// Label des zones
$pairId = " #";
$echoDisci ="Discipline :";
$pairIbfNum = "International number :";
$pairNatNum = "National number :";
$pairIntRank = "International ranking :";
$pairNatRank = "National ranking :";
$pairStatus  = "Status :";
$pairOrder   = "Position :";
$pairCmt     = "Comment";
$pairWo      = "WO";
$pairDateWo  = "WO date";
$msgTds      = "Seed";
$msgPosition = "Position";
$msgStatus   = "New status";
$msgPair     = "Players/Pairs";
$nbsp3       = "Nombre de sortant par poule de 3 :";
$nbsp4       = "Nombre de sortant par poule de 4 :";
$nbsp5       = "Nombre de sortant par poule de 5 :";
$nbSecond    = "Nombre de meilleur second :";
$nbQualif    = "Nombre total de qualifiés :";

/* Messages d'erreur */
$msgNeedPairs  = "Select a player/pair";
$msgConfirmDel = "Do you want to delete the selected players/pairs.";

// Label des boutons
$btnNew = "New registration";
$btnInt = "International";
$btnNat = "French";
$btnSeeded = "Drawing lot";

?>
