<?php

include dirname(__FILE__)."/badnet.inc";
include dirname(__FILE__)."/menu.inc";

// Titre  du navigateur
$prefs      = "Preferences";

// Titres des fenetres

// Titres des blocs
$blkMail = "Email";

// Titre des colonnes
$rowsRanks ="Ranking"; 
$rowsRanks1 ="Label"; 
$rowsRanks2 ="Point"; 
$rowsRanks3 ="Level"; 

// Label des zones
$host = "SMTP server:";
$port = "Connection port:";
$username = "Name :";
$password = "Password :";
$ffbaEmail = "FFBa email:";
$ffbaUrl = "Url national ranking :";
$ibfUrl = "Url international ranking :";

// Label des listes

// Messages d'erreur

// Label des boutons
$btnUpdateMail = "Ok";
$btnAddRank    = "Add";
$btnDelRank    = "Delete";
?>
