<?php
/* Chaines de caractere pour les libelles des champs de la table 
des associations */

// Label des zones
$assoName       = "Name :";
$assoPseudo     = "Acronym :";
$assoStamp      = "Stamp :";
$assoType       = "Type :";
$assoCmt        = "Comment :";
$assoUrl        = "Website Url :";
$assoLogo       = "Logo :";
$assoNoc        = "Olympic code (NOC) :";

// Messages d'erreur
$msgassoName  = "Name is required.";
$msgassoStamp = "Stamp is required.";
$msgassoType  = "Select a type in the list.";

?>
