<?php
/* Chaines de caractere pour les libelles des champs de la table draws */

$serialName   = "Label :";
$serial_ms     = "Men Singles";
$serial_ls     = "Women Singles";
$serial_md     = "Men Doubles";
$serial_ld     = "Women Doubles";
$serial_mx     = "Mixed Doubles";

$drawSerial = "Serial :";
$drawName   = "Name :";
$drawStamp  = "Acronym :";
$drawDisci  = "Discipline :";
$drawType   = "Type :";
$drawNbp3   = "Number of Group of 3 :";
$drawNbs3   = "number qualifiers :";
$drawNbp4   = "Number of Group of 4 :";
$drawNbs4   = "number qualifiers :";
$drawNbp5   = "Number of Group of 5 :";
$drawNbs5   = "number qualifiers :";
$drawNbsd   = "Best second :";
$drawNbq    = "number qualifiers :";
$drawNbplq  = "Number of place in qualification :";
$drawNbpl   = "Number of place in main draw :";
$drawNbpt   = "Number of points :";
$drawNbset  = "Number de sets :";
$drawNbplg  = "Setting :";

$msgserialname   = "Label is required !";

?>
