<?php
/* Chaines de caractere pour les libelles des champs de la table event */
$evntName        = "Name :";
$evntPlace       = "Place :";
$evntDate        = "Date :";
$evntOrganizer   = "Organisation :";
$evntDatedraw    = "Draw :";
$evntDeadline    = "Registration deadline :";
$evntCmt         = "Comment :";
$evntDrawdate    = "Seed :";
$evntNature      = "Event nature :";
$evntLevel       = "Event level :";
$evntNumauto     = "Authorisation number :";
$evntUrl         = "Official Website :";
$evntPoster      = "Poster :";
$evntNbvisited   = "Visit Counter :";
$evntId          = "Identification number :";
$evntScoring     = "Score system :";
$evntRanking     = "Ranking system :";
$evntNbDrawMax   = "Max draws :";
$evntUrlRank     = "URL ranking :";
$evntFirstday    = "First day (dd-mm-aa) :";
$evntLastday     = "Last day (dd-mm-aa) :";
$evntZone        = "Zone :";
$evntOwnerId     = "Owner :";
$evntSeason      = "Season :";

$msgevntName   = "Event name is required !";
?>
