<?php


/* Chaines de caractere pour les libelles des champs de la table 
des items */

// Label des zones
$itemName      = "Name :";
$itemCode      = "Code :";
$itemRef       = "Reference :";
$itemCount     = "Quantiy :";
$itemIsFollowed = "Followed";
$itemIsCreditable = "Creditable";
$itemRubrikId   = "Rubrique :";
$itemValue      = "Value :";

$IS = "Single :";
$ID = "Double :";
$IM = "Mixed :";
$I1 = "One draw :";
$I2 = "Two draws :";
$I3 = "Three draws :";

// Messages d'erreur
$msgitemName   = "Name is required.";
$msgitemValue  = "Value is required.";

?>