<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$mberSexe       = "Gender :";
$mberSexe1      = "Mister";
$mberSexe2      = "Madam, miss";
$mberFirstName  = "Firstname :";
$mberSecondName = "Name :";
$mberBorn       = "Date of Birth :";
$mberIbfNumber  = "IBF number :";
$mberLicence    = "Licence :";
$mberCmt        = "Comment :";


// Messages d'erreur
$msgmberSexe = "Select member's gender";
$msgmberFirstName = "Firstname is required.";
$msgmberSecondName = "Name is required.";

?>
