<?php
/* Chaines de caractere pour les libelles des champs de la table 
des membres */


// Label des zones
$regiDate       = "Registration date :";
$regiType       = "Type :";
$regiLongName   = "Name (long) :";
$regiShortName  = "Name (short) :";
$regiTeamId     = "Team :";
$regiTeamName   = "Team :";
$regiCmt        = "Comment :";
$regiFunction   = "Function :";
$regiNoc        = "NOC :";
$regiArrival    = "Arrival :";
$regiArrCmt     = "Precision :";
$regiDeparture  = "Departure :";
$regiDepCmt     = "Precision :";

$regiStatus1    = "Holder";
$regiStatus2    = "Remplacement";
$regiStatus3    = "Other";

$regiType1 = "Referee";
$regiType2 = "Deputy Referee";
$regiType3 = "Umpire";
$regiType4 = "Line judges";
$regiAccountId1 = "Association account";
$regiAccountId2 = "Personnal account";

// Messages d'erreur

?>
