<?php
/* Chaines de caractere pour les libelles des champs de la table 
des equipes */

// Label des zones
$teamDate       = "Date :";
$teamName       = "Name :";
$teamStamp      = "Stamp :";
$teamCaptain    = "Captain :";
$teamCmt        = "Comment :";
$teamClub       = "Federation :";
$teamUrl        = "Web :";
$teamNoc        = "Olympic code (NOC) :";
$assoId         = "Association :";

// Messages d'erreur
$msgteamName  = "Name is required.";
$msgteamStamp = "Stamps is required.";

?>
