<?php
/* Chaines de caractere pour les libelles des champs de la table user */

$userName   = "Name :";
$userLogin  = "Login :";
$userPseudo = "Pseudo :";
$userPass   = "Password :";
$userLang   = "Langage :";
$userEmail  = "Email :";
$userCmt    = "Comment :";
$userId     = "User Id :";
$userLastvisit = "Last visit :";
$userNbcnx     = "Connections number :";

$msguserName   = "Name is required !";
$msguserPseudo = "Pseudo is required !";
$msguserLogin  = "Login is requred !";
$msguserPass   = "Password is required !";

?>
