<?php
include dirname(__FILE__)."/menu_V.inc";
include dirname(__FILE__)."/t_teams.inc";

// Titre  du navigateur
$teams  = "Teams";

// Actions
$itConvocsPdf  = "Pdf document";

// Label des zones
$assoPseudo     = "Acronym :";
$assoStamp      = "Sigla :";
$assoUrl        = "Web site :";
$assoNoc        = "Country (NOC) :";

// Titre des colonnes
$rowsPairs_V1 = "Players/Pairs";
$rowsPairs_V2 = "Draw";
$rowsPairs_V3 = "Int. Rank";
$rowsPairs_V4 = "Nat. Rank";
$rowsPairs_V5 = "Level";
$rowsPairs_V6 = "Points";

$rowsPlayers1 = "Gender";
$rowsPlayers2 = "FAMILY NAME First name";
$rowsPlayers3 = "Draws";
$rowsPlayers4 = "Convocation";
$rowsPlayers5 = "Sporthall";

$rowsRegis1 = "Gender";
$rowsRegis2 = "FAMILY NAME First name";
$rowsRegis3 = "License";
$rowsRegis4 = "IBF";
$rowsRegis5 = "Level";
$rowsRegis6 = "Entries";
$rowsRegis7 = "Convocation";
$rowsRegis8 = "Sporthall";

$rowsTies1  = "Group";
$rowsTies2  = "Date";
$rowsTies3  = "Stage";
$rowsTies4  = "Opponent";
$rowsTies5  = "Result";
$rowsTies6  = "Score";

$rowsPlayers_V1 = "Gender";
$rowsPlayers_V2 = "FAMILY NAME";
$rowsPlayers_V3 = "Ranking";

// Messages
$msgConvocation = "Le premier match d'un joueur est 30 minutes aprés l'heure de convocation";
$msgNoPlayers      = "The player's list is not available.";
$msgNoAutorisation = "Informations for this federation are not available.";
$msgNoTies         = "The list of the ties is no available.";


?>