<?php
/*****************************************************************************
!   $Id$
******************************************************************************/

define('BADNET_EVENT',        PROJECT_BADNET |0x000000);
define('BADNET_CAPTAIN',      PROJECT_BADNET |0x000100);
define('BADNET_IMPORT',       PROJECT_BADNET |0x000200);
define('BADNET_TRANSFERT',    PROJECT_BADNET |0x000300);
define('BADNET_ADM',          PROJECT_BADNET |0x000400);
define('BADNET_PUBLI',        PROJECT_BADNET |0x000500);
define('BADNET_TEAM',         PROJECT_BADNET |0x000600);
define('BADNET_PREFERENCE',   PROJECT_BADNET |0x000700);
define('BADNET_DIV',          PROJECT_BADNET |0x000800);

define('BADNET_UMPIRE',       PROJECT_BADNET |0x000E00);
define('BADNET_LIVE',         PROJECT_BADNET |0x000F00);
define('BADNET_END',          PROJECT_BADNET |0x00FF00);

?>
