<?php
include_once "Badnet/Badnet.inc";

$indice = BADNET_PREFERENCE;
define('BPREF_PAGE_PREFERENCES',  $indice++);
define('BPREF_PAGE_ADMIN',        $indice++);
define('BPREF_UPDATE_ADMIN',      $indice++);
define('BPREF_PAGE_SPORTIVE',     $indice++);
define('BPREF_UPDATE_SPORTIVE',   $indice++);
define('BPREF_PAGE_CAPTAIN',      $indice++);
define('BPREF_UPDATE_CAPTAIN',    $indice++);
define('BPREF_PAGE_INLINEIC',     $indice++);
define('BPREF_UPDATE_INLINEIC',   $indice++);
define('BPREF_PAGE_PRINT',        $indice++);
define('BPREF_UPDATE_PRINT',      $indice++);
define('BPREF_VISU_PRINT',        $indice++);
define('BPREF_DELETE_LOGO',       $indice++);
define('BPREF_PAGE_PRIVILEGES',   $indice++);
define('BPREF_PAGE_NEW_PRIVILEGE', $indice++);
define('BPREF_UPDATE_PRIVILEGE',  $indice++);
define('BPREF_PAGE_DELETE_PRIVILEGE',  $indice++);
define('BPREF_DELETE_PRIVILEGE',  $indice++);
define('BPREF_FILL_PRIVILEGE',    $indice++);
define('BPREF_SEARCH_USERS',      $indice++);
define('BPREF_PAGE_PRESENTATION', $indice++);
define('BPREF_UPDATE_PRESENTATION', $indice++);
define('BPREF_DELETE_POSTER',     $indice++);
define('BPREF_PAGE_WEIGHT',       $indice++);

define('BPREF_PAGE_INLINE',       $indice++);
define('BPREF_PAGE_FEES',         $indice++);
define('BPREF_PAGE_DOWNLOAD',     $indice++);
define('BPREF_PAGE_SCORING',      $indice++);

?>