<?php
/*****************************************************************************
!   Module     : Account
!   File       : $Source: /cvsroot/aotb/badnet/src/account/account.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.2 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2006/10/27 11:04:56 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/
define("ACCOUNT_MEMBERS",    WBS_ACT_ACCOUNT+1);
define("ACCOUNT_CREDITS",    WBS_ACT_ACCOUNT+2);
define("ACCOUNT_SELECT",     WBS_ACT_ACCOUNT+3);
define("ACCOUNT_PRINT",      WBS_ACT_ACCOUNT+4);

?>
