<?php
/*****************************************************************************
!   Module     : Assocs
!   File       : $Source: /cvsroot/aotb/badnet/src/asso/asso.inc,v $
!   Version    : $Name:  $
!   Revision   : $Revision: 1.3 $
!   Author     : G.CANTEGRIL
!   Revised by : $Author: cage $
!   Date       : $Date: 2006/09/05 20:56:30 $
!   Mailto     : cage@free.fr
******************************************************************************
!   License   : Licensed under GPL [http://www.gnu.org/copyleft/gpl.html]
!      This program is free software; you can redistribute it and/or
!      modify it under the terms of the GNU General Public License
!      as published by the Free Software Foundation; either version 2
!      of the License, or (at your option) any later version.
!
!      This program is distributed in the hope that it will be useful,
!      but WITHOUT ANY WARRANTY; without even the implied warranty of
!      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!      GNU General Public License for more details.
!
!      You should have received a copy of the GNU General Public License
!      along with this program; if not, write to the Free Software
!      Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, 
!      USA.
******************************************************************************/

define("ASSOC_CREATE",          WBS_ACT_ASSOC+1);
define("ASSOC_REGISTER",        WBS_ACT_ASSOC+2);
define("ASSOC_SEARCH",          WBS_ACT_ASSOC+3);
define("ASSOC_EDIT",            WBS_ACT_ASSOC+4);
define("ASSOC_DETAIL_ADMIN",    WBS_ACT_ASSOC+5);
define("ASSOC_RESERVATION",     WBS_ACT_ASSOC+7);
define("ASSOC_DISCOUNT",        WBS_ACT_ASSOC+8);
define("ASSOC_CREDITS",         WBS_ACT_ASSOC+9);
define("ASSOC_EDIT_ACCOUNT",    WBS_ACT_ASSOC+10);
define("ASSOC_UPDATE_ACCOUNT",  WBS_ACT_ASSOC+11);
define("ASSOC_ARRIVALS",        WBS_ACT_ASSOC+12);
define("ASSOC_DEPARTURES",      WBS_ACT_ASSOC+13);
define("ASSOC_FIND",            WBS_ACT_ASSOC+14);
define("ASSOC_SELECT_LOGO",  WBS_ACT_ASSOC+18);
define("ASSOC_UPDATE_LOGO",  WBS_ACT_ASSOC+19);

define("ASSOC_CMD_PLAYERS",  WBS_ACT_ASSOC+20);
define("ASSOC_CMD_ITEMS",    WBS_ACT_ASSOC+21);
define("ASSOC_CMD_DATE",     WBS_ACT_ASSOC+22);
?>