<?php
include_once "Badnet/Badnet.inc";

$indice = BADNET_TRANSFERT;
define('BTRANSFERT_PAGE_IO',       $indice++);
define('BTRANSFERT_PAGE_I',        $indice++);
define('BTRANSFERT_PAGE_O',        $indice++);
define('BTRANSFERT_EXPORT_TIES',   $indice++);
define('BTRANSFERT_EXPORT_HALL',   $indice++);
define('BTRANSFERT_EXPORT_FULL',   $indice++);
define('BTRANSFERT_EXPORT_POONA',  $indice++);
define('BTRANSFERT_IMPORT_TIES',   $indice++);
define('BTRANSFERT_IMPORT_DIVS',   $indice++);
define('BTRANSFERT_IMPORT_HALL',   $indice++);
define('BTRANSFERT_IMPORT_FULL',   $indice++);
define('BTRANSFERT_LOAD_DIVS',     $indice++);
define('BTRANSFERT_LOAD_TIES',     $indice++);
define('BTRANSFERT_SELECT_TIES',   $indice++);
define('BTRANSFERT_CONTROL_TIES',  $indice++);
define('BTRANSFERT_PAGE_TIES',     $indice++);

?>